---
title: "PCA obj"
output: html_document
---

```{r libs & paths}
library(Seurat)
library(ggplot2)
library(dplyr)
library(pbapply)
data_in <- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/DimRedPaper/Zheng4/sce_full_Zhengmix4eq.rds"
data_out <- "/Users/elise/Desktop/GitHub/Hubness_sc/forTAC/results/Zheng4/zheng4_pca_readyforhubness.txt"
sdev_out <- "/Users/elise/Desktop/GitHub/Hubness_sc/forTAC/results/Zheng4/zheng4_pca_sdev.txt"
```

```{r functions}
filter <- function(df) {
  feature <- apply(df,2,function(x) sum(x!=0, na.rm = T))
  count <- apply(df,2,function(x) sum(x, na.rm=T))
  print(plot(feature,count))
}
data_prep <- function(data) {
  data <- log10(data+1)
  return(data)
}
```

```{r do PCA}
data <- readRDS(data_in)
data <- data@assays$data$counts # 15568 x 3994
data <- data[apply(data,1,function(x) sum(x!=0, na.rm=T))>2,] # 12885 x 3994
filter(data)
nfeature <- apply(data,2,function(x) sum(x!=0, na.rm=T))
data <- data[,nfeature<2e3]  # 12885 x 3992
write.csv(data,"/Users/elise/Desktop/GitHub/Hubness_sc/data/Zheng4/data.csv")
# Normalize + log transfo + scale
data <- data_prep(data)
# PCA
hvg <- apply(data,1,var)
genes<-names(sort(hvg,decreasing = T))[1:5e3]
pca <- prcomp(data[genes,])
data_proj <- t(pca$rotation)
# 3992 PCs
write.table(data_proj, file=data_out)
write.table(pca$sdev,file=sdev_out)
```
