---
title: "Do we have hubs?"
output:
  html_document: default
  pdf_document: default
---

```{r libs, results="hide", include = FALSE}
library(philentropy, quietly = T)
library(ggplot2, quietly = T)
library(viridis, quietly = T)
library(ggridges, quietly = T)
library(scales, quietly = T)
library(ggpubr, quietly = T)
library(pbapply)
```

```{r functions, include = FALSE}
data_load <- function(path) {
   source(file=path)
   return(hubness)
}
data_hubness <- list("Baron"=data_load("/Users/elise/Desktop/Github/Hubness_sc/forTAC/hubness_load_write_data_Baron.R"),
                     "Silver"=data_load("/Users/elise/Desktop/Github/Hubness_sc/forTAC/hubness_load_write_data_Silver.R"),
                     "Zheng4"=data_load("/Users/elise/Desktop/Github/Hubness_sc/forTAC/hubness_load_write_data_Zheng4.R"))
data_pca <- list("Baron"=read.table("/Users/elise/Desktop/Github/Hubness_sc/forTAC/results/Baron/baron_pca_readyforhubness.txt"),
                 "Silver"=read.table("/Users/elise/Desktop/Github/Hubness_sc/forTAC/results/Silver/silver_pca_readyforhubness.txt"),
                 "Zheng4"=read.table("/Users/elise/Desktop/Github/Hubness_sc/forTAC/results/Zheng4/zheng4_pca_readyforhubness.txt"))


get_hub1 <- function(df,kval,pcval,pval) { # Maximum hubness score
   max = c()
   ymin = c()
   ymax = c()
   y_increment = 1
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
            val = df$score[df$Dimension==d & df$p==p & df$k==k]
            max = c(max, max(val))
            ymin = c(ymin,y_increment)
            ymax = c(ymax,y_increment+1)
         }
      }
     y_increment <- y_increment+1
   }
   hub_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=max,
                         "ymin"=ymin,
                         "ymax"=ymax)
   return(hub_val)
}
plot_thd <- function(df,hub_val,p) {
  plt <- ggplot(hubness, aes(x = score, y = Dimension, fill = Dimension))
  plt + geom_density_ridges() +
      theme_ridges() +
      xlab("Hubness score") +
      ylab("Dimension of the input space") +
      geom_segment(aes(x = GHubness, xend = GHubness, y = ymin, yend = ymax), hub_val[hub_val$Dimension==9047,], colour=hue_pal()(9)[9], inherit.aes = F) +
      geom_segment(aes(x = GHubness, xend = GHubness, y = ymin, yend = ymax), hub_val[hub_val$Dimension==5000,], colour=hue_pal()(9)[8], inherit.aes = F) +
      geom_segment(aes(x = GHubness, xend = GHubness, y = ymin, yend = ymax), hub_val[hub_val$Dimension==1000,], colour=hue_pal()(9)[7], inherit.aes = F) +
      geom_segment(aes(x = GHubness, xend = GHubness, y = ymin, yend = ymax), hub_val[hub_val$Dimension==500,], colour=hue_pal()(9)[6], inherit.aes = F) +
      geom_segment(aes(x = GHubness, xend = GHubness, y = ymin, yend = ymax), hub_val[hub_val$Dimension==100,], colour=hue_pal()(9)[5], inherit.aes = F) +
      geom_segment(aes(x = GHubness, xend = GHubness, y = ymin, yend = ymax), hub_val[hub_val$Dimension==50,], colour=hue_pal()(9)[4], inherit.aes = F) +
      geom_segment(aes(x = GHubness, xend = GHubness, y = ymin, yend = ymax), hub_val[hub_val$Dimension==10,], colour=hue_pal()(9)[3], inherit.aes = F) +
      geom_segment(aes(x = GHubness, xend = GHubness, y = ymin, yend = ymax), hub_val[hub_val$Dimension==5,], colour=hue_pal()(9)[2], inherit.aes = F) +
      geom_segment(aes(x = GHubness, xend = GHubness, y = ymin, yend = ymax), hub_val[hub_val$Dimension==2,], colour=hue_pal()(9)[1], inherit.aes = F) +
      facet_wrap( ~ k) +
      ggtitle(paste0('Hubness maximum score of Lp norm across dimensions,\np=',p))
  
}
get_hub2 <- function(df,kval,pcval,pval) { # Using the mean + 3*sd from Tomasev
   x_thd = c()
   hub_nb = c()
   ymin = c()
   ymax = c()
   y_increment = 1
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
            val = df$score[df$Dimension==d & df$p==p & df$k==k]
            x_thd = c(x_thd, mean(val)+3*sd(val))
            hub_nb = c(hub_nb, sum(val>=(mean(val)+3*sd(val))))
            ymin = c(ymin,y_increment)
            ymax = c(ymax,y_increment+1)
         }
      }
     y_increment <- y_increment+1
   }
   hub_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=hub_nb,
                         "Threshold"=x_thd,
                         "ymin"=ymin,
                         "ymax"=ymax)
   return(hub_val)
}
plot_thd_txt <- function(df,hub_val,p,method_index) {
  plt <- ggplot(hubness, aes(x = score, y = Dimension, fill = Dimension))
  plt + geom_density_ridges() +
      theme_ridges() +
      xlab("Hubness score") +
      ylab("Dimension of the input space") +
      geom_segment(aes(x = Threshold, xend = Threshold, y = ymin, yend = ymax), hub_val[hub_val$Dimension==9047,], colour=hue_pal()(9)[9], inherit.aes = F) +
      geom_segment(aes(x = Threshold, xend = Threshold, y = ymin, yend = ymax), hub_val[hub_val$Dimension==5000,], colour=hue_pal()(9)[8], inherit.aes = F) +
      geom_segment(aes(x = Threshold, xend = Threshold, y = ymin, yend = ymax), hub_val[hub_val$Dimension==1000,], colour=hue_pal()(9)[7], inherit.aes = F) +
      geom_segment(aes(x = Threshold, xend = Threshold, y = ymin, yend = ymax), hub_val[hub_val$Dimension==500,], colour=hue_pal()(9)[6], inherit.aes = F) +
      geom_segment(aes(x = Threshold, xend = Threshold, y = ymin, yend = ymax), hub_val[hub_val$Dimension==100,], colour=hue_pal()(9)[5], inherit.aes = F) +
      geom_segment(aes(x = Threshold, xend = Threshold, y = ymin, yend = ymax), hub_val[hub_val$Dimension==50,], colour=hue_pal()(9)[4], inherit.aes = F) +
      geom_segment(aes(x = Threshold, xend = Threshold, y = ymin, yend = ymax), hub_val[hub_val$Dimension==10,], colour=hue_pal()(9)[3], inherit.aes = F) +
      geom_segment(aes(x = Threshold, xend = Threshold, y = ymin, yend = ymax), hub_val[hub_val$Dimension==5,], colour=hue_pal()(9)[2], inherit.aes = F) +
      geom_segment(aes(x = Threshold, xend = Threshold, y = ymin, yend = ymax), hub_val[hub_val$Dimension==2,], colour=hue_pal()(9)[1], inherit.aes = F) +
      geom_text(aes(x = 7500, label = GHubness, y = ymin+0.5), hub_val, inherit.aes = F) +
      geom_text(aes(x = 7500, label = GHubness, y = ymin+0.5), hub_val, inherit.aes = F) +
      geom_text(aes(x = 7500, label = GHubness, y = ymin+0.5), hub_val, inherit.aes = F) +
      geom_text(aes(x = 7500, label = GHubness, y = ymin+0.5), hub_val, inherit.aes = F) +
      geom_text(aes(x = 7500, label = GHubness, y = ymin+0.5), hub_val, inherit.aes = F) +
      geom_text(aes(x = 7500, label = GHubness, y = ymin+0.5), hub_val, inherit.aes = F) +
      geom_text(aes(x = 7500, label = GHubness, y = ymin+0.5), hub_val, inherit.aes = F) +
      geom_text(aes(x = 7500, label = GHubness, y = ymin+0.5), hub_val, inherit.aes = F) +
      geom_text(aes(x = 7500, label = GHubness, y = ymin+0.5), hub_val, inherit.aes = F) +
      facet_wrap( ~ k) +
      ggtitle(paste0('Number of hubs with Lp norm across dimensions,\np=',p,',\nMethod ',method_index))
  
}
get_hub3 <- function(df,kval,pcval,pval,log=F) { # Using the method from [1] >= 2k
   if (log==T) {
      hub_nb = c()
      ymin = c()
      ymax = c()
      y_increment = 1
      for (d in pcval) {
         for (k in kval) {
            for (p in pval) {
               val = df$score[df$Dimension==d & df$p==p & df$k==k]
               hub_nb = c(hub_nb, sum(val>=2*log(k)))
               ymin = c(ymin,y_increment)
               ymax = c(ymax,y_increment+1)
            }
         }
      y_increment <- y_increment+1
      }
   }
   else {
      hub_nb = c()
      ymin = c()
      ymax = c()
      y_increment = 1
      for (d in pcval) {
         for (k in kval) {
            for (p in pval) {
               val = df$score[df$Dimension==d & df$p==p & df$k==k]
               hub_nb = c(hub_nb, sum(val>=2*k))
               ymin = c(ymin,y_increment)
               ymax = c(ymax,y_increment+1)
            }
         }
      y_increment <- y_increment+1
      }
   }
   hub_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=hub_nb,
                         "ymin"=ymin,
                         "ymax"=ymax)
   hub_val$Threshold <- 2*hub_val$k
   return(hub_val)
}
get_hub4 <- function(df,kval,pcval,pval) { # skewness
   s = c()
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
            val = df$score[df$Dimension==d & df$p==p & df$k==k]
            s = c(s, mean((val-mean(val))^3)/sd(val)^3)
         }
      }
   }
   skewness_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=s)
   skewness_val$Dimension <- factor(skewness_val$Dimension, levels = pcval)
   return(skewness_val)
}
plot_evol_pval <- function(hub_val,method_name,label.y) {
  ggplot(hub_val, aes(x=factor(Dimension), y=GHubness, color=factor(p))) +
   geom_point() +
   ylab(label.y) +
   xlab("Dimension") +
   geom_line(aes(group=p),linetype='dotted') +
   ggtitle(method_name) +
   facet_wrap(~k)
}
plot_evol_pcval <- function(hub_val,method_name,label.y) {
  ggplot(hub_val, aes(x=factor(p), y=GHubness, color=factor(Dimension))) +
   geom_point() +
   ylab(label.y) +
   xlab("p") +
   geom_line(aes(group=Dimension),linetype='dotted') +
   ggtitle(method_name) +
   facet_wrap(~k)
}
get_hub6 <- function(df,kval,pcval,pval) { # anti hubs
   anti_hub = c()
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
           anti_hub = c(anti_hub,unique(df$Antihubs[df$Dimension==d & df$p==p & df$k==k]))
         }
      }
   }
   hub_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=anti_hub)
   hub_val$Dimension <- factor(hub_val$Dimension, levels = pcval)
   return(hub_val)
}
fn_zarb <- function(knn_list) {
   increment = 0
   for (i in 1:nrow(knn_list)) {
      for (j in 1:ncol(knn_list)) {
         if (i %in% knn_list[knn_list[i,j],]) {
            increment <- increment + 1 
      }
    }
   }
   return(1-increment/(nrow(knn_list)*ncol(knn_list)))
}
get_hub7 <- function(data,kval,pcval,pval) { #asymmetry
  knn_graph <- lapply(pcval,
                      function(x) lapply(kval,
                                         function(y) knn.covertree::find_knn(t(data[1:x,]),y)))
  knn_list <- lapply(knn_graph,
                     function(x) lapply(x,
                                        function(y) y$index))
  result <- lapply(knn_list,
                   function(x) sapply(x,
                                      function(y) fn_zarb(y)))
  asy_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=unlist(result))
   asy_val$Dimension <- factor(asy_val$Dimension, levels = pcval)
  return(asy_val)
}
```

```{r figs}
# Merge the dfs
make_merge <- function(hubness,data,kval,pcval,pval,name,size) {
hub_max <- get_hub1(hubness, kval=kval,pcval=pcval,pval=pval)
hub_mean <- get_hub2(hubness, kval=kval,pcval=pcval,pval=pval)
hub_k <- get_hub3(hubness, kval=kval,pcval=pcval,pval=pval)
hub_skew <- get_hub4(hubness, kval=kval,pcval=pcval,pval=pval)
hub_anti <- get_hub6(hubness, kval=kval,pcval=pcval,pval=pval)
#hub_asym <- get_hub7(data, kval=kval,pcval=pcval,pval=pval)
hub_k <- hub_k[,colnames(hub_skew)]
hub_mean <- hub_mean[,colnames(hub_skew)]
hub_max <- hub_max[,colnames(hub_skew)]
hub_k$GHubness <- hub_k$GHubness*100/size
hub_mean$GHubness <- hub_mean$GHubness*100/size
hub_anti$GHubness <- hub_anti$GHubness*100/size
hub_max$GHubness <- hub_max$GHubness/size
hub_max$Method <- "Max"
hub_mean$Method <- "Mean+Sd"
hub_k$Method <- "2k"
hub_skew$Method <- "Skewness"
hub_anti$Method <- "Antihubs"
#hub_asym$Method <- "Asymmetry"
hub <- rbind(hub_max,hub_mean,hub_skew,hub_anti,hub_k)#,hub_asym)
hub$Dataset <- name
return(hub)
}
dataset <- c("Baron","Silver","Zheng4")
pcval <- list(c(2,5,10,20,30,40,50,100,500,1882),
              c(2,5,10,20,30,40,50,100,500,2583),
              c(2,5,10,20,30,40,50,100,500,3991))
size <- c(1883,2584,3992)
df <- pblapply(1:length(dataset),
             function(x) make_merge(data_hubness[[x]],data_pca[[x]],50,pcval[[x]],pval,dataset[x],size[x]))
df_hub <- do.call(rbind,df)
df_hub$Dimension<-as.numeric(df_hub$Dimension)
# Viz
ggplot(df_hub, aes(x=Dimension, y=GHubness)) + geom_line(aes(group=Dataset, color=Dataset)) + geom_point(alpha=0.2) + facet_wrap(~Method, scales = "free")
ggplot(df_hub[df_hub$Method=="Skewness",], aes(x=Dimension, y=GHubness)) + geom_line(aes(group=Dataset, color=Dataset)) + geom_point(alpha=0.2) + ylab("Skewness") + theme(text = element_text(size=20))
```
