---
title: "PCA obj"
output: html_document
---

```{r libs & paths}
library(Seurat)
library(ggplot2)
library(bigSCale)
library(Matrix)

data_in <- "/Users/elise/Desktop/Imagine_bckp/scRNAseq/Data_sc/hubness_data/10X/GSE100866_pca_readyforhubness.csv"
data_icell <- "/Users/elise/Desktop/Imagine_bckp/scRNAseq/Data_sc/hubness_data/10X/GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv"
data_sparse <- "/Users/elise/Desktop/Imagine_bckp/scRNAseq/Data_sc/hubness_data/10X/GSE100866_CBMC_8K_13AB_10X-RNA_umi.mtx"
data_icell_out <- "/Users/elise/Desktop/Imagine_bckp/scRNAseq/Data_sc/hubness_data/10X/GSE100866_CBMC_8K_13AB_10X-RNA_umi.icell2.txt"
data_out_icell <- "/Users/elise/Desktop/Imagine_bckp/scRNAseq/Data_sc/hubness_data/10X/GSE100866_CBMC_8K_13AB_10X-RNA_umi.icell2_pca_readyforhubness.txt"
data_out_icell_sdev <- "/Users/elise/Desktop/Imagine_bckp/scRNAseq/Data_sc/hubness_data/10X/GSE100866_CBMC_8K_13AB_10X-RNA_umi.icell2_pca_sdev.txt"
```

```{r do the minibatch - merging together cells close in dist and kNN graph}
data <- read.table(data_in) # 20400 x 8046
library(FNN)
k=100
kNNG <- get.knn(t(data), k=k)

percent_overlap = 5
to_merge <- list()
for (cell in 1:ncol(data)) {
  to_merge[[as.character(cell)]] <- as.character(cell)
  for (neighbor in 1:k) {
    if (kNNG$nn.dist[cell,neighbor] <= (max(kNNG$nn.dist)+min(kNNG$nn.dist))/2) {
      if (cell%%100==0 & neighbor%%10==0) {
        print(cell)
      }
      cell_neighbor <- kNNG$nn.index[cell,]
      neighbor_neighbor <- kNNG$nn.index[neighbor,]
      enough_overlap <- length(intersect(cell_neighbor,neighbor_neighbor))/k*100 >= percent_overlap
      to_merge[[as.character(cell)]] <- ifelse(enough_overlap,
                                             c(to_merge[[as.character(cell)]],as.character(neighbor)),
                                             to_merge[[as.character(cell)]])
    }
  }
}

seurat <- CreateSeuratObject(data)
seurat[["percent.mt"]] <- PercentageFeatureSet(seurat, pattern = "^MT-")
VlnPlot(seurat, features = c("nFeature_RNA","nCount_RNA","percent.mt"))
FeatureScatter(seurat, feature1 = "nFeature_RNA", feature2 = "nCount_RNA") + 
  geom_vline(xintercept=7500) +
  geom_hline(yintercept=35e+05)
# Remove cells with more than 4000 genes or 15e+03 total counts for Guo
seurat <- subset(seurat, subset = nFeature_RNA<4000 & nCount_RNA<15e+03)
#  cells for Satija
# Normalize + log transfo + scale
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat)
seurat <- RunPCA(seurat, features=rownames(seurat))
ElbowPlot(seurat, ndims=50)
data <- GetAssayData(seurat)
rm(seurat)
# PCA
pca <- prcomp(data)
data_proj <- t(pca$rotation)
#  PCs x  cells for Satija
write.table(data_proj, file=data_out)
```

```{r do the minibatch - pseudo bulk with small clusters (max 10 cells eg)}

```

```{r do the minibatch - iCell from bigSCale2 v1}
# https://github.com/iaconogi/bigSCale2#bigscale-2-icells
# load raw count matrix
data <- read.table(data_icell, sep=",", header=T, row.names = 1) # 36280 x 8617
data <- data[grep("HUMAN_",rownames(data)),] # 20400 genes
rownames(data) <- gsub("HUMAN_","",rownames(data))
nFeature <- apply(data,2,function(x) sum(x!=0))
nCount <- apply(data,2,sum)
# Remove cells with more than 4000 genes or 15e+03 total counts
data <- data[,nFeature<4000 & nCount<15e+03] # 8604 cells for Satija
# MTX format
mat <- writeMM(Matrix(as.matrix(data), sparse = T), file = data_sparse)

# Reduce the size of the data by ca 50%
data_pooled <- iCells(data_sparse, target.cells = 5000)
rownames(data_pooled$icell.mat) <- rownames(data)
data_pooled <- data_pooled$icell.mat
colnames(data_pooled) <- 1:ncol(data_pooled)
```

```{r do the minibatch - iCell from bigSCale2 v2}
# Reduce the size of the data by a factor 10
data_pooled <- iCells(data_sparse, target.cells = 1000)
rownames(data_pooled$icell.data$icell.mat) <- rownames(data)
data_pooled <- data_pooled$icell.data$icell.mat
colnames(data_pooled) <- 1:ncol(data_pooled)
```

```{r re do the PCA}
seurat <- CreateSeuratObject(data_pooled)
# Normalize + log transfo + scale
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat)
data_pooled <- GetAssayData(seurat)
rm(seurat)
# PCA
pca <- prcomp(data_pooled)
data_proj <- t(pca$rotation)
# 4299 PCs x 4299 metacells for Satija
# 1520 PCs x 1520 metacells for Satija
write.table(data_proj, file=data_out_icell)
write.table(pca$sdev, file=data_out_icell_sdev)
```

