---
title: "fig2"
output:
  pdf_document: default
  html_document: default
---

```{r libs}
library(knn.covertree)
library(pbapply)
library(ggplot2)
```

```{r get data}
dropout_percent <- c(0,5,10,20,30,40,50,75,80,85,90,95)
pca_path <- sapply(dropout_percent, function(y) paste0("/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/simul_pca_readyforhubness",y,".csv"))
simul_pca <- pblapply(pca_path, function(x) read.table(x))
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_simul.R")
hubness <- lapply(hubness, function(x) {x$cellID <- names(hubness_scores_data[[1]][[1]][[1]]); return(x)})
```

```{r functions}
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_functions.R")
get_hub_scores <- function(data,k) {
  knn_graph <- knn.covertree::find_knn(t(data),k)
  knn_list <- knn_graph$index
  occurence <- pbsapply(1:nrow(knn_list), function(x) {sum(knn_list==x)})
  return(occurence)
}
asymmetry_evaluation <- function(data) {
  knn_graph <- knn.covertree::find_knn(t(data),k)
  knn_list <- knn_graph$index
  increment = 0
  for (i in 1:nrow(knn_list)) {
    for (j in 1:ncol(knn_list)) {
      if (i %in% knn_list[knn_list[i,j],]) {
        increment <- increment + 1 
      }
    }
  }
  return(1-increment/(nrow(knn_list)*ncol(knn_list)))
}
skewness <- function(distrib) {
  return(mean((distrib-mean(distrib))^3)/(sd(distrib)^3))
}
antihub <- function(distrib) {
  return(sum(distrib==0))
}
k_thd <- function(distrib,k) {
  return(sum(distrib>=2*k))
} 
meansd_thd <- function(distrib) {
  thd <- mean(distrib) + 3*sd(distrib)
  return(sum(distrib>=thd))
}
generate_gaussian <- function(n,dim) {
  return(t(sapply(1:dim, function(x) rnorm(n))))
}
generate_uniform <- function(n,dim) {
  return(t(sapply(1:dim, function(x) runif(n,min=(-1)))))
}
relative_contrast <- function(data) {
  tmp <- as.matrix(dist(t(data)))
  diag(tmp) <- NA
  rc <- apply(tmp, 1, function(x) abs(max(x, na.rm = T)-min(x, na.rm = T))/min(x, na.rm = T))
  return(mean(rc))
}
extract_r_squared <- function(lm) {
  return(summary(lm)$r.squared)
}
pca_plot <- function(pca_layout) {
  df <- data.frame("PC1"=unname(as.vector(t(pca_layout[1,]))),
                   "PC2"=unname(as.vector(t(pca_layout[2,]))))
  ggplot(df, aes(x=PC1,y=PC2)) + geom_point()
}
pca_plot_labels <- function(pca_layout,clusters) {
  df <- data.frame("PC1"=unname(as.vector(t(pca_layout[1,]))),
                   "PC2"=unname(as.vector(t(pca_layout[2,]))),
                   "Cluster"=factor(clusters))
  ggplot(df, aes(x=PC1,y=PC2,color=Cluster)) + geom_point() + scale_color_viridis_d()
}
umap_plot <- function(umap_layout) {
  df <- data.frame("UMAP1"=unname(as.vector(t(umap_layout[1,]))),
                   "UMAP2"=unname(as.vector(t(umap_layout[2,]))))
  ggplot(df, aes(x=UMAP1,y=UMAP2)) + geom_point()
}
umap_plot_labels <- function(umap_layout,clusters) {
  df <- data.frame("UMAP1"=unname(as.vector(t(umap_layout[1,]))),
                   "UMAP2"=unname(as.vector(t(umap_layout[2,]))),
                   "Cluster"=factor(clusters))
  ggplot(df, aes(x=UMAP1,y=UMAP2,color=Cluster)) + geom_point() + scale_color_viridis_d()
}
kmeans_clustering <- function(data,cluster_nb,pc_nb) {
  clustering <- kmeans(t(data[1:pc_nb,]),cluster_nb)
  kmeans_cluster <- clustering$cluster
  kmeans_center <- t(clustering$centers[,1:2])
  return(list("index"=kmeans_cluster,
              "center"=kmeans_center))
}
compare_dist_to_center <- function(data,clustering,hubs_labels) {
  cluster_nb <- max(clustering$index)
  cluster_hub <- lapply(1:cluster_nb,
                        function(x) data.frame(data[1:2,clustering$index==x & hubs_labels=="Hubs"]))
  cluster_rdm <- lapply(1:cluster_nb,
                        function(x) data[1:2,clustering$index==x & hubs_labels=="Normal"])
#  cluster_rdm <- lapply(1:cluster_nb,
#                        function(x) cluster_rdm[[x]][,sample(1:ncol(cluster_rdm[[x]]),ncol(cluster_hub[[x]]))])
  dist_hub <- lapply(1:cluster_nb,
                     function(x) apply(cluster_hub[[x]],
                                       2,
                                       function(y) dist(t(cbind(y,clustering$center[,x])))))
  dist_rdm <- lapply(1:cluster_nb,
                     function(x) apply(cluster_rdm[[x]],
                                       2,
                                       function(y) dist(t(cbind(y,clustering$center[,x])))))
  df<-data.frame("Distance"=c(unlist(dist_hub),unlist(dist_rdm)),
                 "Cell_type"=c(rep("Hub",length(unlist(dist_hub))),
                               rep("Random",length(unlist(dist_rdm)))),
                 "Cluster"=c(unlist(sapply(1:cluster_nb,
                                  function(x) rep(x,length(dist_hub[[x]])))),
                             unlist(sapply(1:cluster_nb,
                                           function(x) rep(x,length(dist_rdm[[x]]))))))
  return(df)
}
compare_dist_to_random <- function(data,clustering,hubs_labels) {
  cluster_nb <- max(clustering$index)
  cluster_hub <- lapply(1:cluster_nb,
                        function(x) data.frame(data[1:2,clustering$index==x & hubs_labels=="Hubs"]))
  cluster_rdm <- lapply(1:cluster_nb,
                        function(x) data[1:2,clustering$index==x & hubs_labels=="Normal"])
  dist_hub <- lapply(1:cluster_nb,
                     function(x) {rdm <- sample(names(clustering$index)[clustering$index==x],1); rdm <- data[1:2,rdm]; apply(cluster_hub[[x]],
                     2,
                     function(y) dist(t(cbind(y,rdm))))})
  dist_rdm <- lapply(1:cluster_nb,
                     function(x) {rdm <- sample(names(clustering$index)[clustering$index==x],1); rdm <- data[1:2,rdm]; apply(cluster_rdm[[x]],
                     2,
                     function(y) dist(t(cbind(y,rdm))))})
  df<-data.frame("Distance"=c(unlist(dist_hub),unlist(dist_rdm)),
                 "Cell_type"=c(rep("Hub",length(unlist(dist_hub))),
                               rep("Random",length(unlist(dist_rdm)))),
                 "Cluster"=c(unlist(sapply(1:cluster_nb,
                                  function(x) rep(x,length(dist_hub[[x]])))),
                             unlist(sapply(1:cluster_nb,
                                           function(x) rep(x,length(dist_rdm[[x]]))))))
  return(df)
}
```

```{r get neighbors}
k_max=100
neighbors <- pblapply(simul_pca, function(x) findKNN(t(x), k_max))
neighbor_list <- pblapply(neighbors, function(x) return(x$index))
neighbor_list <- pblapply(neighbor_list, function(x) {rownames(x) <- names(hubness_scores_data[[1]][[1]][[1]]);return(x)})
```

```{r get hubs}
k=100
hub_scores <- pblapply(hubness,
                       function(x) x$score[x$Dimension==(cell_nb-1) & x$p==2 & x$k==k])
hub_scores <- lapply(hub_scores,
                     function(x) {names(x) <- names(hubness_scores_data[[1]][[1]][[1]]);return(x)})
h1<-pbsapply(1:length(neighbor_list),
             function(x) reverse_coverage_k(neighbor_list[[x]], hub_scores[[x]], k_max, 2, cell_nb))
```

```{r viz}
library(umap)
hubs <- order(hub_scores[[1]], decreasing = T)[1:h1[[1]]]
hubs_labels <- rep("Normal",cell_nb)
hubs_labels[hubs] <- "Hubs"
umap <- pblapply(simul_pca, function(x) t(umap(t(x[1:50,]))$layout))
pca_plot(simul_pca[[1]])
umap_plot(umap[[1]])
pca_plot_labels(simul_pca[[1]],hubs_labels)
umap_plot_labels(umap[[1]],hubs_labels)
```

```{r clustering}
k_val <- c(2,5,10,sum(hubs_labels=="Hubs"))
clustering <- lapply(k_val,
                     function(x) kmeans_clustering(simul_pca[[2]],x,3))
distance <- lapply(clustering,
                   function(z) compare_dist_to_center(simul_pca[[1]],z,hubs_labels))
distance_rdm <- lapply(clustering,
                       function(z) {tot<-sapply(1:20,
                                          function(y) {tmp<-compare_dist_to_random(simul_pca[[1]],z,hubs_labels)$Distance; return(tmp)}); df <- compare_dist_to_random(simul_pca[[1]],z,hubs_labels); df$Distance <- rowMeans(tot); return(df)})
k_value <- 4
df <- distance[[k_value]]
df_rdm <- distance_rdm[[k_value]]
df$Distance_to <- "Center"
df_rdm$Distance_to <- "Random"
df_tot <- rbind(df,df_rdm)
colnames(df_tot)[colnames(df_tot)=="Cell_type"] <- "Distance_from"
cluster_index <- clustering[[k_value]]$index

pca_plot_labels(simul_pca[[1]],cluster_index)
umap_plot_labels(umap[[1]],cluster_index)

ggplot(df, aes(Distance)) + geom_density(aes(group=Cell_type,fill=Cell_type), alpha=0.5)
#ggplot(df_rdm, aes(Distance)) + geom_density(aes(group=Cell_type,fill=Cell_type), alpha=0.5)
#ggplot(df, aes(x=Cell_type,y=Distance,fill=Cell_type)) + geom_violin(scale = "area") + scale_fill_viridis_d()
ggplot(df_tot, aes(x=Distance_to,y=Distance,fill=Distance_from)) + geom_boxplot() + scale_fill_viridis_d()
```

```{r evaluate density and link with hubness}

```

```{r check node degree}
hub_scores <- pblapply(hubness,
                       function(x) x$score[x$Dimension==100 & x$p==2 & x$k==k])
hub_scores <- lapply(hub_scores,
                     function(x) {names(x) <- names(hubness_scores_data[[1]][[1]][[1]]);return(x)})
df=data.frame("Degree"=hub_scores[[1]])
ggplot(df, aes(Degree)) + geom_density() + scale_y_log10() + scale_x_log10()
hist(df$Degree)
```

