---
title: "fig2"
output: html_document
---

```{r libs}
library(knn.covertree)
library(pbapply)
library(ggplot2)
library(circlize)
library(ComplexHeatmap)
library(ggpubr)
```

```{r functions}
dist_heatmap <- function(dist) {
  col_fun = colorRamp2(c(0,0.5,1),heat.colors(n=3))
  Heatmap(as.matrix(dist), cluster_rows = T, cluster_columns = T, col = col_fun,
        border = T, show_column_names = F, show_row_names = F, name = "Euclidean distance")
}
get_hub_scores <- function(data,k) {
  knn_graph <- knn.covertree::find_knn(t(data),k)
  knn_list <- knn_graph$index
  occurence <- pbsapply(1:nrow(knn_list), function(x) {sum(knn_list==x)})
  return(occurence)
}
asymmetry_evaluation <- function(data) {
  knn_graph <- knn.covertree::find_knn(t(data),k)
  knn_list <- knn_graph$index
  increment = 0
  for (i in 1:nrow(knn_list)) {
    for (j in 1:ncol(knn_list)) {
      if (i %in% knn_list[knn_list[i,j],]) {
        increment <- increment + 1 
      }
    }
  }
  return(1-increment/(nrow(knn_list)*ncol(knn_list)))
}
skewness <- function(distrib) {
  return(mean((distrib-mean(distrib))^3)/(sd(distrib)^3))
}
antihub <- function(distrib) {
  return(sum(distrib==0))
}
k_thd <- function(distrib,k) {
  return(sum(distrib>=2*k))
} 
meansd_thd <- function(distrib) {
  thd <- mean(distrib) + 3*sd(distrib)
  return(sum(distrib>=thd))
}
generate_gaussian <- function(n,dim) {
  return(t(sapply(1:dim, function(x) rnorm(n))))
}
generate_uniform <- function(n,dim) {
  return(t(sapply(1:dim, function(x) runif(n,min=(-1)))))
}
relative_contrast <- function(dist) {
  tmp <- as.matrix(dist)
  diag(tmp) <- NA
  rc <- apply(tmp, 1, function(x) abs(max(x, na.rm = T)-min(x, na.rm = T))/min(x, na.rm = T))
  return(mean(rc))
}
relative_contrast2 <- function(data) {
  tmp <- as.matrix(dist(t(data)))
  diag(tmp) <- NA
  rc <- apply(tmp, 1, function(x) abs(max(x, na.rm = T)-min(x, na.rm = T))/min(x, na.rm = T))
  return(mean(rc))
}
```

```{r create distributions}
N = 1000
tested_dim = c(5,10,20,30,40,50,100,200,300,400,500,600,700,800,900,1000)
distrib_gaussian <- lapply(tested_dim, function(x) generate_gaussian(N,x))
distrib_uniform <- lapply(tested_dim, function(x) generate_uniform(N,x))
```

```{r get hub scores}
k=50
scores_gaussian <- pblapply(distrib_gaussian, function(x) get_hub_scores(x,k))
scores_uniform <- pblapply(distrib_uniform, function(x) get_hub_scores(x,k))
```

```{r look at the distrib}
lapply(scores_gaussian, hist)
lapply(scores_uniform, hist)
```

```{r distance concentration}
pairwise_dist <- pblapply(c(distrib_gaussian,distrib_uniform), function(x) dist(t(x)))
pairwise_dist_norm <- pblapply(pairwise_dist, function(x) x/max(x))
pblapply(pairwise_dist_norm, dist_heatmap)
# look at relative contrast
rc <- pbsapply(pairwise_dist_norm, relative_contrast)
n_cell <- nrow(rc)
rc <- data.frame("Relative_contrast"=as.vector(rc),
                 "Data"=rep(c("Gaussian","Uniform"),each=length(tested_dim)),
                 "Dimension"=tested_dim)

ggplot(rc, aes(x=Dimension, y=Relative_contrast)) +
  geom_point() +
  geom_line(aes(group=Data, color=Data), alpha=0.5)
```

```{r look at the parameters as a function of dim}
Skewness <- data.frame("Skewness"=c(pbsapply(scores_gaussian, function(x) skewness(x)),
                                    pbsapply(scores_uniform, function(x) skewness(x))),
                       "Distribution"=rep(c("Normal","Uniform"), each=length(tested_dim)),
                       "Dimension"=tested_dim)
ggplot(Skewness, aes(x=Dimension, y=Skewness)) +
  geom_line(aes(group=Distribution)) +
  geom_point(aes(color=Distribution))
Antihub <- data.frame("Antihub"=c(pbsapply(scores_gaussian, function(x) antihub(x)),
                                  pbsapply(scores_uniform, function(x) antihub(x))),
                      "Distribution"=rep(c("Normal","Uniform"), each=length(tested_dim)),
                      "Dimension"=tested_dim)
ggplot(Antihub, aes(x=Dimension, y=Antihub)) +
  geom_line(aes(group=Distribution)) +
  geom_point(aes(color=Distribution))
KThd <- data.frame("KThd"=c(pbsapply(scores_gaussian, function(x) k_thd(x,k)),
                            pbsapply(scores_uniform, function(x) k_thd(x,k))),
                   "Distribution"=rep(c("Normal","Uniform"), each=length(tested_dim)),
                   "Dimension"=tested_dim)
ggplot(KThd, aes(x=Dimension, y=KThd)) +
  geom_line(aes(group=Distribution)) +
  geom_point(aes(color=Distribution))
MeanSdThd <- data.frame("MeanSdThd"=c(pbsapply(scores_gaussian, function(x) meansd_thd(x)),
                                      pbsapply(scores_uniform, function(x) meansd_thd(x))),
                        "Distribution"=rep(c("Normal","Uniform"), each=length(tested_dim)),
                        "Dimension"=tested_dim)
ggplot(MeanSdThd, aes(x=Dimension, y=MeanSdThd)) +
  geom_line(aes(group=Distribution)) +
  geom_point(aes(color=Distribution))
Asymmetry <- data.frame("Asymmetry"=c(pbsapply(distrib_gaussian, asymmetry_evaluation),
                                      pbsapply(distrib_uniform, asymmetry_evaluation)),
                        "Distribution"=rep(c("Normal","Uniform"), each=length(tested_dim)),
                        "Dimension"=tested_dim)
ggplot(Asymmetry, aes(x=Dimension, y=Asymmetry)) +
  geom_line(aes(group=Distribution)) +
  geom_point(aes(color=Distribution))
```

```{r link to distance concentration}
rc_gaussian <- pbsapply(distrib_gaussian, relative_contrast2)
rc_uniform <- pbsapply(distrib_uniform, relative_contrast2)
link_df <- data.frame("Relative_contrast"=c(rc_gaussian,rc_uniform),
                      "Asymmetry"=Asymmetry$Asymmetry,
                      "Antihub"=Antihub$Antihub,
                      "KThd"=KThd$KThd,
                      "MeanSdThd"=MeanSdThd$MeanSdThd,
                      "Skewness"=Skewness$Skewness,
                      "Dimension"=tested_dim,
                      "Distribution"=rep(c("Normal","Uniform"), each=length(tested_dim)))

lm_gauss <- lm(Skewness ~ log(Relative_contrast), data=link_df[link_df$Distribution=="Normal",])
lm_unif <- lm(Skewness ~ log(Relative_contrast), data=link_df[link_df$Distribution=="Uniform",])
summary(lm_gauss)
summary(lm_unif)
ggplot(link_df, aes(x=log(Relative_contrast), y=Skewness, color=Distribution)) +
  geom_point() +
  geom_abline(slope = lm_gauss$coefficients[2], intercept = lm_gauss$coefficients[1], color="red") +
  geom_abline(slope = lm_unif$coefficients[2], intercept = lm_unif$coefficients[1], color="blue")
# Do pearson and spearman also
lm_gauss <- lm(Asymmetry ~ log(Relative_contrast), data=link_df[link_df$Distribution=="Normal",])
lm_unif <- lm(Asymmetry ~ log(Relative_contrast), data=link_df[link_df$Distribution=="Uniform",])
summary(lm_gauss)
summary(lm_unif)
ggplot(link_df, aes(x=log(Relative_contrast), y=Asymmetry, color=Distribution)) +
  geom_point() +
  geom_abline(slope = lm_gauss$coefficients[2], intercept = lm_gauss$coefficients[1], color="red") +
  geom_abline(slope = lm_unif$coefficients[2], intercept = lm_unif$coefficients[1], color="blue")

lm_gauss <- lm(KThd ~ log(Relative_contrast), data=link_df[link_df$Distribution=="Normal",])
lm_unif <- lm(KThd ~ log(Relative_contrast), data=link_df[link_df$Distribution=="Uniform",])
summary(lm_gauss)
summary(lm_unif)
ggplot(link_df, aes(x=log(Relative_contrast), y=KThd, color=Distribution)) +
  geom_point() +
  geom_abline(slope = lm_gauss$coefficients[2], intercept = lm_gauss$coefficients[1], color="red") +
  geom_abline(slope = lm_unif$coefficients[2], intercept = lm_unif$coefficients[1], color="blue")

lm_gauss <- lm(MeanSdThd ~ log(Relative_contrast), data=link_df[link_df$Distribution=="Normal",])
lm_unif <- lm(MeanSdThd ~ log(Relative_contrast), data=link_df[link_df$Distribution=="Uniform",])
summary(lm_gauss)
summary(lm_unif)
ggplot(link_df, aes(x=log(Relative_contrast), y=MeanSdThd, color=Distribution)) +
  geom_point() +
  geom_abline(slope = lm_gauss$coefficients[2], intercept = lm_gauss$coefficients[1], color="red") +
  geom_abline(slope = lm_unif$coefficients[2], intercept = lm_unif$coefficients[1], color="blue")

p1=ggplot(link_df, aes(x=Asymmetry, y=Skewness, color=Distribution, alpha=Dimension)) +
  geom_point()
p2=ggplot(link_df, aes(x=Asymmetry, y=Antihub, color=Distribution, alpha=Dimension)) +
  geom_point() 
p3=ggplot(link_df, aes(x=Asymmetry, y=KThd, color=Distribution, alpha=Dimension)) +
  geom_point() 
p4=ggplot(link_df, aes(x=Asymmetry, y=MeanSdThd, color=Distribution, alpha=Dimension)) +
  geom_point() 
ggarrange(p1,p2,p3,p4)
```

