---
title: "Sparsity X genes number"
output: html_document
---

```{r load data, include = FALSE}
library(pbapply)
library(ggplot2)
datasets = c("Baron","Darmanis","Guo","PDX1","Satija","Silver","Zheng4","Zheng8","BRCA")
path_before <- c("/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Luis/sce_Baron.rds",
                 "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Luis/sce_full_Darmanis.rds",
                 "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Guo_lung_2018/GSE99254_NSCLC.TCell.S9055.count.labeled.txt",
                 "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/10x/GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv",
                 "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Luis/sce_full_GSE115189Silver.rds",
                 "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Luis/sce_full_Zhengmix4eq.rds",
                 "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Luis/sce_full_Zhengmix8eq.rds",
                 "/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/Raw_data_TCGA-BRCA.RData")
counts <- pblapply(datasets,
                       function(x) {
                          source(file=paste0("/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_",x,".R"));
                                 return(data)})
load_rds <- function(path) {
  data <- readRDS(path)
  return(data@assays$data$counts)
}
load_rdata <- function(path) {
  load(path)
  rownames(data) <- data[,1]
  return(data[,-1])
}
Baron <- load_rds(path_before[1])
Darmanis <- load_rds(path_before[2])
Guo <- read.table(path_before[3])
Satija <- read.csv(path_before[4], header = T, row.names = 1)
Satija <- Satija[grep("HUMAN_",rownames(Satija)),]
rownames(Satija) <- gsub("HUMAN_","",rownames(Satija))
Silver <- load_rds(path_before[5])
Zheng4 <- load_rds(path_before[6])
Zheng8 <- load_rds(path_before[7])
BRCA <- load_rdata(path_before[8])
counts_tot <- list(Baron,Darmanis,Guo,Satija,Silver,Zheng4,Zheng8,BRCA)
names(counts_tot) <- c("Baron","Darmanis","Guo","Satija","Silver","Zheng4","Zheng8","BRCA")
```

```{r plot}
sparsity <- pbsapply(counts, function(x) sum(x==0)/ncol(x)/nrow(x)*100)
sparsity_tot <- pbsapply(counts_tot, function(x) sum(x==0)/ncol(x)/nrow(x)*100)
gene_nb <- pbsapply(counts, function(x) nrow(x))
gene_nb_tot <- pbsapply(counts_tot, function(x) nrow(x))
df <- data.frame("Dataset"=c(datasets,names(counts_tot)),
                 "Sparsity"=c(sparsity,sparsity_tot),
                 "Gene_nb"=c(gene_nb,gene_nb_tot),
                 "Filter"=c(rep("yes",length(counts)),rep("no",length(counts_tot))))
ggplot(df, aes(x=Gene_nb, y=Sparsity, color=Dataset)) +
  geom_point(aes(shape=Filter)) +
  geom_line(aes(group=Dataset), lty=2) +
  xlab("Number of genes") +
  ylab("Sparsity (%)")
```

