---
title: "Reverse coverage-based hub definition -Guo"
output: html_document
---

```{r load data, include = FALSE}
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_Guo.R")
hubness$cellID <- names(hubness_scores_data[[1]][[1]])

source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_Guo.R")

source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_functions.R")
path_neighbors <- "/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hub_network/neighbors_Guo.rds"
path_neighbors_pca <- "/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hub_network/neighbors_pca_Guo.rds"
path_hub <- "/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hubness_def/rev_cov/hubs_Guo.rds"
```

```{r get hub scores, include=FALSE}
hub_scores <- hubness$score[hubness$Dimension==(cell_nb-1) & hubness$p==2 & hubness$k==50]
names(hub_scores) <- names(hubness_scores_data[[1]][[1]])
```

```{r get neighbors}
k_max=100
d=100
#neighbors <- findKNN(t(data), k_max)
#saveRDS(neighbors,file=path_neighbors)
#neighbors_pca <- findKNN(t(data_pca[1:50,]), k_max)
#saveRDS(neighbors_pca,file=path_neighbors_pca)
neighbors <- readRDS(path_neighbors)
neighbors_pca <- readRDS(path_neighbors_pca)
neighbor_list <- neighbors$index
neighbor_pca_list <- neighbors_pca$index
rownames(neighbor_list) <- names(hubness_scores_data[[1]][[1]])
rownames(neighbor_pca_list) <- names(hubness_scores_data[[1]][[1]])
```

```{r reverse get all the data fixing the neighborhood size but increasing the nb of hubs}
k=100
h1<-reverse_coverage_k(neighbor_list, hub_scores, k, 2)
h2<-reverse_coverage_k(neighbor_pca_list, hub_scores, k, 2)
```

```{r extract the indexes of hubs}
h1==h2
print(paste0("We have selected ",h1," hubs"))
hubs <- names(sort(hub_scores, decreasing = T)[1:h1])
saveRDS(hubs, file=path_hub)
```

```{r measure stemID entropy, include = FALSE}
sc <- SCseq(data)
sc@ndata <- data
ltr <- Ltree(sc)
ltr <- compentropy(ltr)
stemID <- ltr@entropy
rm(sc,ltr)
```

```{r prep Seurat, include = FALSE}
seurat <- CreateSeuratObject(data)
seurat$hub <- c("normal","hub")[factor(colnames(seurat) %in% hubs, levels = c("FALSE","TRUE"))]
seurat$scentropy <- entropy
seurat$stemID <- stemID
seurat$dropout <- apply(data, 2, function(x) {sum(x==0)/length(x)})
rm(entropy,stemID)
rb_gene <- c("^RPS","^RPL","^MRPS","^MRPL")
seurat[["percent.rb"]] <- PercentageFeatureSet(seurat,
                                               features = unlist(lapply(rb_gene, function(x) {
                                                 grep(x,rownames(seurat),value=T)})))
seurat[["percent.mt"]] <- PercentageFeatureSet(seurat, pattern = "^MT-")
VlnPlot(seurat, features = c("nFeature_RNA","nCount_RNA","percent.mt"))
# Normalize + log transfo + scale
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat)
seurat <- FindVariableFeatures(seurat)
seurat <- RunPCA(seurat, verbose = F)
seurat <- RunUMAP(seurat, dims = 1:50)
seurat <- RunTSNE(seurat, dims = 1:50)
```

```{r visualise the hubs}
k = 100
DimPlot(seurat, group.by = "hub", reduction = "umap", pt.size = 1.5, order="hub")
```

```{r QC metrics}
# nFeature/nCount
ggarrange(FeaturePlot(seurat,"nFeature_RNA"),
          FeaturePlot(seurat,"nCount_RNA"))
ggarrange(vlnplot_hub_spec_connect(seurat,"nFeature_RNA","hub",0,4000,3900),
          vlnplot_hub_spec_connect(seurat, "nCount_RNA", "hub",0,12000,11000))
ggarrange(histoplot_hub_spec(seurat, seurat$nFeature_RNA, "nFeature", seurat$hub),
          histoplot_hub_spec(seurat, seurat$nCount_RNA, "nCount", seurat$hub))
# Dropout rate
FeaturePlot(seurat,"dropout")
vlnplot_hub_spec_connect(seurat,"dropout","hub",0.7,1.05,1.02)
histoplot_hub_spec(seurat, seurat$dropout, "dropout", seurat$hub)
# Percentage of mito/ribo
ggarrange(FeaturePlot(seurat,"percent.mt"),
          FeaturePlot(seurat,"percent.rb"))
ggarrange(vlnplot_hub_spec_connect(seurat, "percent.mt", "hub",0,30,25),
          vlnplot_hub_spec_connect(seurat, "percent.rb", "hub",0,55,52))
ggarrange(histoplot_hub_spec(seurat, seurat$percent.mt, "percent.mt", seurat$hub),
          histoplot_hub_spec(seurat, seurat$percent.rb, "percent.rb", seurat$hub))
```

```{r entropy}
# scEntropy 
FeaturePlot(seurat, reduction = "umap", features = "scentropy")
vlnplot_hub_spec(seurat, "scentropy", "hub",2.6,3.6,3.5)
histoplot_hub_spec(seurat, seurat$scentropy, "scentropy", seurat$hub)
# stemID
FeaturePlot(seurat, reduction = "umap", features = "stemID")
vlnplot_hub_spec(seurat, "stemID", "hub",0.2,0.8,0.78)
histoplot_hub_spec(seurat, seurat$stemID, "stemID", seurat$hub)
```

