---
title: "Do we have hubs?"
output:
  html_document: default
  pdf_document: default
---

```{r libs, results="hide", include = FALSE}
library(ggplot2, quietly = T)
library(viridis, quietly = T)
library(ggridges, quietly = T)
library(scales, quietly = T)
library(ggpubr, quietly = T)
library(pbapply)
library(knn.covertree)
```

```{r functions, include = FALSE}
data_load <- function(path) {
   source(file=path)
   return(hubness)
}
dataset <- c("Koh","KohTCC","Kumar","KumarTCC","SimKumar4easy","SimKumar4hard","SimKumar8hard","Trapnell","TrapnellTCC", "Zhengmix4eq", "Zhengmix4uneq","Zhengmix8eq")
data_hubness <- data_load("/Users/elise/Desktop/Github/Hubness_sc/Figure1_sc/hubness_load_write_data_duo_scaled.R")
data_pca <- pblapply(dataset,
                     function(x)read.table(paste0(
                        "/Users/elise/Desktop/GitHub/Hubness_sc/Figure1_sc/pca_scaled/",
                                                   x,"_pca_readyforhubness.csv")))
data_sdev <- pblapply(dataset,
                     function(x)read.table(paste0(
                        "/Users/elise/Desktop/GitHub/Hubness_sc/Figure1_sc/pca_scaled/sdev_",
                                                   x,".csv")))

get_hub1 <- function(df,kval,pcval) { # Maximum hubness score
   max = c()
   ymin = c()
   ymax = c()
   y_increment = 1
   for (d in pcval) {
      for (k in kval) {
         val = df$score[df$Dimension==d & df$k==k]
         max = c(max, max(val))
         ymin = c(ymin,y_increment)
         ymax = c(ymax,y_increment+1)
      }
     y_increment <- y_increment+1
   }
   hub_val <- data.frame("k"=rep(kval,times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)),
                         "GHubness"=max,
                         "ymin"=ymin,
                         "ymax"=ymax)
   return(hub_val)
}
get_hub2 <- function(df,kval,pcval) { # Using the mean + 3*sd from Tomasev
   x_thd = c()
   hub_nb = c()
   ymin = c()
   ymax = c()
   y_increment = 1
   for (d in pcval) {
      for (k in kval) {
         val = df$score[df$Dimension==d & df$k==k]
         x_thd = c(x_thd, mean(val)+3*sd(val))
         hub_nb = c(hub_nb, sum(val>=(mean(val)+3*sd(val))))
         ymin = c(ymin,y_increment)
         ymax = c(ymax,y_increment+1)
      }
     y_increment <- y_increment+1
   }
   hub_val <- data.frame("k"=rep(kval,times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)),
                         "GHubness"=hub_nb,
                         "Threshold"=x_thd,
                         "ymin"=ymin,
                         "ymax"=ymax)
   return(hub_val)
}
get_hub3 <- function(df,kval,pcval,log=F) { # Using the method from [1] >= 2k
   if (log==T) {
      hub_nb = c()
      ymin = c()
      ymax = c()
      y_increment = 1
      for (d in pcval) {
         for (k in kval) {
               val = df$score[df$Dimension==d & df$k==k]
               hub_nb = c(hub_nb, sum(val>=2*log(k)))
               ymin = c(ymin,y_increment)
               ymax = c(ymax,y_increment+1)
         }
      y_increment <- y_increment+1
      }
   }
   else {
      hub_nb = c()
      ymin = c()
      ymax = c()
      y_increment = 1
      for (d in pcval) {
         for (k in kval) {
               val = df$score[df$Dimension==d & df$k==k]
               hub_nb = c(hub_nb, sum(val>=2*k))
               ymin = c(ymin,y_increment)
               ymax = c(ymax,y_increment+1)
         }
      y_increment <- y_increment+1
      }
   }
   hub_val <- data.frame("k"=rep(kval,times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)),
                         "GHubness"=hub_nb,
                         "ymin"=ymin,
                         "ymax"=ymax)
   hub_val$Threshold <- 2*hub_val$k
   return(hub_val)
}
get_hub4 <- function(df,kval,pcval) { # skewness
   s = c()
   for (d in pcval) {
      for (k in kval) {
            val = df$score[df$Dimension==d & df$k==k]
            s = c(s, mean((val-mean(val))^3)/sd(val)^3)
      }
   }
   skewness_val <- data.frame("k"=rep(kval,times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)),
                         "GHubness"=s)
   skewness_val$Dimension <- factor(skewness_val$Dimension, levels = pcval)
   return(skewness_val)
}
get_hub6 <- function(df,kval,pcval) { # anti hubs
   anti_hub = c()
   for (d in pcval) {
      for (k in kval) {
           anti_hub = c(anti_hub,unique(df$Antihubs[df$Dimension==d & df$k==k]))
      }
   }
   hub_val <- data.frame("k"=rep(kval,times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)),
                         "GHubness"=anti_hub)
   hub_val$Dimension <- factor(hub_val$Dimension, levels = pcval)
   return(hub_val)
}
fn_zarb <- function(knn_list) {
   increment = 0
   for (i in 1:nrow(knn_list)) {
      for (j in 1:ncol(knn_list)) {
         if (i %in% knn_list[knn_list[i,j],]) {
            increment <- increment + 1 
      }
    }
   }
   return(100*(1-increment/(nrow(knn_list)*ncol(knn_list))))
}
get_hub7 <- function(data,kval,pcval) { #asymmetry
  knn_list <- lapply(pcval,
                      function(x) lapply(kval,
                                         function(y) knn.covertree::find_knn(t(data[1:x,]),y)$index))
  result <- lapply(knn_list,
                   function(x) sapply(x,
                                      function(y) fn_zarb(y)))
  asy_val <- data.frame("k"=rep(kval, times=length(pcval)),
                        "Dimension"=rep(pcval,each=length(kval)),
                        "GHubness"=unlist(result))
   asy_val$Dimension <- factor(asy_val$Dimension, levels = pcval)
  return(asy_val)
}
make_merge <- function(hubness,data,kval,pcval,name,size) {
#hub_max <- get_hub1(hubness, kval=kval,pcval=pcval)
#hub_mean <- get_hub2(hubness, kval=kval,pcval=pcval)
hub_k <- get_hub3(hubness, kval=kval,pcval=pcval)
hub_skew <- get_hub4(hubness, kval=kval,pcval=pcval)
hub_anti <- get_hub6(hubness, kval=kval,pcval=pcval)
hub_asym <- get_hub7(data, kval=kval,pcval=pcval)
hub_k <- hub_k[,colnames(hub_skew)]
#hub_mean <- hub_mean[,colnames(hub_skew)]
#hub_max <- hub_max[,colnames(hub_skew)]
hub_k$GHubness <- hub_k$GHubness*100/size
#hub_mean$GHubness <- hub_mean$GHubness*100/size
hub_anti$GHubness <- hub_anti$GHubness*100/size
#hub_max$GHubness <- hub_max$GHubness/size
#hub_max$Method <- "Max"
#hub_mean$Method <- "Mean+Sd"
hub_k$Method <- "2k"
hub_skew$Method <- "Skewness"
hub_anti$Method <- "Antihubs"
hub_asym$Method <- "Asymmetry"
hub <- rbind(hub_skew,hub_k,hub_asym,hub_anti)
hub$Dataset <- name
return(hub)
}
```

```{r fig1}
# Merge the dfs
pcval=lapply(dim_nb,
               function(x) return(c(2,5,10,20,30,40,50,100,200,x-1)))
pcval2=lapply(dim_nb,
               function(x) return(c(2,5,10,20,30,40,50,100,200)))
df <- do.call(rbind,pblapply(seq(n_dataset),
             function(x) make_merge(data_hubness[[x]],data_pca[[x]],10,pcval[[x]],dataset[x],dim_nb[x])))
df2 <- do.call(rbind,pblapply(seq(n_dataset),
             function(x) make_merge(data_hubness[[x]],data_pca[[x]],10,pcval2[[x]],dataset[x],dim_nb[x])))
df$Dimension <- as.numeric(as.character(df$Dimension))
df2$Dimension <- as.numeric(as.character(df2$Dimension))

# Viz
labz_method = c("2k (% of hubs)", "Antihubs (% of hubs)", "Asymmetry (% of edges)", "Skewness")
names(labz_method) <- c("2k","Antihubs","Asymmetry","Skewness")
ggplot(df, aes(x=Dimension, y=GHubness)) + geom_line(aes(group=Dataset, color=Dataset)) + geom_point(size=0.1) + facet_wrap(~Method, scales = "free") + ylab(NULL)
ggplot(df2, aes(x=Dimension, y=GHubness)) +
   geom_line(aes(group=Dataset, color=Dataset)) +
   geom_point(size=0.1) +
   facet_wrap(~Method, scales = "free", labeller = labeller(Method = labz_method), nrow=1) +
   ylab(NULL) +
   scale_color_viridis_d(option = "plasma") +
   theme(panel.background = element_rect(fill="grey98"),
         panel.grid = element_line(colour = "grey80"))

saveRDS(df2,
        file="/Users/elise/Desktop/Github/Hubness_sc/Figure1_sc/hubness_param_ggplot1_scaled.rds")
```

```{r fig1 supp}
make_merge_supp <- function(hubness,data,kval,pcval,name,size) {
hub_max <- get_hub1(hubness, kval=kval,pcval=pcval)
hub_mean <- get_hub2(hubness, kval=kval,pcval=pcval)
hub_skew <- get_hub4(hubness, kval=kval,pcval=pcval)
hub_mean <- hub_mean[,colnames(hub_skew)]
hub_max <- hub_max[,colnames(hub_skew)]
hub_mean$GHubness <- hub_mean$GHubness*100/size
hub_max$GHubness <- hub_max$GHubness/size
hub_max$Method <- "Max"
hub_mean$Method <- "Mean+Sd"
hub <- rbind(hub_max,hub_mean)
hub$Dataset <- name
return(hub)
}
df2_supp <- do.call(rbind,pblapply(seq(n_dataset),
             function(x) make_merge_supp(data_hubness[[x]],data_pca[[x]],10,pcval2[[x]],dataset[x],dim_nb[x])))
df2_supp$Dimension <- as.numeric(as.character(df2_supp$Dimension))

# Viz
labz_method_supp = c("Mean (% of hubs)", "Maximum hub score")
names(labz_method_supp) <- c("Mean+Sd","Max")
ggplot(df2_supp, aes(x=Dimension, y=GHubness)) +
   geom_line(aes(group=Dataset, color=Dataset)) +
   geom_point(size=0.1) +
   facet_wrap(~Method, scales = "free", labeller = labeller(Method = labz_method_supp)) +
   ylab(NULL) +
   scale_color_viridis_d(option = "plasma") +
   theme(panel.background = element_rect(fill="grey98"),
         panel.grid = element_line(colour = "grey80"))

saveRDS(df2_supp,
        file="/Users/elise/Desktop/Github/Hubness_sc/Figure1_sc/hubness_param_ggplot2_scaled.rds")
```

```{r interplay with dropout and ID}
# estimate ID of each dataset
# Screeplot
sdev <- data.frame("Sdev_"=unlist(lapply(data_sdev, function(x)
   unlist(x)/unlist(x)[1])),
   "Dataset"=unname(unlist(mapply(x=dataset, y=data_sdev, function(x,y)
      rep(x, nrow(y)), SIMPLIFY = T))),
   "PC"=unlist(sapply(data_sdev, function(x)
      seq(nrow(x)))))
ggplot(sdev[sdev$PC<30,], aes(x=PC, y=Sdev_, color=Dataset)) +
   geom_point() +
   geom_line(aes(group=Dataset)) +
   geom_hline(yintercept=0.1) +
   scale_color_viridis_d(option="plasma") +
   ylab("Sd/Sd1") +
   xlab("Principal Components")

linear_dim_df <- data.frame("GID_pca"=unlist(lapply(data_sdev, function(x)  return(which(unlist(x)<=unlist(x)[1]/10)[1]))),
                         "Dataset"=dataset)
ggplot(linear_dim_df, aes(x=Dataset, y=GID_pca, color=Dataset)) +
  scale_color_viridis_d(option="plasma") +
  geom_point() +
  ylab("Intrinsic Dimension")

# Get dropout
data_in <- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/DimRedPaper/DuoClustering2018/sce_full/sce_full_"
data_counts <- pblapply(dataset,
                 function(x) {tmp <- readRDS(paste0(data_in,x,".rds"));
                 tmp <- tmp@assays$data@listData$counts;
                 hvg <- names(sort(apply(tmp,1,var),
                                   decreasing = T)[1:min(1e4,nrow(tmp))]);
                 tmp <- tmp[hvg,]
                 return(tmp)})
linear_dim_df$Dropout <- sapply(data_counts, function(x)
   mean(x==0)*100)

# ID x Dropout
ggplot(linear_dim_df[-grep("TCC",linear_dim_df$Dataset),], aes(x=Dropout, y=GID_pca, color=Dataset)) +
  scale_color_viridis_d(option="plasma") +
  geom_point() +
  ylab("Intrinsic Dimension")

# Dropout x Hubness
k=10
Dimension=50
hubness_dropout <- mapply(x=data_hubness, y=data_counts, function(x,y)
   data.frame("Hubness"= x$score[x$Dimension==Dimension & x$k==k],
              "Dropout"=apply(y,2,function(z) mean(z==0)*100)), SIMPLIFY = F)
mapply(x=hubness_dropout, y=dataset, function(x,y)
   ggplot(x, aes(x=Dropout, y=Hubness, color=Hubness)) +
      geom_point() +
      scale_color_viridis(option="plasma") +
      scale_y_log10() +
      scale_x_log10() +
      ggtitle(y), SIMPLIFY = F)
```

