---
title: "PCA obj"
output: html_document
---

```{r libs & paths}
library(Seurat)
library(ggplot2)
library(dplyr)
library(pbapply)
data_in<- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/DimRedPaper/DuoClustering2018/sce_filteredHVG10/sce_filteredHVG10_"
dataset <- c("Koh","KohTCC","Kumar","KumarTCC","SimKumar4easy","SimKumar4hard","SimKumar8hard","Trapnell","TrapnellTCC","Zhengmix4eq","Zhengmix4uneq","Zhengmix8eq")
data_out <- "/Users/elise/Desktop/GitHub/Hubness_sc/duo/pca/"
sdev_out <- "/Users/elise/Desktop/GitHub/Hubness_sc/duo/pca/sdev_"
```

```{r functions}
filter <- function(df) {
  feature <- apply(df,2,function(x) sum(x!=0, na.rm = T))
  count <- apply(df,2,function(x) sum(x, na.rm=T))
  print(plot(feature,count))
}
data_prep <- function(data) {
  data <- log10(data+1)
  return(data)
}
```

```{r do PCA}
data <- pblapply(dataset,
                 function(x) readRDS(paste0(data_in,x,".rds")))
data <- pblapply(data,
                 function(x) return(x@assays$data@listData$counts))
pblapply(data,filter)
pbsapply(data,dim)
# Remove datasets with more cells than genes (10 to 12)
data <- data[1:9]
# Keep 10k HVG
data <- pblapply(data, function(x) {hvg <- names(sort(apply(x,1,var), decreasing = T)[1:min(1e4,nrow(x))]); return(x[hvg,])})
pblapply(1:length(data),
         function(x) write.table(data[[x]], file=paste0(data_out,dataset[x],".csv")))
# Log transfo
data <- pblapply(data, function(x) data_prep(x))
# PCA
pca <- pblapply(data, function(x) prcomp(x, center=T, scale.=F))
data_proj <- pblapply(pca, function(x) t(x$rotation))

pblapply(1:length(data_proj),
         function(x) write.table(data_proj[[x]], file=paste0(data_out,dataset[x],"_pca_readyforhubness.csv")))
pblapply(1:length(data_proj),
          function(x) write.table(pca[[x]]$sdev,file=paste0(sdev_out,dataset[x],".csv")))
```
