---
title: "Looking at QC metrics"
output:
  html_document: default
  pdf_document: default
---
Method 3 : 2k
Method 6 : anti hubs
REV COV

```{r load data, include = FALSE}
library(pbapply)
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_duo.R")
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_duo.R")

source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_functions.R")

hub_nb_dim<- function(data,d,hub_scores,thd,n_cell) {
  k <- min(50,round(ncol(data)/20))
  neighbors <- findKNN(t(data[1:d,]), k)
  neighbor_list <- neighbors$index
  rownames(neighbor_list) <- colnames(data)
  h_nb <- reverse_coverage_k(neighbor_list, hub_scores, k, thd, n_cell)
  return(h_nb)
}
hubness <- pblapply(1:length(hubness),
                    function(x) {hubness[[x]]$cellID <- names(hubness_scores_data[[x]][[1]][[1]]);
                    return(hubness[[x]])})
hub_scores <- pblapply(1:length(hubness),
                       function(x) hubness[[x]]$score[hubness[[x]]$Dimension==(cell_nb[x]-1) & hubness[[x]]$p==2 & hubness[[x]]$k==50])
hub_scores <- pblapply(1:length(hub_scores),
                       function(x) {names(hub_scores[[x]]) <- names(hubness_scores_data[[x]][[1]][[1]]);
                       return(hub_scores[[x]])})

vlnplot_hub_spec_3 <- function(seurat, feature, cell_type) {
  df <- cbind(seurat[[feature]],seurat[[cell_type]])
  colnames(df) <- c("feature","cell_type")
  gplot <- ggplot(df, aes(y=feature, x=cell_type, fill=cell_type)) + geom_violin(scale="area") + geom_jitter(size=0.5, color="black")
  gplot +
    xlab(NULL) +
    ylab(feature) +
    geom_hline(yintercept = mean(df$feature[df$cell_type == "normal"]),
               col="#619CFF") +
    geom_hline(yintercept = mean(df$feature[df$cell_type == "hub"]),
               col="#00BA38") +
    geom_hline(yintercept = mean(df$feature[df$cell_type == "antihub"]),
               col="#F8766D") +
    stat_compare_means(aes(label=..p.adj..), method = "t.test", p.adjust.method = "BH", label = "p.signif",
                       comparisons = list(c("antihub","hub"),c("antihub","normal"),c("hub","normal")))
}

```

```{r get the hubs with the different methods, include = FALSE}
parameter <- data.frame(50,100,2)
names(parameter) <- c("k","pc","p")
val <- pblapply(hubness,
                function(x) x$score[x$k==parameter$k & x$Dimension==parameter$pc & x$p==parameter$p])
thd3 <- pblapply(hubness,
                 function(x) get_hub3(x,kval=parameter$k,pcval=parameter$pc,pval=parameter$p)$Threshold)
hub3 <- pblapply(1:length(data),
                 function(x) colnames(data[[x]])[val[[x]]>=thd3[[x]]])
hub6 <- pblapply(1:length(data),
                 function(x) colnames(data[[x]])[val[[x]]==0])
hb_nb <- pblapply(1:length(data_pca),
                  function(y) {tmp<-hub_nb_dim(data_pca[[y]],parameter$pc,hub_scores[[y]],1, cell_nb[y]);
                                     return(tmp)})
hub_cov <- pblapply(1:length(data),
                 function(x) colnames(data[[x]])[order(val[[x]], decreasing = T)[1:hb_nb[[x]]]])
```

```{r prep Seurat, include=FALSE}
seurat <- pblapply(data,CreateSeuratObject)
seurat <- pblapply(1:length(seurat),
                   function(x) {seurat[[x]]$hub3 <- c("normal","hub")[factor(colnames(seurat[[x]]) %in% hub3[[x]], levels = c("FALSE","TRUE"))];
                   seurat[[x]]$hub6 <- c("normal","antihub")[factor(colnames(seurat[[x]]) %in% hub6[[x]], levels = c("FALSE","TRUE"))];
                   seurat[[x]]$hub_cov <- c("normal","hub")[factor(colnames(seurat[[x]]) %in% hub_cov[[x]], levels = c("FALSE","TRUE"))];
                   seurat[[x]][["percent.mt"]] <- PercentageFeatureSet(seurat[[x]], pattern = "^MT-");
                   return(seurat[[x]])})
# convert genes
pblapply(seurat,
         function(x) VlnPlot(x, features = c("nFeature_RNA","nCount_RNA","percent.mt")))
# Normalize + log transfo + scale
library(ggpubr)
seurat2 <- seurat
seurat2 <- pblapply(seurat2,NormalizeData)
seurat2 <- pblapply(seurat2,ScaleData)
seurat2 <- pblapply(seurat2,FindVariableFeatures)
seurat2 <- pblapply(seurat2,function(x) RunPCA(x, verbose = F))
seurat2 <- pblapply(seurat2,function(x) RunUMAP(x, dims = 1:50))
seurat2 <- pblapply(seurat2,function(x) RunTSNE(x, dims = 1:50))
pblapply(seurat2, function(x) DimPlot(x, reduction = "umap"))
```

```{r position -> uniform}
plot_umap <- pblapply(seurat2, function(x) DimPlot(x, reduction = "umap"))
ggarrange(plotlist=plot_umap, common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) plot_hub(x,red="umap",hubs="hub3")), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) plot_hub(x,red="umap",hubs="hub6")), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) plot_hub(x,red="umap",hubs="hub_cov")), common.legend = T)
```

```{r nFeature/nCount of hubs/anti hubs vs normal cells}
ggarrange(plotlist=pblapply(seurat2,function(x) vlnplot_hub_spec(x, "nFeature_RNA", "hub3")), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) vlnplot_hub_spec(x, "nCount_RNA", "hub3")), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) vlnplot_hub_spec(x, "nFeature_RNA", "hub6")), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) vlnplot_hub_spec(x, "nCount_RNA", "hub6")), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) vlnplot_hub_spec(x, "nFeature_RNA", "hub_cov")), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) vlnplot_hub_spec(x, "nCount_RNA", "hub_cov")), common.legend = T)

ggarrange(plotlist=pblapply(seurat2,function(x) histoplot_hub_spec(x, x$nFeature_RNA, x$hub3, "nFeature", NULL)), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) histoplot_hub_spec(x, x$nCount_RNA, x$hub3, "nCount", NULL)), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) histoplot_hub_spec(x, x$nFeature_RNA, x$hub6, "nFeature", NULL)), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) histoplot_hub_spec(x, x$nCount_RNA, x$hub6, "nCount", NULL)), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) histoplot_hub_spec(x, x$nFeature_RNA, x$hub_cov, "nFeature", NULL)), common.legend = T)
ggarrange(plotlist=pblapply(seurat2,function(x) histoplot_hub_spec(x, x$nCount_RNA, x$hub_cov, "nCount", NULL)), common.legend = T)

```

```{r dropout rate of hubs/antihubs}
seurat <- pblapply(seurat,
                   function(x) {x$dropout <- apply(x@assays$RNA@counts, 2, function(y) {sum(y==0)/length(y)});
                   return(x)})
ggarrange(plotlist=pblapply(seurat,function(x) vlnplot_hub_spec(x, "dropout", "hub3")))
ggarrange(plotlist=pblapply(seurat,function(x) vlnplot_hub_spec(x, "dropout", "hub6")))
ggarrange(plotlist=pblapply(seurat,function(x) vlnplot_hub_spec(x, "dropout", "hub_cov")))
```

```{r look @ mito/ribo genes}
#seurat[["percent.ribo"]] <- PercentageFeatureSet(seurat, pattern = c("^RPS","^RPL"))
#ggarrange(vlnplot_hub_spec(seurat, "percent.mt", "hub2"),
#          vlnplot_hub_spec(seurat, "percent.mt", "hub6"),
#          vlnplot_hub_spec(seurat, "percent.mt", "hub7"))
#ggarrange(vlnplot_hub_spec(seurat, "percent.ribo", "hub2"),
#          vlnplot_hub_spec(seurat, "percent.ribo", "hub6"),
#          vlnplot_hub_spec(seurat, "percent.ribo", "hub7"))
# all same for Satija ..
```

```{r summary fig with rev cov and antihubs}
# nFeature, nCount, dropout rate
seurat <- pblapply(seurat,
                   function(x) {x$status <- sapply(1:ncol(x),
                     function(y) ifelse(x$hub_cov[y]=="hub","hub",ifelse(x$hub6[y]=="antihub","antihub","normal")));
                   return(x)})
seurat2 <- pblapply(seurat2,
                   function(x) {x$status <- sapply(1:ncol(x),
                     function(y) ifelse(x$hub_cov[y]=="hub","hub",ifelse(x$hub6[y]=="antihub","antihub","normal")));
                   return(x)})
seurat <- pblapply(seurat,
                   function(x) {x$Dropout <- x$dropout*100; return(x)})
p1 <- ggarrange(plotlist=pblapply(seurat,function(x) vlnplot_hub_spec_3(x, "nFeature_RNA", "status")), common.legend = T, labels = dataset)
p2 <- ggarrange(plotlist=pblapply(seurat,function(x) vlnplot_hub_spec_3(x, "nCount_RNA", "status")), common.legend = T, labels = dataset)
p3 <- ggarrange(plotlist=pblapply(seurat,function(x) vlnplot_hub_spec_3(x, "Dropout", "status")), common.legend = T, labels = dataset)
p4 <- ggarrange(plotlist=pblapply(seurat2,function(x) plot_hub(x,red="umap",hubs="status")), common.legend = T, labels = dataset)
p1
p2
p3
p4
```

