---
title: "PCA obj"
output: html_document
---

```{r libs & paths}
library(pbapply)
library(ggplot2)
Skewness <- function(distrib) {
  return(mean((distrib-mean(distrib))^3)/(sd(distrib)^3))
}
asymmetry_evaluation <- function(data) {
  knn_graph <- knn.covertree::find_knn(t(data),k)
  knn_list <- knn_graph$index
  increment = 0
  for (i in 1:nrow(knn_list)) {
    for (j in 1:ncol(knn_list)) {
      if (i %in% knn_list[knn_list[i,j],]) {
        increment <- increment + 1 
      }
    }
  }
  return(1-increment/(nrow(knn_list)*ncol(knn_list)))
}
dropout_percent <- c(0,5,10,20,30,40,50,75,80,85,90,95)
sdev_path <- sapply(dropout_percent, function(y) paste0("/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/simul_pca_sdev",y,".csv"))
data_path <- sapply(dropout_percent, function(y) paste0("/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/simul_pca_readyforhubness",y,".csv"))
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_simul.R")
hubness <- lapply(hubness, function(x) {x$cellID <- names(hubness_scores_data[[1]][[1]][[1]]); return(x)})
```

```{r screeplot}
simul_pca <- pblapply(data_path, function(x) read.table(file=x))
sdev <- pblapply(sdev_path, function(x) read.table(file=x))
sdev <- pblapply(sdev, function(x) return(x/x[1,1]))
for (i in 1:length(sdev)) {
  sdev[[i]]$Dropout <- dropout_percent[i]
}
all_sdev <- lapply(sdev, function(x) return(x[1:100,]))
all_sdev <- do.call(rbind,all_sdev)
all_sdev$eigenvalue <- 1:100
ggplot(all_sdev, aes(x=eigenvalue, y=x, color=factor(Dropout))) + geom_point(size=0.5) + geom_line(aes(group=Dropout), alpha=0.5, lty=3) + geom_hline(yintercept=0.1)

# ID
linear_dim <- pbsapply(sdev, function(x) return(which(x<=0.1)[1]))
linear_dim <- sapply(linear_dim, function(x) {tmp<-ifelse(is.na(x),cell_nb,x); return(tmp)})
# Skewness
k=50
dim_val = c(2,5,10,20,30,40,50,100,500,1000,1212)
scores <- pblapply(dim_val, function(y) lapply(hubness, function(x) return(x$score[x$p==2 & x$k==k & x$Dimension==y])))
skewness <- pbsapply(scores, function(x) sapply(x,Skewness))
# Asymmetry
asymmetry <- pblapply(dim_val, function(x) sapply(simul_pca, function(y) asymmetry_evaluation(y[1:x,])))
# Summary
df <- lapply(1:length(dim_val), function(x) return(data.frame("Skewness"=skewness[,x],
                                                              "Dropout"=dropout_percent,
                                                              "Asymmetry"=asymmetry[[x]],
                                                              "ID"=linear_dim,
                                                              "Manifold_dimension"=dim_val[x])))
lapply(df, function(x) ggplot(x, aes(x=Dropout, y=ID, color=Skewness)) + geom_point() + scale_color_gradient(low="blue", high="red"))
lapply(df, function(x) ggplot(x, aes(x=Dropout, y=ID, color=Asymmetry)) + geom_point() + scale_color_gradient(low="blue", high="red"))

lapply(df, function(x) ggplot(x, aes(x=ID, y=Asymmetry, color=Dropout)) + geom_point() + scale_color_gradient(low="blue", high="red"))
#lapply(df, function(x) ggplot(x, aes(x=Dropout, y=Skewness)) + geom_point())

df_tot <- do.call(rbind,df)
ggplot(df_tot, aes(x=ID, y=Asymmetry, color=Dropout)) + geom_point() + scale_color_gradient(low="blue", high="red") + geom_line(aes(group=Manifold_dimension)) + scale_y_log10()
```
