---
title: "Skewness x size"
output:
  html_document: default
  pdf_document: default
---
Method 4 : skewness, appropriate YES

```{r libs, results="hide", include = FALSE}
library(philentropy, quietly = T)
library(ggplot2, quietly = T)
library(viridis, quietly = T)
library(ggridges, quietly = T)
library(scales, quietly = T)
library(ggpubr, quietly = T)
library(pbapply, quietly = T)
```

```{r functions, include = FALSE}
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_simul.R")
get_hub4 <- function(df,kval,pcval,pval) { # skewness
   s = c()
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
            val = df$score[df$Dimension==d & df$p==p & df$k==k]
            s = c(s, mean((val-mean(val))^3)/sd(val)^3)
         }
      }
   }
   skewness_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=s)
   skewness_val$Dimension <- factor(skewness_val$Dimension, levels = pcval)
   return(skewness_val)
}
```

```{r get the skewness}
minkow=2
skewness <- pbsapply(X=hubness, FUN=function(x) get_hub4(x,kval=50,pcval=pcval,pval=minkow)$GHubness)
skewness <- data.frame("Skewness"=as.vector(skewness),
                       "Dimension"=rep(pcval,times=length(hubness)))
skewness$Dropout <- rep(dropout_percent, each=length(pcval))
skewness$Size <- cell_nb
ggplot(skewness, aes(x=Dropout, y=Skewness, color=Dimension)) + geom_point() + geom_line(aes(group=Dimension), lty=2)
ggplot(skewness, aes(x=Dimension, y=Skewness, color=factor(Dropout))) + geom_point() + geom_line(aes(group=Dropout), lty=2)
```


