---
title: "Antihubs x Dropout"
output: html_document
---

```{r load data, include = FALSE}
library(pbapply)
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_simul.R")
hubness <- lapply(hubness, function(x) {x$cellID <- names(hubness_scores_data[[1]][[1]][[1]]); return(x)})

dropout_percent <- c(5,10,20,30,40,50,75,80,85,90,95)
counts_path <- sapply(dropout_percent, function(y) paste0("/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/simul",y,".csv"))
pca_path <- sapply(dropout_percent, function(y) paste0("/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/simul_pca_readyforhubness",y,".csv"))
simul <- pblapply(counts_path, function(x) read.table(x))
simul_pca <- pblapply(pca_path, function(x) read.table(x))

source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_functions.R")
```

```{r get hub scores, include=FALSE}
dim_val=pcval
idx <- seq(from=1, to=nrow(hubness[[1]]), by=cell_nb)
tmp <- lapply(hubness, function(x) x[idx,])
hub_scores <- pbsapply(tmp, function(x) {return(x$Antihubs[x$p==2 & x$k==50])})
```

```{r get neighbors nb}
antihub_nb <- data.frame("Antihub_nb" = as.vector(hub_scores))
antihub_nb$Dimension <- dim_val
antihub_nb$Dropout <- factor(rep(dropout_percent, each=length(dim_val)))
```

```{r antihub nb as a function of the dimension}
ggplot(antihub_nb, aes(x=Dimension, y=Antihub_nb, color=Dropout)) +
  geom_point() +
  geom_line(aes(group=Dropout), lty=2) +
  ylim(0,max(antihub_nb$Antihub_nb))
ggplot(antihub_nb, aes(x=Dropout, y=Antihub_nb, color=Dimension)) +
  geom_point() +
  geom_line(aes(group=Dimension), lty=2) +
  ylim(0,max(antihub_nb$Antihub_nb))
```
