---
title: "Looking at QC metrics"
output:
  html_document: default
  pdf_document: default
---
Method 3 : 2k
Method 6 : anti hubs
REV COV

```{r load data, include = FALSE}
library(pbapply)
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_duo.R")
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_duo.R")

source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_functions.R")

hubness <- pblapply(1:length(hubness),
                    function(x) {hubness[[x]]$cellID <- names(hubness_scores_data[[x]][[1]][[1]]);
                    return(hubness[[x]])})
hub_scores <- pblapply(1:length(hubness),
                       function(x) hubness[[x]]$score[hubness[[x]]$Dimension==(cell_nb[x]-1) & hubness[[x]]$p==2 & hubness[[x]]$k==50])
hub_scores <- pblapply(1:length(hub_scores),
                       function(x) {names(hub_scores[[x]]) <- names(hubness_scores_data[[x]][[1]][[1]]);
                       return(hub_scores[[x]])})
```

```{r get the hubs, include = FALSE}
parameter <- data.frame(50,100,2)
names(parameter) <- c("k","pc","p")
val <- pblapply(hubness,
                function(x) x$score[x$k==parameter$k & x$Dimension==parameter$pc & x$p==parameter$p])
hb_nb <- pblapply(1:length(data_pca),
                  function(y) {tmp<-hub_nb_dim(data_pca[[y]],parameter$pc,hub_scores[[y]],0.1, cell_nb[y]);
                                     return(tmp)})
hub_cov <- pblapply(1:length(data),
                 function(x) colnames(data[[x]])[order(val[[x]], decreasing = T)[1:hb_nb[[x]]]])
```

```{r rm hubs, include=FALSE}
data <- pblapply(1:length(data),
                 function(x) {tmp <- data[[x]][,!(colnames(data[[x]]) %in% hub_cov[[x]])]})
```

```{r make pca}
data_prep <- function(data) {
  data <- log10(data+1)
  return(data)
}
# Log transfo
data <- pblapply(data, function(x) data_prep(x))
# PCA
pca <- pblapply(data, function(x) prcomp(x, center=T, scale.=F))
data_proj <- pblapply(pca, function(x) t(x$rotation))
lapply(pca,function(x) plot(1:50,x$sdev[1:50]))
```

```{r save data}
data_out <- "/Users/elise/Desktop/GitHub/Hubness_sc/duo/hub_removal/"
pblapply(1:length(data_proj),
         function(x) write.table(data_proj[[x]], file=paste0(data_out,dataset[x],"_pca_readyforhubness.csv")))
pblapply(1:length(data),
         function(x) write.table(data[[x]], file=paste0(data_out,dataset[x],".csv")))
```

```{r get hub scores}
library(philentropy)
library(pbapply)

# MAKE THE DIST MATRIX WITH ALL ENTRIES EXCEPT DIAG INSTEAD OF UPPER TRI

dataset <- c("Koh","KohTCC","Kumar","KumarTCC","SimKumar4easy","SimKumar4hard","SimKumar8hard","Trapnell","TrapnellTCC")
matrix <- pblapply(dataset,
                   function(x) read.table(paste0(data_out,x,"_pca_readyforhubness.csv")))
print("data loaded!")
n_dim = pbsapply(matrix,
                 function(x) nrow(x))

# matrix is PCs x cell

# Range of k values
k.val <- c(5,50,100,200)

# Range of p values for Lp norm
p.val <- c(0.1,0.5,1,1.5,2,4,10)
p.val <- 2

# Range of PCs nb values
pc.val <- c(2,5,10,20,30,40,50,100,500,1000,5000,n_dim-1)
pc.val <- pblapply(n_dim,
                   function(x) return(c(2,5,10,20,30,40,50,100,x-1)))

# Write the function for the kNN graph
distance_dim <- function(data,p) {
  mat <- t(data)
  dist.matrix <- philentropy::distance(mat,method="minkowski",p)
  diag(dist.matrix) <- NA # remove diag only
  return(dist.matrix)
}
kNN <- function(dist.matrix,k) {
  k.nn <- t(apply(dist.matrix,1,function(x) order(x,na.last=T)[1:k]))
  return(k.nn)
}
# Get the k-occurences from the kNN graph
k.occurence <- function(k.nn,data) {
  occurence <- sapply(X=1:nrow(k.nn), FUN=function(x,y) {sum(y==x)}, y=k.nn)
  names(occurence) <- colnames(data)
  return(occurence)
}
# Get the scores
get_scores <- function(data,k.val,p.val,pc.val,name) {
  for (pc in pc.val) {
    data_pc <- data[1:pc,]
    for (p in p.val) {
      dist.matrix <- distance_dim(data=data_pc,p=p)
      minkow <- lapply(X=k.val, FUN=function(x,y,z) {k.occurence(kNN(y,x),z)}, y=dist.matrix, z=data)
      saveRDS(minkow, file=paste0("/Users/elise/Desktop/GitHub/Hubness_sc/results/",name,"/kNN_occurence_",p,"_pca",pc,"_minkow_bis.rds"))
      print(paste0(p, " pval done for PC",pc))
    }
  }
}
pblapply(1:length(matrix),
         function(x) get_scores(matrix[[x]], k.val=k.val, p.val=p.val, pc.val=pc.val[[x]], name=paste0("duo_removal/",dataset[x])))
```

```{r hub param}
library(ggplot2, quietly = T)
library(viridis, quietly = T)
library(ggridges, quietly = T)
library(scales, quietly = T)
library(ggpubr, quietly = T)
library(pbapply)
library(knn.covertree)
data_load <- function(path) {
   source(file=path)
   return(hubness)
}
dataset <- c("Koh","KohTCC","Kumar","KumarTCC","SimKumar4easy","SimKumar4hard","SimKumar8hard","Trapnell","TrapnellTCC")
data_hubness <- data_load("/Users/elise/Desktop/Github/Hubness_sc/R_scripts/load_data/hubness_load_write_data_duo_removal.R")
data_pca <- pblapply(dataset,
                     function(x) read.table(paste0("/Users/elise/Desktop/GitHub/Hubness_sc/duo/hub_removal/",x,"_pca_readyforhubness.csv")))

get_hub3 <- function(df,kval,pcval,pval,log=F) { # Using the method from [1] >= 2k
   if (log==T) {
      hub_nb = c()
      ymin = c()
      ymax = c()
      y_increment = 1
      for (d in pcval) {
         for (k in kval) {
            for (p in pval) {
               val = df$score[df$Dimension==d & df$p==p & df$k==k]
               hub_nb = c(hub_nb, sum(val>=2*log(k)))
               ymin = c(ymin,y_increment)
               ymax = c(ymax,y_increment+1)
            }
         }
      y_increment <- y_increment+1
      }
   }
   else {
      hub_nb = c()
      ymin = c()
      ymax = c()
      y_increment = 1
      for (d in pcval) {
         for (k in kval) {
            for (p in pval) {
               val = df$score[df$Dimension==d & df$p==p & df$k==k]
               hub_nb = c(hub_nb, sum(val>=2*k))
               ymin = c(ymin,y_increment)
               ymax = c(ymax,y_increment+1)
            }
         }
      y_increment <- y_increment+1
      }
   }
   hub_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=hub_nb,
                         "ymin"=ymin,
                         "ymax"=ymax)
   hub_val$Threshold <- 2*hub_val$k
   return(hub_val)
}
get_hub4 <- function(df,kval,pcval,pval) { # skewness
   s = c()
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
            val = df$score[df$Dimension==d & df$p==p & df$k==k]
            s = c(s, mean((val-mean(val))^3)/sd(val)^3)
         }
      }
   }
   skewness_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=s)
   skewness_val$Dimension <- factor(skewness_val$Dimension, levels = pcval)
   return(skewness_val)
}
fn_zarb <- function(knn_list) {
   increment = 0
   for (i in 1:nrow(knn_list)) {
      for (j in 1:ncol(knn_list)) {
         if (i %in% knn_list[knn_list[i,j],]) {
            increment <- increment + 1 
      }
    }
   }
   return(1-increment/(nrow(knn_list)*ncol(knn_list)))
}
get_hub7 <- function(data,kval,pcval,pval) { #asymmetry
  knn_graph <- lapply(pcval,
                      function(x) lapply(kval,
                                         function(y) knn.covertree::find_knn(t(data[1:x,]),y)))
  knn_list <- lapply(knn_graph,
                     function(x) lapply(x,
                                        function(y) y$index))
  result <- lapply(knn_list,
                   function(x) sapply(x,
                                      function(y) fn_zarb(y)))
  asy_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=unlist(result))
   asy_val$Dimension <- factor(asy_val$Dimension, levels = pcval)
  return(asy_val)
}
make_merge <- function(hubness,data,kval,pcval,pval,name,size) {
hub_k <- get_hub3(hubness, kval=kval,pcval=pcval,pval=pval)
hub_skew <- get_hub4(hubness, kval=kval,pcval=pcval,pval=pval)
hub_asym <- get_hub7(data, kval=kval,pcval=pcval,pval=pval)
hub_k <- hub_k[,colnames(hub_skew)]
hub_k$GHubness <- hub_k$GHubness*100/size
hub_k$Method <- "2k"
hub_skew$Method <- "Skewness"
hub_asym$Method <- "Asymmetry"
hub <- rbind(hub_skew,hub_k,hub_asym)
hub$Dataset <- name
return(hub)
}
Dataset <- dataset
size <- cell_nb
pcval=pblapply(dim_nb,
               function(x) return(c(2,5,10,20,30,40,50,100,x-1)))
pcval2=pblapply(dim_nb,
               function(x) return(c(2,5,10,20,30,40,50,100)))
df_hub <- pblapply(1:length(Dataset),
             function(x) make_merge(data_hubness[[x]],data_pca[[x]],50,pcval[[x]],2,Dataset[x],size[x]))
df <- do.call(rbind,df_hub)
df$Dimension <- as.numeric(as.character(df$Dimension))
df_hub2 <- pblapply(1:length(Dataset),
             function(x) make_merge(data_hubness[[x]],data_pca[[x]],50,pcval2[[x]],2,Dataset[x],size[x]))
df2 <- do.call(rbind,df_hub2)
df2$Dimension <- as.numeric(as.character(df2$Dimension))

# Viz
ggplot(df, aes(x=Dimension, y=GHubness)) + geom_line(aes(group=Dataset, color=Dataset)) + geom_point(size=0.1) + facet_wrap(~Method, scales = "free") + ylab(NULL)
ggplot(df2, aes(x=Dimension, y=GHubness)) + geom_line(aes(group=Dataset, color=Dataset)) + geom_point(size=0.1) + facet_wrap(~Method, scales = "free") + ylab(NULL)
```

