---
title: "PCA obj"
output: html_document
---

```{r libs & paths}
library(Seurat)
library(ggplot2)
data_in <- "/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/Raw_data_TCGA-BRCA.RData"
data_out <- "/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/brca_pca_readyforhubness.txt"
sdev_out <- "/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/brca_pca_sdev.txt"
```

```{r do PCA}
load(data_in)
rownames(data) <- data[,1]
data <- data[,-1] # 60488 x 1222
# Sparsity
sum(data==0)/ncol(data)/nrow(data)*100 # 46%
# Remove bad genes
ncells <- apply(data,1,function(x) sum(x!=0, na.rm=T))
data <- data[ncells>2,] # 57763 x 1222
sum(data==0)/ncol(data)/nrow(data)*100 # 44%
nfeature <- apply(data,2,function(x) sum(x!=0, na.rm=T))
ncount <- apply(data,2,function(x) sum(x, na.rm=T))
plot(nfeature,ncount)
data <- data[,nfeature<4e4] # 57763 x 1213
write.csv(data,"/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/brca.csv")
# Seurat normalization
seurat <- CreateSeuratObject(data)
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat)
data <- GetAssayData(seurat)
rm(seurat)
# PCA
pca <- prcomp(data)
data_proj <- t(pca$rotation)
# 1213 PCs
write.table(data_proj, file=data_out)
write.table(pca$sdev,file=sdev_out)
```
