---
title: "dropout x hubs"
output: html_document
---


```{r rev cov hub}
library(pbapply)
library(ggplot2)
datasets <- c("Baron","Darmanis","Ewing","Guo","Pancreatic","PDX1","Satija","Silver","Zheng4","Zheng8","BRCA")
load_data_revco <- function(dataset) {
  source(file=paste0("/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_",dataset,".R"))
  sparsity <- mean(apply(data,2,function(x) mean(x==0, na.rm = T)))*100
  hubs <- readRDS(paste0("/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hubness_def/rev_cov/hubs_",dataset,".rds"))
  hub_nb <- length(hubs)
  return(c(sparsity,hub_nb))
}
plot_dropout <- function(df,method_name) {
  ggplot(df, aes(x=Hub_nb, y=Dropout, color=Method)) +
   geom_point() +
   xlab("Number of hubs") +
   geom_line(aes(group=Method),linetype='dotted') +
   ggtitle(method_name)
}

test=pbsapply(datasets,function(x) load_data_revco(x))
df = data.frame(t(test))
colnames(df) <- c("Dropout","Hub_nb")
df$Method = c(rep("single-cell",nrow(df)-1),"bulk")
plot_dropout(df,"Rev cov")
```

```{r skewness}
main_path = "/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_"
get_hub4 <- function(df,kval,pcval,pval) { # skewness
   s = c()
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
            val = df$score[df$Dimension==d & df$p==p & df$k==k]
            s = c(s, mean((val-mean(val))^3)/sd(val)^3)
         }
      }
   }
   skewness_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=s)
   skewness_val$Dimension <- factor(skewness_val$Dimension, levels = pcval)
   return(skewness_val)
}
load_data_skewness <- function(dataset,df_revcov) {
  sparsity <- df_revcov[dataset,1]
  source(file=paste0(main_path,dataset,".R"))
  hub_skewness <- get_hub4(hubness, kval=100,pcval=pcval[length(pcval)-1],pval=2)
  skewness <- hub_skewness$GHubness
  return(c(sparsity,skewness))
}
plot_skewness <- function(df) {
  ggplot(df, aes(x=Skewness, y=Dropout, color=Method)) +
   geom_point() +
   xlab("Skewness") +
   geom_line(aes(group=Method),linetype='dotted') +
   ggtitle("Skewness")
}

test=pbsapply(datasets,function(x) load_data_skewness(x,df))
df_skewness = data.frame(t(test))
colnames(df_skewness) <- c("Dropout","Skewness")
df_skewness$Method = c(rep("single-cell",nrow(df_skewness)-1),"bulk")
plot_skewness(df_skewness)
```

