---
title: "Hub definition comparison - BRCA x Silver"
output: html_document
---

```{r load data, include = FALSE}
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_functions.R")

source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_Silver.R")
hubness$cellID <- names(hubness_scores_data[[1]][[1]])
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_Silver.R")
sc_data <- data
sc_data_pca <- data_pca
sc_hubness <- hubness
sc_hubness_scores_data <- hubness_scores_data
sc_cell_nb <- cell_nb
sc_dim_nb <- dim_nb
sc_pcval <- pcval

source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_BRCA.R")
hubness$cellID <- names(hubness_scores_data[[1]][[1]])
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_BRCA.R")
bulk_data <- data
bulk_data_pca <- data_pca
bulk_hubness <- hubness
bulk_hubness_scores_data <- hubness_scores_data
bulk_cell_nb <- cell_nb
bulk_dim_nb <- dim_nb
bulk_pcval <- pcval

rm(data,data_pca,hubness,entropy,hubness_scores_data,cell_nb,dim_nb,pcval)
```

```{r get hub scores, include=FALSE}
sc_hub_scores <- sc_hubness$score[sc_hubness$Dimension==(sc_cell_nb-1) & sc_hubness$p==2 & sc_hubness$k==50]
bulk_hub_scores <- bulk_hubness$score[bulk_hubness$Dimension==(bulk_cell_nb-1) & bulk_hubness$p==2 & bulk_hubness$k==50]

names(sc_hub_scores) <- names(sc_hubness_scores_data[[1]][[1]])
names(bulk_hub_scores) <- names(bulk_hubness_scores_data[[1]][[1]])
```

```{r functions, include=FALSE}
library(pbapply)
get_hub4 <- function(df,kval,pcval,pval) { # skewness
   s = c()
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
            val = df$score[df$Dimension==d & df$p==p & df$k==k]
            s = c(s, mean((val-mean(val))^3)/sd(val)^3)
         }
      }
   }
   skewness_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=s)
   skewness_val$Dimension <- factor(skewness_val$Dimension, levels = pcval)
   return(skewness_val)
}
plot_evol_comp <- function(hub_val1,hub_val2,type1,type2,method_name,label.y) {
  df1 <- hub_val1
  df2 <- hub_val2
  df1$Method <- type1
  df2$Method <- type2
  df <- rbind(df1,df2)
  ggplot(df, aes(x=factor(Dimension), y=GHubness, color=Method)) +
   geom_point() +
   ylab(label.y) +
   xlab("Dimension") +
   geom_line(aes(group=Method),linetype='dotted') +
   ggtitle(method_name) +
   facet_wrap(~k)
}
plot_evol_comp2 <- function(hub_val1,hub_val2,type1,type2,method_name,label.y) {
  df1 <- hub_val1
  df2 <- hub_val2
  df1$Method <- type1
  df2$Method <- type2
  df <- rbind(df1,df2)
  ggplot(df, aes(x=Dimension, y=log(GHubness), color=Method)) +
   geom_point() +
   ylab(label.y) +
   xlab("Dimension") +
   geom_line(aes(group=Method),linetype='dotted') +
   ggtitle(method_name)
}
reverse_coverage_k <- function(neighbor_list, hub_scores, k, thd,n_cell) {
  cell_scores_sorted <- order(hub_scores, decreasing=T)
  hub_nb <- 10
  hubs <- cell_scores_sorted[1:hub_nb]
  coverage <- sum(apply(neighbor_list[,1:k],1,function(x) any(x %in% hubs)))
  while (coverage[hub_nb/10] < n_cell*0.9 & hub_nb < 1000) {
    hub_nb <- hub_nb+10
    hubs <- cell_scores_sorted[1:hub_nb]
    coverage <- c(coverage, sum(apply(neighbor_list[,1:k],1,function(x) any(x %in% hubs))))
  }
  rev_coverage_rdm <- reverse_coverage_random_k(neighbor_list, k, n_cell)
  return(plateau_detection(neighbor_list, hub_scores, k, thd, n_cell))
}
hub_nb_dim<- function(data,d,k,hub_scores,thd,n_cell) {
  neighbors <- findKNN(t(data[1:d,]), k)
  neighbor_list <- neighbors$index
  rownames(neighbor_list) <- colnames(data)
  h_nb <- reverse_coverage_k(neighbor_list, hub_scores, k, thd, n_cell)
  return(h_nb)
}
```

```{r skewness}
sc_hub_skewness <- get_hub4(sc_hubness, kval=kval,pcval=sc_pcval,pval=2)
bulk_hub_skewness <- get_hub4(bulk_hubness, kval=kval,pcval=bulk_pcval,pval=2)
plot_evol_comp(sc_hub_skewness,bulk_hub_skewness,"single-cell","bulk","Skewness across dimensions","Skewness")
```

```{r mean and sd}
sc_hub2 <- get_hub2(sc_hubness, kval=kval,pcval=sc_pcval,pval=2)
bulk_hub2 <- get_hub2(bulk_hubness, kval=kval,pcval=bulk_pcval,pval=2)
sc_hub2$GHubness <- sc_hub2$GHubness/sc_cell_nb*100
bulk_hub2$GHubness <- bulk_hub2$GHubness/bulk_cell_nb*100
plot_evol_comp(sc_hub2,bulk_hub2,"single-cell","bulk","Nb of hubs across dimensions","Nb of hubs (%)")
```

```{r reverse hubs}
sc_k=min(100,round(ncol(sc_data)/20))
sc_dim_val=c(2,5,10,20,30,40,50,100,500,1000,sc_dim_nb)
sc_hb_nb <- pbapply::pbsapply(sc_dim_val, FUN=function(x) hub_nb_dim(sc_data_pca,x,sc_k,sc_hub_scores,1,sc_cell_nb))
sc_hb_df <- data.frame("GHubness"=sc_hb_nb,
                       "Dimension"=sc_dim_val)
bulk_k=min(100,round(ncol(bulk_data)/20))
bulk_dim_val=c(2,5,10,20,30,40,50,100,500,1000,bulk_dim_nb)
bulk_hb_nb <- pbapply::pbsapply(bulk_dim_val, FUN=function(x) hub_nb_dim(bulk_data_pca,x,bulk_k,bulk_hub_scores,1,bulk_cell_nb))
bulk_hb_df <- data.frame("GHubness"=bulk_hb_nb,
                       "Dimension"=bulk_dim_val)
sc_hb_df$GHubness <- sc_hb_df$GHubness/sc_cell_nb*100
bulk_hb_df$GHubness <- bulk_hb_df$GHubness/bulk_cell_nb*100
plot_evol_comp2(sc_hb_df,bulk_hb_df,"single-cell","bulk","Nb of reverse hubs across dimensions","Nb of hubs (%)")
```
