---
title: "PCA obj"
output: html_document
---

```{r libs & paths}
library(pbapply)
library(ggplot2)
library(ggpubr)
dropout_percent <- c(0,10,20,30,40,50,60,70,80,90,95)
datasets <- c("TCGA_BRCA","TCGA_KIRC","ARCHS4")
data_in <- lapply(datasets,
                  function(x) sapply(dropout_percent, function(y) paste0("/Users/elise/Desktop/GitHub/Hubness_sc/Data_bulk/", x, "/simulated/simul_dropout", y,".csv")))
data_out <- lapply(datasets,
                  function(x) sapply(dropout_percent, function(y) paste0("/Users/elise/Desktop/GitHub/Hubness_sc/Data_bulk/", x, "/pca/simul_dropout", y,"_pca.csv")))
sdev_out <- lapply(datasets,
                  function(x) sapply(dropout_percent, function(y) paste0("/Users/elise/Desktop/GitHub/Hubness_sc/Data_bulk/", x, "/pca/simul_dropout", y,"_sdev.csv")))
```

```{r functions}
zero_percent <- function(data) { # gene x cell matrix
  return(sum(data==0)/ncol(data)/nrow(data)*100)
}
data_prep <- function(data) {
  data <- log10(data+1)
  return(data)
}
```

```{r do PCA}
# load data
data <- pblapply(X=data_in, FUN=function(x) lapply(x,
                                                   function(y) read.table(file=y)))
# Keep 10k HVG
data <- lapply(data, function(x) pblapply(x,
                                          function(y) {hvg<-names(sort(apply(y,1,var),decreasing=T)[1:1e4]); return(y[hvg,])}))
# Log transfo
data <- lapply(data, function(y) pblapply(y, function(x) data_prep(x)))
# PCA
pca <- lapply(data, function(y) pblapply(y, function(x) prcomp(x, center=T, scale.=F)))
data_proj <- lapply(pca, function(y) pblapply(y, function(x) t(x$rotation)))

mapply(z=data_proj, t=data_out, function(z,t) pbmapply(x=z, y=t, function(x,y) write.table(x, file=y)))
mapply(z=pca, t=sdev_out, function(z,t) pbmapply(x=z, y=t, function(x,y) write.table(x$sdev, file=y)))
```

```{r plot sdev}
sdev <- lapply(pca, function(y) pblapply(y, function(x) return(x$sdev/x$sdev[1])))
sdev_df <- lapply(sdev,
                  function(y) data.frame("Sdev" = unlist(y),
                      "Dropout"=as.factor(rep(dropout_percent,each=length(y[[1]]))),
                      "PC"=1:length(y[[1]])))
pdf(file="/Users/elise/Desktop/GitHub/Hubness_sc/Figure3_supp/screeplot.pdf")
ggarrange(ggplot(sdev_df[[1]][sdev_df[[1]]$PC<25,], aes(x=PC, y=Sdev, color=Dropout)) +
                              geom_point() +
                              geom_line(aes(group=Dropout)) +
                              geom_hline(yintercept=0.1) +
                              scale_color_viridis_d() +
                              ylab("Sd/Sd1") +
            xlab("Principal Components"),
          ggplot(sdev_df[[2]][sdev_df[[2]]$PC<25,], aes(x=PC, y=Sdev, color=Dropout)) +
                              geom_point() +
                              geom_line(aes(group=Dropout)) +
                              geom_hline(yintercept=0.1) +
                              scale_color_viridis_d() +
                              ylab("") +
            xlab("Principal Components"),
          labels = datasets,
          common.legend = T)
dev.off()

pdf(file="/Users/elise/Desktop/GitHub/Hubness_sc/Figure3_supp/IDxDropout.pdf")
linear_dim_df <- data.frame("GID_pca"=unlist(lapply(sdev, function(y) sapply(y, function(x) return(which(x<=0.1)[1]/length(x))))),
                         "Dataset"=rep(datasets, each=length(dropout_percent)),
                         "Dropout"=dropout_percent)
ggplot(linear_dim_df, aes(x=Dropout, y=GID_pca)) +
  geom_point() +
  geom_line(aes(group=Dataset, color=Dataset)) +
  ylab("Normalized intrinsic Dimension") +
  scale_x_log10()
dev.off()
```

```{r distance correlation scatter plot NOT SUPER USEFUL}
#dropout_choice <- c(0,50,90)
#choice <- dropout_percent %in% dropout_choice
#nPC <- c(1e1,1e2,1e3)
#mat_ref <- lapply(data, function(x) x[choice])
#mat_pca <- lapply(data_proj, function(x) x[choice])
#distances_ref <- lapply(mat_ref, function(y) pblapply(y, function(x) dist(t(x))))
#distances_pca <- lapply(mat_pca, function(y) pblapply(y, function(y) {sapply(nPC, #function(x) dist(t(y[1:x,])))}))
#                        
#dist_df <- lapply(distances_pca,
#                  function(x) data.frame("Distance"=unlist(x),
#                      "Dropout"=rep(rep(dropout_choice,each=lengths(x)[1]/length(dropout_cho#ice)),times=length(nPC)),
#                      "nPC"=rep(nPC,each=lengths(x)[1])))
#dist_df_0 <- mapply(x=distances_ref,y=dist_df,
#                  function(x,y) #data.frame("Distance_ref"=rep(unlist(x)[1:lengths(x)[1]],times=length(nPC)),
#                        "Distance_comp"=c(y$Distance[y$Dropout==0 & y$nPC==1e1],
#                                          y$Distance[y$Dropout==0 & y$nPC==1e2],
#                                          y$Distance[y$Dropout==0 & y$nPC==1e3]),
#                        "nPC"=rep(nPC,each=sum(y$Dropout==0 & y$nPC==1e1))), SIMPLIFY = F)
#dist_df_50 <- mapply(x=distances_ref,y=dist_df,
#                  function(x,y) #data.frame("Distance_ref"=rep(unlist(x)[1:lengths(x)[1]],times=length(nPC)),
#                        "Distance_comp"=c(y$Distance[y$Dropout==50 & y$nPC==1e1],
#                                          y$Distance[y$Dropout==50 & y$nPC==1e2],
#                                          y$Distance[y$Dropout==50 & y$nPC==1e3]),
#                        "nPC"=rep(nPC,each=sum(y$Dropout==50 & y$nPC==1e1))), SIMPLIFY = F)
#dist_df_90 <- mapply(x=distances_ref,y=dist_df,
#                  function(x,y) #data.frame("Distance_ref"=rep(unlist(x)[1:lengths(x)[1]],times=length(nPC)),
#                        "Distance_comp"=c(y$Distance[y$Dropout==90 & y$nPC==1e1],
#                                          y$Distance[y$Dropout==90 & y$nPC==1e2],
#                                          y$Distance[y$Dropout==90 & y$nPC==1e3]),
#                        "nPC"=rep(nPC,each=sum(y$Dropout==90 & y$nPC==1e1))), SIMPLIFY = F)
#lapply(dist_df_0,
#       function(x) ggplot(x, aes(x=Distance_ref,y=Distance_comp,color=factor(nPC))) +
#  geom_density2d(aes(group = nPC), size=1) +
#  geom_point(size=0.01, alpha=0.01))
#lapply(dist_df_50,
#       function(x) ggplot(x, aes(x=Distance_ref,y=Distance_comp,color=factor(nPC))) +
#  geom_density2d(aes(group = nPC), size=1) +
#  geom_point(size=0.01, alpha=0.01))
#lapply(dist_df_90,
#       function(x) ggplot(x, aes(x=Distance_ref,y=Distance_comp,color=factor(nPC))) +
#  geom_density2d(aes(group = nPC), size=1) +
#  geom_point(size=0.01, alpha=0.01))
```

