---
title: "fig1"
output: html_document
---

```{r}
library(pbapply)
library(EnsDb.Hsapiens.v79)
dropout_percent <- c(0,5,10,20,30,40,50,75,80,85,90,95)
data_in <- sapply(dropout_percent, function(y) paste0("/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/simul",y,".csv"))
data_out <- sapply(dropout_percent, function(y) paste0("/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/simul_pca_readyforhubness",y,".csv"))
```

```{r functions}
library(circlize)
library(ComplexHeatmap)
library(ggplot2)
zero_percent <- function(data) { # gene x cell matrix
  return(sum(data==0)/ncol(data)/nrow(data)*100)
}
data_prep <- function(data) {
  data <- log10(data+1)
  return(data)
}
dist_heatmap <- function(dist) {
  col_fun = colorRamp2(c(0,0.5,1),heat.colors(n=3))
  Heatmap(as.matrix(dist), cluster_rows = T, cluster_columns = T, col = col_fun,
        border = T, show_column_names = F, show_row_names = F, name = "Euclidean distance")
}
max_min_ratio <- function(dist) {
  tmp <- as.matrix(dist)
  diag(tmp) <- NA
  ratios <- apply(tmp, 1, function(x) max(x, na.rm = T)/min(x, na.rm = T))
  return(ratios)
}
relative_contrast <- function(data) {
  tmp <- as.matrix(dist(t(data)))
  diag(tmp) <- NA
  rc <- apply(tmp, 1, function(x) abs(max(x, na.rm = T)-min(x, na.rm = T))/min(x, na.rm = T))
  return(mean(rc))
}
```

```{r look at original matrix with 10k HVG}
data <- pblapply(X=data_in, FUN=function(x) read.table( file=x)) 
data <- pblapply(data, function(x) return(x[grep("^ENS",rownames(x)),])) # 57760 x 1213
data <- pblapply(data, function(x) {rownames(x) <- gsub("\\..*","",rownames(x)); return(x)})
# Sparsity
dropout <- sapply(data,function(x) zero_percent(x)) # 46%, 49%, 55%, 60%, 66%, 72%, 86%, 88%, 92%, 94%, 97%
# Replace with genes names, remove duplicates
genes <- ensembldb::select(EnsDb.Hsapiens.v79, keys=rownames(data[[1]]), keytype = "GENEID", columns = c("SYMBOL"))$SYMBOL
duplicates <- duplicated(genes)
data <- pblapply(data, function(x) {x <- x[!duplicates,];
                                    rownames(x) <- unique(genes);
                                    return(x)}) # 56029 x 1213
# Keep 10k HVG
data <- pblapply(data, function(x) {hvg <- names(sort(apply(x,1,var), decreasing = T)[1:1e4]); return(x[hvg,])})

# make the distance heatmap
#pairwise_dist <- pblapply(data, function(x) dist(t(x)))
#pairwise_dist_norm <- pblapply(pairwise_dist, function(x) x/max(x))
#pblapply(pairwise_dist_norm, dist_heatmap)

# look at relative contrast
rc <- pbsapply(data,relative_contrast)
n_cell <- ncol(data[[1]])
rc <- data.frame("Relative_contrast"=as.vector(rc),
                 "Dropout_rate"=dropout_percent,
                 "Dimension"=n_cell)
ggplot(rc, aes(y=Relative_contrast, x=factor(Dropout_rate))) +
  geom_point()
```

```{r look at PCA matrix}
dim_val = c(2,5,10,50,100,500,1000)
data_pca <- pblapply(X=data_out, FUN=function(x) read.table(file=x))
#pca <- pblapply(data_pca, function(x) return(x[1:nPC,]))
# make the distance heatmap
#pairwise_dist_pca <- pblapply(pca, function(x) dist(t(x)))
#pairwise_dist_norm_pca <- pblapply(pairwise_dist_pca, function(x) x/max(x))
#pblapply(pairwise_dist_norm_pca, dist_heatmap)

# look at relative contrast
rc_pca <- pbsapply(data_pca, function(x) sapply(dim_val, function(y) relative_contrast(x[1:y,])))
n_dim <- nrow(rc_pca)
rc_pca <- data.frame("Relative_contrast"=as.vector(rc_pca),
                 "Dropout_rate"=rep(dropout_percent,each=n_dim),
                 "Dimension"=dim_val)
ggplot(rc_pca, aes(y=Relative_contrast, x=Dimension, color=(Dropout_rate))) +
  geom_point() +
  geom_line(aes(group=Dropout_rate), alpha=0.5)
```

```{r compare the low vs high dimensions}
total_rc <- rbind(rc_pca,rc)
ggplot(total_rc, aes(x=Dimension, y=Relative_contrast, color=Dropout_rate)) +
  xlab("Dimension") +
  geom_line(aes(group=Dropout_rate), alpha=0.5) +
  scale_y_log10()
```

```{r look at dropout dependence of relative contrast}
ggplot(rc_pca, aes(x=Dropout_rate, y=Relative_contrast, color=factor(Dimension))) +
  xlab("Dropout") +
  geom_point() +
  geom_line(aes(group=Dimension), alpha=0.5) +
  scale_y_log10()
```

