---
title: "PCA obj"
output: html_document
---

```{r libs & paths}
library(Seurat)
library(ggplot2)
data_in <- "/Users/elise/Desktop/Imagine_bckp/scRNAseq/Data_sc/hubness_data/10X/GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv"
data_out <- "/Users/elise/Desktop/Imagine_bckp/scRNAseq/Data_sc/hubness_data/10X/GSE100866_pca_readyforhubness.csv"
```

```{r do PCA}
data <- read.csv(data_in, header = T, row.names = 1)
# 23370 x 9055 for Guo
# 36280 x 8617 for https://satijalab.org/seurat/v3.1/multimodal_vignette.html
# For satija data, remove mouse genes
data <- data[grep("HUMAN_",rownames(data)),] # 20400 genes
seurat <- CreateSeuratObject(data)
seurat[["percent.mt"]] <- PercentageFeatureSet(seurat, pattern = "^MT-")
VlnPlot(seurat, features = c("nFeature_RNA","nCount_RNA","percent.mt"))
FeatureScatter(seurat, feature1 = "nFeature_RNA", feature2 = "nCount_RNA") + 
  geom_vline(xintercept=4000) +
  geom_hline(yintercept=15000)
# Remove cells with more than 4000 genes or 15e+03 total counts for Guo
seurat <- subset(seurat, subset = nFeature_RNA<4000 & nCount_RNA<15e+03)
# 9048 cells for Guo
# 8604 cells for Satija
# Normalize + log transfo + scale
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat)
data <- GetAssayData(seurat)
rm(seurat)
# PCA
pca <- prcomp(data)
data_proj <- t(pca$rotation)
# 9048 PCs x 9048 cells for Guo
# 8604 PCs x 8604 cells for Satija
write.table(data_proj, file=data_out)
```
