---
title: "hub-based network building -Satija"
output: html_document
---

```{r load data, include = FALSE}
#source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_Guo.R")
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_Satija.R")
hubness$cellID <- names(hubness_scores_data[[1]][[1]])

#source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_Guo.R")
#source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_Satija.R")

source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_functions.R")
path_neighbors <- "/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hub_network/neighbors_satija.rds"
path_neighbors_pca <- "/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hub_network/neighbors_pca_satija.rds"
```

```{r get neighbors}
k_max=100
d=100
#neighbors <- findKNN(t(data), k_max)
#saveRDS(neighbors,file=path_neighbors)
#neighbors_pca <- findKNN(t(data_pca[1:d,]), k_max)
#saveRDS(neighbors_pca,file=path_neighbors_pca)
neighbors <- readRDS(path_neighbors)
neighbors_pca <- readRDS(path_neighbors_pca)
neighbor_list <- neighbors$index
neighbor_pca_list <- neighbors_pca$index
rownames(neighbor_list) <- names(hubness_scores_data[[1]][[1]])
rownames(neighbor_pca_list) <- names(hubness_scores_data[[1]][[1]])
```

```{r get hub scores, include=FALSE}
hub_scores <- hubness$score[hubness$Dimension==(cell_nb-1) & hubness$p==2 & hubness$k==50]
names(hub_scores) <- names(hubness_scores_data[[1]][[1]])
```

```{r get all the data fixing the nb of hubs but increasing the neighborhood size}
coverage_hub(neighbor_list, hub_scores, 1000)
coverage_hub(neighbor_pca_list, hub_scores, 1000)
```

```{r get all the data fixing the neighborhood size but increasing the nb of hubs}
k=100
coverage_k(neighbor_list, hub_scores, k)
coverage_k(neighbor_pca_list, hub_scores, k)
```

```{r reverse get all the data fixing the nb of hubs but increasing the neighborhood size}
reverse_coverage_hub(neighbor_list, hub_scores, 500)
reverse_coverage_hub(neighbor_pca_list, hub_scores, 500)
```

```{r reverse get all the data fixing the neighborhood size but increasing the nb of hubs}
k=100
reverse_coverage_k(neighbor_list, hub_scores, k)
reverse_coverage_k(neighbor_pca_list, hub_scores, k)
```

