---
title: "Gaussian blobs"
output: html_document
---

```{r libs}
library(knn.covertree)
library(pbapply)
library(ggplot2)
library(circlize)
library(ComplexHeatmap)
library(ggpubr)
library(umap)
```

```{r functions}
get_hub_scores <- function(data,k) {
  knn_graph <- knn.covertree::find_knn(t(data),k)
  knn_list <- knn_graph$index
  occurence <- sapply(1:nrow(knn_list), function(x) {sum(knn_list==x)})
  return(occurence)
}
asymmetry_evaluation <- function(data) {
  knn_graph <- knn.covertree::find_knn(t(data),k)
  knn_list <- knn_graph$index
  increment = 0
  for (i in 1:nrow(knn_list)) {
    for (j in 1:ncol(knn_list)) {
      if (i %in% knn_list[knn_list[i,j],]) {
        increment <- increment + 1 
      }
    }
  }
  return(1-increment/(nrow(knn_list)*ncol(knn_list)))
}
skewness <- function(distrib) {
  return(mean((distrib-mean(distrib))^3)/(sd(distrib)^3))
}
antihub <- function(distrib) {
  return(sum(distrib==0))
}
k_thd <- function(distrib,k) {
  return(sum(distrib>=2*k))
} 
meansd_thd <- function(distrib) {
  thd <- mean(distrib) + 3*sd(distrib)
  return(sum(distrib>=thd))
}
generate_gaussian <- function(n,dim,centers,sds) { # make a gaussian blob in dimension dim
  return(t(sapply(1:dim, function(x) rnorm(n,centers[x],sds[x]))))
}
generate_uniform <- function(n,dim) {
  return(t(sapply(1:dim, function(x) runif(n,min=(-1)))))
}
kthd_hub_number <- function(score,k) {
  return(sum(score>(2*k)))
}
```

```{r create distribution}
N = 1000
n = 500
tested_dim = c(2,5,10,20,30,40,50,100)
tested_clusters = 1:10
centers = lapply(tested_dim,
                 function(x) sapply(1:max(tested_clusters),
                                    function(y) sample(c(-5:5),x,replace=T)))
centers_spaced = lapply(tested_dim,
                        function(x) {tmp <- matrix(1, nrow=x, ncol=max(tested_clusters));
                        tmp[1,] <- 1:max(tested_clusters);
                        return(tmp)})
sds=sample(c(0.1,0.2,0.3,0.5),max(tested_dim),replace = T)
sds_small=rep(0.1,max(tested_dim))
sds_large=rep(5,max(tested_dim))
sds_spaced=lapply(seq(0.1,5,by=0.2),
                  function(y) rep(y,each=max(tested_dim)))
distrib_gaussian1 <- pblapply(tested_clusters, # dataset of same size, centers and sds random
                             function(z) {lapply(1:length(tested_dim),
                                                 function(y) {tmp<-lapply(1:z,
                                                                          function(x) generate_gaussian(N/z,tested_dim[y],centers[[y]][,x],sds[1:tested_dim[y]]));do.call(cbind,tmp)})})
distrib_gaussian2 <- pblapply(tested_clusters, # dataset of same size, centers rdm and sds small
                             function(z) {lapply(1:length(tested_dim),
                                                 function(y) {tmp<-lapply(1:z,
                                                                          function(x) generate_gaussian(N/z,tested_dim[y],centers[[y]][,x],sds_small[1:tested_dim[y]]));do.call(cbind,tmp)})})
distrib_gaussian3 <- pblapply(tested_clusters, # dataset of same size, centers random and sds large
                             function(z) {lapply(1:length(tested_dim),
                                                 function(y) {tmp<-lapply(1:z,
                                                                          function(x) generate_gaussian(N/z,tested_dim[y],centers[[y]][,x],sds_large[1:tested_dim[y]]));do.call(cbind,tmp)})})
distrib_gaussian4 <- pblapply(tested_clusters, # clusters of same size, centers and sds random
                             function(z) {lapply(1:length(tested_dim),
                                                 function(y) {tmp<-lapply(1:z,
                                                                          function(x) generate_gaussian(n,tested_dim[y],centers[[y]][,x],sds[1:tested_dim[y]]));do.call(cbind,tmp)})})
distrib_gaussian5 <- pblapply(tested_clusters, # clusters of same size, centers random and sds small
                             function(z) {lapply(1:length(tested_dim),
                                                 function(y) {tmp<-lapply(1:z,
                                                                          function(x) generate_gaussian(n,tested_dim[y],centers[[y]][,x],sds_small[1:tested_dim[y]]));do.call(cbind,tmp)})})
distrib_gaussian6 <- pblapply(tested_clusters, # clusters of same size, centers random and sds large
                             function(z) {lapply(1:length(tested_dim),
                                                 function(y) {tmp<-lapply(1:z,
                                                                          function(x) generate_gaussian(n,tested_dim[y],centers[[y]][,x],sds_large[1:tested_dim[y]]));do.call(cbind,tmp)})})

distrib_gaussian_spaced <- pblapply(1:length(sds_spaced), # 10 clusters of same size, centers lin spaced and various sds
                                    function(z) {lapply(1:length(tested_dim),
                                                 function(y) {tmp<-lapply(1:10,
                                                                          function(x) generate_gaussian(n,tested_dim[y],centers_spaced[[y]][,x],sds_spaced[[z]][1:tested_dim[y]]));do.call(cbind,tmp)})})

distrib_gaussian <- list(distrib_gaussian1,distrib_gaussian2,distrib_gaussian3,
                         distrib_gaussian4,distrib_gaussian5,distrib_gaussian6)

distrib_uniform <- lapply(tested_dim, function(x) generate_uniform(N,x))
```

```{r viz}
pca <- pblapply(distrib_gaussian,
                function(y) lapply(y,
                                   function(z) lapply(z,
                                                      function(x) prcomp(x, center=F))))
pca_spaced <- pblapply(distrib_gaussian_spaced,
                       function(y) lapply(y,
                                          function(z) prcomp(z, center=F)))
pca_uniform <- pblapply(distrib_uniform,
                        function(x) prcomp(x, center=F))
#umap <- pblapply(pca,
#                 function(y) lapply(y,
#                                    function(z) lapply(z[4:length(z)],
#                                                       function(x) umap(x$rotation[,1:20]))))
#umap_spaced <- pblapply(pca_spaced,
#                        function(z) lapply(z[4:length(z)],
#                                           function(x) umap(x$rotation[,1:20])))
#umap_uniform <- pblapply(pca_uniform[4:length(distrib_uniform)],
#                         function(x) umap(x$rotation[,1:20]))
# check 2 clusters in low and high dimensions
opt=1:6
lapply(opt,
       function(x) lapply(c(2,10),
                          function(clust) lapply(c(4,8),
                                                 function(dim)
                                                   plot(pca[[x]][[clust]][[dim]]$rotation[,1],
                                                        pca[[x]][[clust]][[dim]]$rotation[,2]))))
#lapply(opt,
#       function(x) lapply(c(2,10),
#                          function(clust) lapply(c(1,4),
#                                                 function(dim)
#                                                   plot(umap[[x]][[clust]][[dim]]$layout[,1],
#                                                        umap[[x]][[clust]][[dim]]$layout[,2]))))
# check 3 sds in low and high dimensions
lapply(c(1,10,20),
       function(sds) lapply(c(4,8),
                            function(dim) plot(pca_spaced[[sds]][[dim]]$rotation[,1],
                                               pca_spaced[[sds]][[dim]]$rotation[,2])))
#lapply(c(1,10,20),
#       function(sds) lapply(c(1,4),
#                            function(dim) plot(umap_spaced[[sds]][[dim]]$layout[,1],
#                                               umap_spaced[[sds]][[dim]]$layout[,2])))
```

```{r check clusters}
#labels <- lapply(tested_clusters,
#                 function(x) rep(1:x, each=N/x))
#kmeans <- lapply(1:length(pca_spaced),
#                 function(x) kmeans(t(t(pca_spaced[[x]][[6]]$rotation[,1:5])),10)$cluster)
#library(mclust)
#ari <- sapply(1:length(kmeans),
#              function(x) adjustedRandIndex(kmeans[[x]],labels[[x]]))
```

```{r get hub scores}
k=50
scores_gaussian <- pblapply(distrib_gaussian,
                            function(y) lapply(y,
                                               function(x) lapply(x,
                                                                  function(z) get_hub_scores(z,k))))
scores_gaussian_spaced <- pblapply(distrib_gaussian_spaced,
                            function(x) lapply(x,
                                               function(z) get_hub_scores(z,k)))
scores_uniform <- pblapply(distrib_uniform,
                           function(x) get_hub_scores(x,k))
```

```{r look at the distrib}
#lapply(scores_gaussian, function(x) lapply(x,hist))
# Having more clusters -> less skewness ?
```

```{r look at the parameters as a function of dim}
Skewness <- data.frame("Skewness"=as.vector(sapply(scores_gaussian,
                                           function(y) sapply(y,
                                                              function(x) sapply(x,
                                                                                 function(z) skewness(z))))),
                       "Distribution"=rep(paste0("Gaussian",tested_clusters), each=length(tested_dim)),
                       "Dimension"=tested_dim,
                       "Option"=rep(1:6,each=length(tested_dim)*length(tested_clusters)))
Antihub <- data.frame("Antihub"=as.vector(sapply(scores_gaussian,
                                           function(y) sapply(y,
                                                              function(x) sapply(x,
                                                                                 function(z) antihub(z))))),
                      "Distribution"=rep(paste0("Gaussian",tested_clusters), each=length(tested_dim)),
                      "Dimension"=tested_dim,
                       "Option"=rep(1:6,each=length(tested_dim)*length(tested_clusters)))
KThd <- data.frame("KThd"=as.vector(sapply(scores_gaussian,
                                           function(y) sapply(y,
                                                              function(x) sapply(x,
                                                                                 function(z) k_thd(z,k))))),
                   "Distribution"=rep(paste0("Gaussian",tested_clusters), each=length(tested_dim)),
                   "Dimension"=tested_dim,
                       "Option"=rep(1:6,each=length(tested_dim)*length(tested_clusters)))
MeanSdThd <- data.frame("MeanSdThd"=as.vector(sapply(scores_gaussian,
                                           function(y) sapply(y,
                                                              function(x) sapply(x,
                                                                                 function(z) meansd_thd(z))))),
                        "Distribution"=rep(paste0("Gaussian",tested_clusters), each=length(tested_dim)),
                        "Dimension"=tested_dim,
                       "Option"=rep(1:6,each=length(tested_dim)*length(tested_clusters)))
Asymmetry <- data.frame("Asymmetry"=as.vector(pbsapply(distrib_gaussian,
                                           function(y) sapply(y,
                                                              function(x) sapply(x, asymmetry_evaluation)))),
                        "Distribution"=rep(paste0("Gaussian",tested_clusters), each=length(tested_dim)),
                        "Dimension"=tested_dim,
                       "Option"=rep(1:6,each=length(tested_dim)*length(tested_clusters)))
p1<-lapply(1:length(distrib_gaussian),
                   function(x) {ggplot(Skewness[Skewness$Option==x,], aes(x=Dimension, y=Skewness)) +
                       geom_line(aes(group=Distribution)) +
                       geom_point(aes(color=Distribution))})
ggarrange(plotlist=p1, common.legend = T)
p2<-lapply(1:length(distrib_gaussian),
                   function(x) {ggplot(Asymmetry[Asymmetry$Option==x,], aes(x=Dimension, y=Asymmetry)) +
                       geom_line(aes(group=Distribution)) +
                       geom_point(aes(color=Distribution))})
ggarrange(plotlist=p2, common.legend = T)
p3<-lapply(1:length(distrib_gaussian),
                   function(x) {ggplot(Antihub[Antihub$Option==x,], aes(x=Dimension, y=Antihub)) +
                       geom_line(aes(group=Distribution)) +
                       geom_point(aes(color=Distribution))})
ggarrange(plotlist=p3, common.legend = T)
p4<-lapply(1:length(distrib_gaussian),
                   function(x) {ggplot(KThd[KThd$Option==x,], aes(x=Dimension, y=KThd)) +
                       geom_line(aes(group=Distribution)) +
                       geom_point(aes(color=Distribution))})
ggarrange(plotlist=p4, common.legend = T)
p5<-lapply(1:length(distrib_gaussian),
                   function(x) {ggplot(MeanSdThd[MeanSdThd$Option==x,], aes(x=Dimension, y=MeanSdThd)) +
                       geom_line(aes(group=Distribution)) +
                       geom_point(aes(color=Distribution))})
ggarrange(plotlist=p5, common.legend = T)

link_df <- data.frame("Asymmetry"=Asymmetry$Asymmetry,
                      "Antihub"=Antihub$Antihub,
                      "KThd"=KThd$KThd,
                      "MeanSdThd"=MeanSdThd$MeanSdThd,
                      "Skewness"=Skewness$Skewness,
                      "Dimension"=tested_dim,
                      "Distribution"=rep(paste0("Gaussian",tested_clusters), each=length(tested_dim)),
                      "Cluster_nb"=rep(tested_clusters, each=length(tested_dim)),
                      "Option"=Skewness$Option)

p1=lapply(1:6,
          function(x) ggplot(link_df[link_df$Option==x,], aes(x=Asymmetry, y=Skewness, color=Distribution, alpha=Dimension)) +
  geom_point())
p2=lapply(1:6,
          function(x) ggplot(link_df[link_df$Option==x,], aes(x=Asymmetry, y=Antihub, color=Distribution, alpha=Dimension)) +
  geom_point())
p3=lapply(1:6,
          function(x) ggplot(link_df[link_df$Option==x,], aes(x=Asymmetry, y=KThd, color=Distribution, alpha=Dimension)) +
  geom_point())
p4=lapply(1:6,
          function(x) ggplot(link_df[link_df$Option==x,], aes(x=Asymmetry, y=MeanSdThd, color=Distribution, alpha=Dimension)) +
  geom_point())
ggarrange(plotlist=p1,common.legend = T)
ggarrange(plotlist=p2,common.legend = T)
ggarrange(plotlist=p3,common.legend = T)
ggarrange(plotlist=p4,common.legend = T)
lapply(1:6,
       function(x) ggplot(link_df[link_df$Option==x,], aes(x=Cluster_nb, y=Asymmetry, color=Dimension)) + geom_point() + scale_color_viridis_c() + geom_line(aes(group=Dimension)))
lapply(1:6,
       function(x) ggplot(link_df[link_df$Option==x,], aes(x=Cluster_nb, y=Skewness, color=Dimension)) + geom_point() + scale_color_viridis_c() + geom_line(aes(group=Dimension)))

link_df$Distribution<-factor(link_df$Distribution, levels=paste0("Gaussian",1:10))
x=6
p1<-ggplot(link_df[link_df$Option==x,], aes(x=Distribution, y=Asymmetry, color=factor(Dimension))) +
  geom_point() +
  geom_line(aes(group=Dimension)) +
  theme(axis.text.x = element_text(angle = 90))
p2<-ggplot(link_df[link_df$Option==x,], aes(x=Distribution, y=Antihub, color=factor(Dimension))) +
  geom_point() +
  geom_line(aes(group=Dimension)) +
  theme(axis.text.x = element_text(angle = 90))
p3<-ggplot(link_df[link_df$Option==x,], aes(x=Distribution, y=KThd, color=factor(Dimension))) +
  geom_point() +
  geom_line(aes(group=Dimension)) +
  theme(axis.text.x = element_text(angle = 90))
p4<-ggplot(link_df[link_df$Option==x,], aes(x=Distribution, y=MeanSdThd, color=factor(Dimension))) +
  geom_point() +
  geom_line(aes(group=Dimension)) +
  theme(axis.text.x = element_text(angle = 90))
p5<-ggplot(link_df[link_df$Option==x,], aes(x=Distribution, y=Skewness, color=factor(Dimension))) +
  geom_point() +
  geom_line(aes(group=Dimension)) +
  theme(axis.text.x = element_text(angle = 90))
ggarrange(p1,p3,p4,p5, common.legend = T)
```

```{r look at the parameters as a function of dim - spaced}
Skewness <- data.frame("Skewness"=as.vector(sapply(scores_gaussian_spaced,
                                                   function(x) sapply(x,
                                                              function(z) skewness(z)))),
                       "Distribution"=rep(paste0("Sd",unique(unlist(sds_spaced))), each=length(tested_dim)),
                       "Dimension"=tested_dim)
Antihub <- data.frame("Antihub"=as.vector(sapply(scores_gaussian_spaced,
                                                 function(x) sapply(x,
                                                                    function(z) antihub(z)))),
                      "Distribution"=rep(paste0("Sd",unique(unlist(sds_spaced))), each=length(tested_dim)),
                      "Dimension"=tested_dim)
KThd <- data.frame("KThd"=as.vector(sapply(scores_gaussian_spaced,
                                           function(x) sapply(x,
                                                              function(z) k_thd(z,k)))),
                   "Distribution"=rep(paste0("Sd",unique(unlist(sds_spaced))), each=length(tested_dim)),
                   "Dimension"=tested_dim)
MeanSdThd <- data.frame("MeanSdThd"=as.vector(sapply(scores_gaussian_spaced,
                                                   function(x) sapply(x,
                                                              function(z) meansd_thd(z)))),
                       "Distribution"=rep(paste0("Sd",unique(unlist(sds_spaced))), each=length(tested_dim)),
                       "Dimension"=tested_dim)
Asymmetry <- data.frame("Asymmetry"=as.vector(pbsapply(distrib_gaussian_spaced,
                                           function(x) sapply(x, asymmetry_evaluation))),
                        "Distribution"=rep(paste0("Sd",unique(unlist(sds_spaced))), each=length(tested_dim)),
                        "Dimension"=tested_dim)
ggplot(Skewness, aes(x=Dimension, y=Skewness)) +
  geom_line(aes(group=Distribution)) +
  geom_point(aes(color=Distribution))
ggplot(Antihub, aes(x=Dimension, y=Antihub)) +
  geom_line(aes(group=Distribution)) +
  geom_point(aes(color=Distribution))
ggplot(Asymmetry, aes(x=Dimension, y=Asymmetry)) +
  geom_line(aes(group=Distribution)) +
  geom_point(aes(color=Distribution))
ggplot(KThd, aes(x=Dimension, y=KThd)) +
  geom_line(aes(group=Distribution)) +
  geom_point(aes(color=Distribution))
ggplot(MeanSdThd, aes(x=Dimension, y=MeanSdThd)) +
  geom_line(aes(group=Distribution)) +
  geom_point(aes(color=Distribution))

link_df_spaced <- data.frame("Asymmetry"=Asymmetry$Asymmetry,
                             "Antihub"=Antihub$Antihub,
                             "KThd"=KThd$KThd,
                             "MeanSdThd"=MeanSdThd$MeanSdThd,
                             "Skewness"=Skewness$Skewness,
                             "Dimension"=tested_dim,
                             "Distribution"=Skewness$Distribution)
p1<-ggplot(link_df_spaced, aes(x=Distribution, y=Asymmetry, color=factor(Dimension))) +
  geom_point() +
  geom_line(aes(group=Dimension)) +
  theme(axis.text.x = element_text(angle = 90))
p2<-ggplot(link_df_spaced, aes(x=Distribution, y=Antihub, color=factor(Dimension))) +
  geom_point() +
  geom_line(aes(group=Dimension)) +
  theme(axis.text.x = element_text(angle = 90))
p3<-ggplot(link_df_spaced, aes(x=Distribution, y=KThd, color=factor(Dimension))) +
  geom_point() +
  geom_line(aes(group=Dimension)) +
  theme(axis.text.x = element_text(angle = 90))
p4<-ggplot(link_df_spaced, aes(x=Distribution, y=MeanSdThd, color=factor(Dimension))) +
  geom_point() +
  geom_line(aes(group=Dimension)) +
  theme(axis.text.x = element_text(angle = 90))
p5<-ggplot(link_df_spaced, aes(x=Distribution, y=Skewness, color=factor(Dimension))) +
  geom_point() +
  geom_line(aes(group=Dimension)) +
  theme(axis.text.x = element_text(angle = 90))
ggarrange(p1,p3,p4,p5, common.legend = T)
```

```{r retrieve hubs}
# using KThd method
D <- 50
hub_nb <- sapply(scores_gaussian,
                 function(x) sapply(x,
                                    function(y) kthd_hub_number(y[[which(tested_dim==D)]],k))/N*100)
cluster_nb <- tested_clusters
df <- data.frame("Cluster_nb"=as.vector(cluster_nb),
                 "Hub_nb"=as.numeric(hub_nb))
ggplot(df, aes(x=Cluster_nb,y=Hub_nb)) + geom_point() + ylab("Hub number (%)")
```

