---
title: "Entropy -Satija"
output:
  html_document: default
  pdf_document: default
---
Method 2 : mu + 3sigma (k=200)
Method 6 : anti hubs
Method 7 : MAD (k=200)

```{r load data, include = FALSE}
#source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_Guo.R")
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_Satija.R")
#source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_Guo.R")
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_Satija.R")

source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_functions.R")
```

```{r get the hubs with the different methods, include = FALSE}
parameter <- data.frame(200,100,2)
names(parameter) <- c("k","pc","p")
val <- hubness$score[hubness$k==parameter$k & hubness$Dimension==parameter$pc & hubness$p==parameter$p]
thd2 <- get_hub2(hubness,kval=parameter$k,pcval=parameter$pc,pval=parameter$p)$Threshold
hub2 <- colnames(data)[val>=thd2]
hub6 <- colnames(data)[val==0]
thd7 <- get_hub7(hubness,kval=parameter$k,pcval=parameter$pc,pval=parameter$p)$Threshold
hub7 <- colnames(data)[val>=thd7]
```

```{r measure stemID entropy, include = FALSE}
sc <- SCseq(data)
sc@ndata <- data
ltr <- Ltree(sc)
ltr <- compentropy(ltr)
stemID <- ltr@entropy
rm(sc,ltr)
```

```{r prep Seurat, include = FALSE}
seurat <- CreateSeuratObject(data)
seurat$hub2 <- c("normal","hub")[factor(colnames(seurat) %in% hub2, levels = c("FALSE","TRUE"))]
seurat$hub6 <- c("normal","antihub")[factor(colnames(seurat) %in% hub6, levels = c("FALSE","TRUE"))]
seurat$hub7 <- c("normal","hub")[factor(colnames(seurat) %in% hub7, levels = c("FALSE","TRUE"))]
seurat$scentropy <- entropy
seurat$stemID <- stemID
seurat[["percent.mt"]] <- PercentageFeatureSet(seurat, pattern = "^MT-")
# Normalize + log transfo + scale
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat)
seurat <- FindVariableFeatures(seurat)
seurat <- RunPCA(seurat, verbose = F)
seurat <- RunUMAP(seurat, dims = 1:50)
seurat <- RunTSNE(seurat, dims = 1:50)
```

```{r scentropy}
FeaturePlot(seurat, reduction = "umap", features = "scentropy")
ggarrange(vlnplot_hub_spec(seurat, "scentropy", "hub2",2.6,3.6,3.5),
          vlnplot_hub_spec(seurat, "scentropy", "hub6",2.6,3.6,3.5),
          vlnplot_hub_spec(seurat, "scentropy", "hub7",2.6,3.6,3.5))
```

```{r stemID}
FeaturePlot(seurat, reduction = "umap", features = "stemID")
ggarrange(vlnplot_hub_spec(seurat, "stemID", "hub2",0.1,0.95,0.85),
          vlnplot_hub_spec(seurat, "stemID", "hub6",0.1,0.95,0.85),
          vlnplot_hub_spec(seurat, "stemID", "hub7",0.1,0.95,0.85))
```
