---
title: "Reverse coverage-based hub definition2 -BRCA"
output: html_document
---

```{r load data, include = FALSE}
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_BRCA.R")
hubness$cellID <- names(hubness_scores_data[[1]][[1]])

source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_BRCA.R")

source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_functions.R")
path_neighbors <- "/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hub_network/neighbors_BRCA.rds"
path_neighbors_pca <- "/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hub_network/neighbors_pca_BRCA.rds"
path_hub <- "/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hubness_def/rev_cov_plateau/hubs_BRCA.rds"
```

```{r get hub scores, include=FALSE}
hub_scores <- hubness$score[hubness$Dimension==(cell_nb-1) & hubness$p==2 & hubness$k==50]
names(hub_scores) <- names(hubness_scores_data[[1]][[1]])
```

```{r get neighbors}
k_max=100
d=100
#neighbors <- findKNN(t(data), k_max)
#saveRDS(neighbors,file=path_neighbors)
#neighbors_pca <- findKNN(t(data_pca[1:50,]), k_max)
#saveRDS(neighbors_pca,file=path_neighbors_pca)
neighbors <- readRDS(path_neighbors)
neighbors_pca <- readRDS(path_neighbors_pca)
neighbor_list <- neighbors$index
neighbor_pca_list <- neighbors_pca$index
rownames(neighbor_list) <- names(hubness_scores_data[[1]][[1]])
rownames(neighbor_pca_list) <- names(hubness_scores_data[[1]][[1]])
```

```{r reverse get all the data fixing the neighborhood size but increasing the nb of hubs}
k=min(100,round(ncol(data/20)))
h1<-reverse_coverage_percent_k(neighbor_list, hub_scores, k, 2, cell_nb, percent=70)
h2<-reverse_coverage_k(neighbor_pca_list, hub_scores, k, 2, cell_nb)
```

```{r extract the indexes of hubs}
h1==h2
print(paste0("We have selected ",h1," hubs"))
hubs <- names(sort(hub_scores, decreasing = T)[1:h1])
saveRDS(hubs, file=path_hub)
```