---
title: "PCA obj"
output: html_document
---

```{r libs & paths}
library(Seurat)
data_in <- "/home/Storage/scRNAseq/Data_sc/hubness_data/GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv"
data_out <- "/home/Storage/scRNAseq/Data_sc/hubness_data/GSE100866_pca_readyforhubness.csv"
```

```{r do PCA}
data <- read.table(data_in)
# 23370 x 9055 for Guo
# For satija data, remove mouse genes
data <- data[-grep("MOUSE_",rownames(data)),]
seurat <- CreateSeuratObject(data)
seurat[["percent.mt"]] <- PercentageFeatureSet(seurat, pattern = "^MT-")
VlnPlot(seurat, features = c("nFeature_RNA","nCount_RNA","percent.mt"))
FeatureScatter(seurat, feature1 = "nFeature_RNA", feature2 = "nCount_RNA")
# Remove cells with more than 7500 genes or 5e+06 total counts for Guo
seurat <- subset(seurat, subset = nFeature_RNA<7500 & nCount_RNA<5e+06)
# 9048 cells for Guo
# Normalize + log transfo + scale
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat)
data <- GetAssayData(seurat)
# PCA
pca <- prcomp(data)
data_proj <- t(pca$rotation)
# 9048 PCs x 9048 cells for Guo
write.table(data_proj, file=data_out)
```
