---
title: "PCA obj"
output: html_document
---

```{r libs & paths}
library(Seurat)
library(ggplot2)
library(dplyr)
library(pbapply)
data_in1 <- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Andrei_Ewing/3_normalized_pooled/pdx184_nufp.txt"
data_in2 <- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Andrei_Ewing/3_normalized_pooled/pdx352_nufp.txt"
data_in3 <- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Andrei_Ewing/3_normalized_pooled/pdx471_nufp.txt"
data_in4 <- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Andrei_Ewing/3_normalized_pooled/pdx856_nufp.txt"
data_in5 <- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Andrei_Ewing/3_normalized_pooled/pdx857_nufp.txt"
data_in6 <- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Andrei_Ewing/3_normalized_pooled/pdx861_nufp.txt"
data_in7 <- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Andrei_Ewing/3_normalized_pooled/pdx1057_nufp.txt"
data_in8 <- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Andrei_Ewing/3_normalized_pooled/pdx1058_nufp.txt"
data_out <- "/Users/elise/Desktop/GitHub/Hubness_sc/data/Ewing_PDX_normalized/pdx3_pca_readyforhubness.txt"
out <- "/Users/elise/Desktop/GitHub/Hubness_sc/data/Ewing_PDX_normalized/pdx3_merged.txt"
sdev_out <- "/Users/elise/Desktop/GitHub/Hubness_sc/data/Ewing_PDX_normalized/pdx3_pca_sdev.txt"
```

```{r functions}
load_pdx <- function(path) {
  data <- read.table(path, header = T)
  data <- data[!is.na(data[,1]),]
  data <- data[!duplicated(data[,1]),]
  rownames(data) <- data[,1]
  data <- data[,-1]
  data <- data[!apply(data,1,function(x) any(is.na(x))),]
  count <- apply(data,1,function(x) sum(x!=0, na.rm = T))
  return(data[count>2,])
}
filter1 <- function(df) {
  feature <- apply(df,2,function(x) sum(x!=0, na.rm = T))
  count <- apply(df,2,function(x) sum(x, na.rm=T))
  print(plot(feature,count))
}
```

```{r do PCA}
data1 <- load_pdx(data_in1)
data2 <- load_pdx(data_in2)
data3 <- load_pdx(data_in3)
data4 <- load_pdx(data_in4)
data5 <- load_pdx(data_in5)
data6 <- load_pdx(data_in6)
data7 <- load_pdx(data_in7)
data8 <- load_pdx(data_in8)
data <- list(data1,data2,data3,data4,data5,data6,data7,data8)
pblapply(data,filter1)
genes <- intersect(intersect(intersect(intersect(intersect(intersect(intersect(rownames(data1),rownames(data2)),
                                                                     rownames(data3)),
                                                           rownames(data4)),
                                                 rownames(data5)),
                                       rownames(data6)),
                             rownames(data7)),
                   rownames(data8))
data <- pblapply(data,function(x) {x[genes,]}) #11857 genes (slightly more than PDX1 11288)
rm(genes)
# Pool
pooled_df <- cbind(cbind(cbind(cbind(cbind(cbind(cbind(data[[1]],data[[2]]),
                                            data[[3]]),
                                      data[[4]]),
                                data[[5]]),
                          data[[6]]),
                    data[[7]]),
              data[[8]])
# Normalize + log transfo + scale
Seurat <- CreateSeuratObject(pooled_df)
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat)
pooled_df <- GetAssayData(seurat)
rm(seurat)
# PCA
pca <- prcomp(pooled_df)
data_proj <- t(pca$rotation)
# 2000 PCs
write.table(pooled_df, file=out) # 11857 x 12338
write.table(data_proj, file=data_out)
write.table(pca$sdev,file=sdev_out)
```
