---
title: "PCA obj"
output: html_document
---

```{r libs & paths}
library(Seurat)
path_hub <- "/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hubness_def/rev_cov/hubs_Satija.rds"
path_data <- "/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/10x/GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv"
data_out <- "/Users/elise/Desktop/GitHub/Hubness_sc/data/Satija/revcovhub_rm/revcov_pca_readyforhubness.txt"
sdev_out <- "/Users/elise/Desktop/GitHub/Hubness_sc/data/Satija/revcovhub_rm/revcov_pca_sdev.txt"
```

```{r rm hubs}
hubs <- readRDS(path_hub)
data <- read.csv(path_data, header = T, row.names = 1)
data <- data[grep("HUMAN_",rownames(data)),] # 20400 genes
rownames(data) <- gsub("HUMAN_","",rownames(data))
nFeature <- apply(data,2,function(x) sum(x!=0))
nCount <- apply(data,2,sum)
data <- data[,nFeature<4000 & nCount<15e+03] # 8604 cells for Satija
data <- data[,!(colnames(data) %in% hubs)]
```

```{r do PCA}
seurat <- CreateSeuratObject(data)
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat)
data <- GetAssayData(seurat)
rm(seurat)
# PCA
pca <- prcomp(data)
data_proj <- t(pca$rotation)
# 8504 PCs
write.table(data_proj, file=data_out)
write.table(pca$sdev,file=sdev_out)
```
