---
title: "Bulk with varying degrees of dropout"
output: html_document
---

```{r load data, include = FALSE}
library(pbapply)
data <- t(read.csv("/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/data.csv",header=T, row.names = 1))
#source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/load_counts_BRCA.R")
#rm(path_neighbors,path_neighbors_pca,data_pca)
```

```{r functions, include=FALSE}
generate_dropout <- function(data, dropout_percent) {
  n_elements <- ncol(data)*nrow(data)
  zeros <- sample(1:n_elements, length(1:n_elements)*dropout_percent/100)
  simul_data <- data
  idx_row <- ceiling(zeros/ncol(data))
  idx_col <- zeros %% ncol(data)
  idx_col <- replace(idx_col,idx_col==0,ncol(data))
  simul_data[cbind(idx_row,idx_col)] <- 0
  return(simul_data)
}
zero_percent <- function(data) { # gene x cell matrix
  return(sum(data==0)/ncol(data)/nrow(data)*100)
}
```

```{r}
dropout_percent <- c(0,5,10,20,30,40,50,75,80,85,90,95)
data_simul <- pblapply(dropout_percent,function(x) generate_dropout(data,x))
dropout_simul <- sapply(data_simul,function(x) zero_percent(x))
mapply(x=data_simul, y=dropout_percent, function(x,y) write.table(x, file=paste0("/Users/elise/Desktop/GitHub/Hubness_sc/bulkRNAseq/bulk_simul",y,".csv")))
```

