---
title: "Bulk with varying degrees of dropout"
output: html_document
---

```{r load data, include = FALSE}
library(pbapply)
data_brca <- read.csv("/Users/elise/Desktop/GitHub/Hubness_sc/Data_bulk/TCGA_BRCA/brca.csv", row.names=1)
data_archs4 <- read.csv("/Users/elise/Desktop/GitHub/Hubness_sc/Data_bulk/ARCHS4/data.csv", row.names=1)
data <- list(data_brca, data_archs4)
names(data) <- c("TCGA_BRCA","ARCHS4")
```

```{r functions, include=FALSE}
generate_dropout <- function(data, dropout_percent) {
  if (dropout_percent==0) {
    return(data)
  }
  else {
  n_genes <- nrow(data)
  zeros <- sapply(seq(ncol(data)),
                  function(x) sample(seq(n_genes), n_genes*dropout_percent/100))
  simul_data <- data
  for (i in seq(ncol(data))) {
    simul_data[zeros[,i],i] <- 0
  }
  return(simul_data)
  }
}
zero_percent <- function(data) { # gene x cell matrix
  return(sum(data==0)/ncol(data)/nrow(data)*100)
}
```

```{r}
dropout_percent <- c(0,5,10,20,30,40,50,60,70,75,80,85,90,95)
data_simul <- lapply(data,
                     function(y) pblapply(dropout_percent,function(x) generate_dropout(y,x)))
sapply(data_simul,
       function(x) sapply(x,zero_percent))
mapply(x=data_simul, y=names(data_simul),
       function(x,y) pbmapply(t=x, z=dropout_percent,
                            function(t,z) write.table(t, file=paste0("/Users/elise/Desktop/GitHub/Hubness_sc/Data_bulk/", y, "/simulated/simul_dropout", z,".csv"))))
```

