---
title: "What is the difference between (anti)hubs and normal cells?"
output:
  html_document: default
  pdf_document: default
---

```{r libs, results="hide", include = FALSE}
library(ggplot2, quietly = T)
library(viridis, quietly = T)
library(ggpubr, quietly = T)
library(Seurat, quietly = T)
library(cluster, quietly = T)
```

Method 2 : mu + 3sigma (k=200)
Method 6 : anti hubs
Method 7 : MAD (k=200)

```{r functions, include = FALSE}
get_hub2 <- function(df,kval,pcval,pval) { # Using the mean + 3*sd from Tomasev
   x_thd = c()
   hub_nb = c()
   ymin = c()
   ymax = c()
   y_increment = 1
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
            val = df$score[df$Dimension==d & df$p==p & df$k==k]
            x_thd = c(x_thd, mean(val)+3*sd(val))
            hub_nb = c(hub_nb, sum(val>=(mean(val)+3*sd(val))))
            ymin = c(ymin,y_increment)
            ymax = c(ymax,y_increment+1)
         }
      }
     y_increment <- y_increment+1
   }
   hub_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=hub_nb,
                         "Threshold"=x_thd,
                         "ymin"=ymin,
                         "ymax"=ymax)
   return(hub_val)
}
get_hub6 <- function(df,kval,pcval,pval) { # anti hubs
   anti_hub = c()
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
           anti_hub = c(anti_hub,unique(df$Antihubs[df$Dimension==d & df$p==p & df$k==k]))
         }
      }
   }
   hub_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=anti_hub)
   hub_val$Dimension <- factor(hub_val$Dimension, levels = pcval)
   return(hub_val)
}
get_hub7 <- function(df,kval,pcval,pval) { # median + 3MAD
   x_thd = c()
   hub_nb = c()
   ymin = c()
   ymax = c()
   y_increment = 1
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
           val = df$score[df$Dimension==d & df$p==p & df$k==k]
           x_thd = c(x_thd, median(val)+3*mad(val,
                                              #center=ifelse(median(val)!=0,median(val),1)
                                              ))
           hub_nb = c(hub_nb, sum(val>=(median(val)+3*mad(val,
                                                          #center=ifelse(median(val)!=0,median(val),1)
                                                          ))))
           ymin = c(ymin,y_increment)
           ymax = c(ymax,y_increment+1)
         }
      }
     y_increment <- y_increment+1
   }
   hub_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=hub_nb,
                         "Threshold"=x_thd,
                         "ymin"=ymin,
                         "ymax"=ymax)
   return(hub_val)
}
plot_hub <- function(seurat,hubs,red, pt.size=1) {
   DimPlot(guo_seurat, reduction = red, cells.highlight = hubs, pt.size = pt.size, sizes.highlight = pt.size)
}
```

```{r load data, include = FALSE}
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hubness_load_write_data.R")
guo_data <- read.table("/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Guo_lung_2018/GSE99254_NSCLC.TCell.S9055.count.labeled.txt")
guo_labels <- read.table("/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Guo_lung_2018/Dataset-2019-01-22.csv",sep=";",header = T)
satija_data <- read.csv("/Users/elise/Desktop/Imagine_bckp/scRNAseq/Data_sc/hubness_data/10X/GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv", row.names = 1)
```

```{r get the hubs with the different methods, include = FALSE}
parameter <- data.frame(200,100,2)
names(parameter) <- c("k","pc","p")
val <- hubness$score[hubness$k==parameter$k & hubness$Dimension==parameter$pc & hubness$p==parameter$p]
thd2 <- get_hub2(hubness,kval=parameter$k,pcval=parameter$pc,pval=parameter$p)$Threshold
hub2 <- colnames(guo_data)[val>=thd2]
hub6 <- colnames(guo_data)[val==0]
thd7 <- get_hub7(hubness,kval=parameter$k,pcval=parameter$pc,pval=parameter$p)$Threshold
hub7 <- colnames(guo_data)[val>=thd7]
```

