---
title: "Hubness evaluation Euclidean"
output:
  pdf_document: default
  html_document: default
---

```{r libs}
library(ggplot2)
library(plotrix)
library(streamgraph)
library(ggridges)
library(hrbrthemes)
library(viridis)
library(scales)
```

```{r functions}
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/Analysis/hubness_load_write_data.R")
get_max <- function(df, dim, ymin, ymax) {
  max=data.frame("k"=c(5,10,20,50,100,200),
                 "max"=c(max(df$Hubness_score[df$k==5 & df$Dimension==dim]),
                         max(df$Hubness_score[df$k==10 & df$Dimension==dim]),
                         max(df$Hubness_score[df$k==20 & df$Dimension==dim]),
                         max(df$Hubness_score[df$k==50 & df$Dimension==dim]),
                         max(df$Hubness_score[df$k==100 & df$Dimension==dim]),
                         max(df$Hubness_score[df$k==200 & df$Dimension==dim])),
                 "ymin"=ymin,
                 "ymax"=ymax)
  return(max)
}
```

```{r viz, p=0.1}
# Viz
max_9047 <- get_max(hubness1,"9047", ymin=9, ymax=10)
max_5000 <- get_max(hubness1,"5000", ymin=8, ymax=9)
max_1000 <- get_max(hubness1,"1000", ymin=7, ymax=8)
max_500 <- get_max(hubness1,"500", ymin=6, ymax=7)
max_100 <- get_max(hubness1,"100", ymin=5, ymax=6)
max_50 <- get_max(hubness1,"50", ymin=4, ymax=5)
max_10 <- get_max(hubness1,"10", ymin=3, ymax=4)
max_5 <- get_max(hubness1,"5", ymin=2, ymax=3)
max_2 <- get_max(hubness1,"2", ymin=1, ymax=2)
max_9047_log <- get_max(hubness1_log,"9047", ymin=9, ymax=10)
max_5000_log <- get_max(hubness1_log,"5000", ymin=8, ymax=9)
max_1000_log <- get_max(hubness1_log,"1000", ymin=7, ymax=8)
max_500_log <- get_max(hubness1_log,"500", ymin=6, ymax=7)
max_100_log <- get_max(hubness1_log,"100", ymin=5, ymax=6)
max_50_log <- get_max(hubness1_log,"50", ymin=4, ymax=5)
max_10_log <- get_max(hubness1_log,"10", ymin=3, ymax=4)
max_5_log <- get_max(hubness1_log,"5", ymin=2, ymax=3)
max_2_log <- get_max(hubness1_log,"2", ymin=1, ymax=2)

ggplot(hubness1, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=0.1')
ggplot(hubness1_log, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score (log)") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047_log, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000_log, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000_log, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500_log, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100_log, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50_log, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10_log, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5_log, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2_log, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=0.1')
```

```{r test violin, p=0.1}
ggplot(hubness1, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=0.1)") +
    ylab("Hubness score") +
    theme_grey(base_size = 15)
ggplot(hubness1_log, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=0.1)") +
    ylab("Hubness score (log)") +
    theme_grey(base_size = 15)
```

```{r viz, p=0.5}
# Viz
max_9047 <- get_max(hubness2,"9047", ymin=9, ymax=10)
max_5000 <- get_max(hubness2,"5000", ymin=8, ymax=9)
max_1000 <- get_max(hubness2,"1000", ymin=7, ymax=8)
max_500 <- get_max(hubness2,"500", ymin=6, ymax=7)
max_100 <- get_max(hubness2,"100", ymin=5, ymax=6)
max_50 <- get_max(hubness2,"50", ymin=4, ymax=5)
max_10 <- get_max(hubness2,"10", ymin=3, ymax=4)
max_5 <- get_max(hubness2,"5", ymin=2, ymax=3)
max_2 <- get_max(hubness2,"2", ymin=1, ymax=2)
max_9047_log <- get_max(hubness2_log,"9047", ymin=9, ymax=10)
max_5000_log <- get_max(hubness2_log,"5000", ymin=8, ymax=9)
max_1000_log <- get_max(hubness2_log,"1000", ymin=7, ymax=8)
max_500_log <- get_max(hubness2_log,"500", ymin=6, ymax=7)
max_100_log <- get_max(hubness2_log,"100", ymin=5, ymax=6)
max_50_log <- get_max(hubness2_log,"50", ymin=4, ymax=5)
max_10_log <- get_max(hubness2_log,"10", ymin=3, ymax=4)
max_5_log <- get_max(hubness2_log,"5", ymin=2, ymax=3)
max_2_log <- get_max(hubness2_log,"2", ymin=1, ymax=2)

ggplot(hubness2, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=0.5')
ggplot(hubness2_log, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score (log)") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047_log, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000_log, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000_log, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500_log, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100_log, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50_log, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10_log, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5_log, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2_log, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=0.5')
```

```{r test violin, p=0.5 with facet wrap}
ggplot(hubness2, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=0.5)") +
    ylab("Hubness score") +
    theme_grey(base_size = 15) +
  facet_wrap( ~ k)
ggplot(hubness2_log, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=0.5)") +
    ylab("Hubness score (log)") +
    theme_grey(base_size = 15)
```

```{r viz, p=1}
# Viz
max_9047 <- get_max(hubness3,"9047", ymin=9, ymax=10)
max_5000 <- get_max(hubness3,"5000", ymin=8, ymax=9)
max_1000 <- get_max(hubness3,"1000", ymin=7, ymax=8)
max_500 <- get_max(hubness3,"500", ymin=6, ymax=7)
max_100 <- get_max(hubness3,"100", ymin=5, ymax=6)
max_50 <- get_max(hubness3,"50", ymin=4, ymax=5)
max_10 <- get_max(hubness3,"10", ymin=3, ymax=4)
max_5 <- get_max(hubness3,"5", ymin=2, ymax=3)
max_2 <- get_max(hubness3,"2", ymin=1, ymax=2)
max_9047_log <- get_max(hubness3_log,"9047", ymin=9, ymax=10)
max_5000_log <- get_max(hubness3_log,"5000", ymin=8, ymax=9)
max_1000_log <- get_max(hubness3_log,"1000", ymin=7, ymax=8)
max_500_log <- get_max(hubness3_log,"500", ymin=6, ymax=7)
max_100_log <- get_max(hubness3_log,"100", ymin=5, ymax=6)
max_50_log <- get_max(hubness3_log,"50", ymin=4, ymax=5)
max_10_log <- get_max(hubness3_log,"10", ymin=3, ymax=4)
max_5_log <- get_max(hubness3_log,"5", ymin=2, ymax=3)
max_2_log <- get_max(hubness3_log,"2", ymin=1, ymax=2)

ggplot(hubness3, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=1')
ggplot(hubness3_log, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score (log)") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047_log, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000_log, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000_log, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500_log, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100_log, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50_log, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10_log, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5_log, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2_log, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=1')
```

```{r test violin, p=1}
# Log to zoom on differences
ggplot(hubness3, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=1)") +
    ylab("Hubness score") +
    theme_grey(base_size = 15)
ggplot(hubness3_log, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=1)") +
    ylab("Hubness score (log)") +
    theme_grey(base_size = 15)
```

```{r viz, p=1.5}
# Viz
max_9047 <- get_max(hubness4,"9047", ymin=9, ymax=10)
max_5000 <- get_max(hubness4,"5000", ymin=8, ymax=9)
max_1000 <- get_max(hubness4,"1000", ymin=7, ymax=8)
max_500 <- get_max(hubness4,"500", ymin=6, ymax=7)
max_100 <- get_max(hubness4,"100", ymin=5, ymax=6)
max_50 <- get_max(hubness4,"50", ymin=4, ymax=5)
max_10 <- get_max(hubness4,"10", ymin=3, ymax=4)
max_5 <- get_max(hubness4,"5", ymin=2, ymax=3)
max_2 <- get_max(hubness4,"2", ymin=1, ymax=2)
max_9047_log <- get_max(hubness4_log,"9047", ymin=9, ymax=10)
max_5000_log <- get_max(hubness4_log,"5000", ymin=8, ymax=9)
max_1000_log <- get_max(hubness4_log,"1000", ymin=7, ymax=8)
max_500_log <- get_max(hubness4_log,"500", ymin=6, ymax=7)
max_100_log <- get_max(hubness4_log,"100", ymin=5, ymax=6)
max_50_log <- get_max(hubness4_log,"50", ymin=4, ymax=5)
max_10_log <- get_max(hubness4_log,"10", ymin=3, ymax=4)
max_5_log <- get_max(hubness4_log,"5", ymin=2, ymax=3)
max_2_log <- get_max(hubness4_log,"2", ymin=1, ymax=2)

ggplot(hubness4, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=1.5')
ggplot(hubness4_log, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score (log)") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047_log, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000_log, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000_log, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500_log, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100_log, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50_log, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10_log, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5_log, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2_log, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=1.5')
```

```{r test violin, p=1.5}
# Log to zoom on differences
ggplot(hubness4, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=1.5)") +
    ylab("Hubness score") +
    theme_grey(base_size = 15)
ggplot(hubness4_log, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=1.5)") +
    ylab("Hubness score (log)") +
    theme_grey(base_size = 15)
```

```{r viz, p=2}
# Viz
max_9047 <- get_max(hubness5,"9047", ymin=9, ymax=10)
max_5000 <- get_max(hubness5,"5000", ymin=8, ymax=9)
max_1000 <- get_max(hubness5,"1000", ymin=7, ymax=8)
max_500 <- get_max(hubness5,"500", ymin=6, ymax=7)
max_100 <- get_max(hubness5,"100", ymin=5, ymax=6)
max_50 <- get_max(hubness5,"50", ymin=4, ymax=5)
max_10 <- get_max(hubness5,"10", ymin=3, ymax=4)
max_5 <- get_max(hubness5,"5", ymin=2, ymax=3)
max_2 <- get_max(hubness5,"2", ymin=1, ymax=2)
max_9047_log <- get_max(hubness5_log,"9047", ymin=9, ymax=10)
max_5000_log <- get_max(hubness5_log,"5000", ymin=8, ymax=9)
max_1000_log <- get_max(hubness5_log,"1000", ymin=7, ymax=8)
max_500_log <- get_max(hubness5_log,"500", ymin=6, ymax=7)
max_100_log <- get_max(hubness5_log,"100", ymin=5, ymax=6)
max_50_log <- get_max(hubness5_log,"50", ymin=4, ymax=5)
max_10_log <- get_max(hubness5_log,"10", ymin=3, ymax=4)
max_5_log <- get_max(hubness5_log,"5", ymin=2, ymax=3)
max_2_log <- get_max(hubness5_log,"2", ymin=1, ymax=2)

ggplot(hubness5, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=2')
ggplot(hubness5_log, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score (log)") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047_log, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000_log, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000_log, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500_log, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100_log, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50_log, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10_log, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5_log, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2_log, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=2')
```

```{r test violin, p=2}
ggplot(hubness5, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=2)") +
    ylab("Hubness score") +
    theme_grey(base_size = 15)
ggplot(hubness5_log, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=2)") +
    ylab("Hubness score (log)") +
    theme_grey(base_size = 15)
```

```{r viz, p=4}
# Viz
max_9047 <- get_max(hubness6,"9047", ymin=9, ymax=10)
max_5000 <- get_max(hubness6,"5000", ymin=8, ymax=9)
max_1000 <- get_max(hubness6,"1000", ymin=7, ymax=8)
max_500 <- get_max(hubness6,"500", ymin=6, ymax=7)
max_100 <- get_max(hubness6,"100", ymin=5, ymax=6)
max_50 <- get_max(hubness6,"50", ymin=4, ymax=5)
max_10 <- get_max(hubness6,"10", ymin=3, ymax=4)
max_5 <- get_max(hubness6,"5", ymin=2, ymax=3)
max_2 <- get_max(hubness6,"2", ymin=1, ymax=2)
max_9047_log <- get_max(hubness6_log,"9047", ymin=9, ymax=10)
max_5000_log <- get_max(hubness6_log,"5000", ymin=8, ymax=9)
max_1000_log <- get_max(hubness6_log,"1000", ymin=7, ymax=8)
max_500_log <- get_max(hubness6_log,"500", ymin=6, ymax=7)
max_100_log <- get_max(hubness6_log,"100", ymin=5, ymax=6)
max_50_log <- get_max(hubness6_log,"50", ymin=4, ymax=5)
max_10_log <- get_max(hubness6_log,"10", ymin=3, ymax=4)
max_5_log <- get_max(hubness6_log,"5", ymin=2, ymax=3)
max_2_log <- get_max(hubness6_log,"2", ymin=1, ymax=2)

ggplot(hubness6, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=4')
ggplot(hubness6_log, aes(x = Hubness_score, y = Dimension, fill = Dimension)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  xlab("Hubness score (log)") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_9047_log, size=1, colour=hue_pal()(9)[9], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5000_log, size=1, colour=hue_pal()(9)[8], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_1000_log, size=1, colour=hue_pal()(9)[7], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_500_log, size=1, colour=hue_pal()(9)[6], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_100_log, size=1, colour=hue_pal()(9)[5], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_50_log, size=1, colour=hue_pal()(9)[4], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_10_log, size=1, colour=hue_pal()(9)[3], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_5_log, size=1, colour=hue_pal()(9)[2], inherit.aes = F) +
  geom_segment(aes(x = max, xend = max, y = ymin, yend = ymax), max_2_log, size=1, colour=hue_pal()(9)[1], inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores histogram with Lp norm,\np=4')
```

```{r test violin, p=4}
ggplot(hubness6, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=4)") +
    ylab("Hubness score") +
    theme_grey(base_size = 15)
ggplot(hubness6_log, aes(x=Dimension, y=Hubness_score, color=Dimension, fill=Dimension)) +
    geom_violin(width=1, size=0.8) +
    geom_jitter(position = position_jitter(0.2), cex=0.1, alpha = 0.1) +
    scale_fill_viridis(discrete=TRUE, alpha = 0.4) +
    scale_color_viridis(discrete=TRUE) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    xlab("Dimension of the tested space (p=4)") +
    ylab("Hubness score (log)") +
    theme_grey(base_size = 15)
```