---
title: "Hubness comparison for Lp norms"
output:
  pdf_document: default
  html_document: default
---

```{r libs, results="hide"}
library(philentropy)
library(ggplot2)
library(viridis)
library(ggridges)
library(scales)
```

```{r load}
h5_2 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_5_pca2_minkow.rds")
h10_2 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_10_pca2_minkow.rds")
h20_2 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_20_pca2_minkow.rds")
h50_2 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_50_pca2_minkow.rds")
h100_2 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_100_pca2_minkow.rds")
h200_2 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_200_pca2_minkow.rds")

h5_50 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_5_pca50_minkow.rds")
h10_50 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_10_pca50_minkow.rds")
h20_50 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_20_pca50_minkow.rds")
h50_50 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_50_pca50_minkow.rds")
h100_50 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_100_pca50_minkow.rds")
h200_50 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_200_pca50_minkow.rds")

h5_500 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_5_pca500_minkow.rds")
h10_500 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_10_pca500_minkow.rds")
h20_500 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_20_pca500_minkow.rds")
h50_500 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_50_pca500_minkow.rds")
h100_500 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_100_pca500_minkow.rds")
h200_500 <- readRDS("/Users/elise/Desktop/Thèse/Calcsub/tmp_zela/ML/hubness/Results/kNN_occurence_200_pca500_minkow.rds")
```

```{r functions}
get_rectange <- function(df,kval,dim1,dim2,p,ymin,ymax) {
   rect <- data.frame("k"=kval,
                      "xmin"=c(min(max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim2 & df$p==p])),
                               min(max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim2 & df$p==p])),
                               min(max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim2 & df$p==p])),
                               min(max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim2 & df$p==p])),
                               min(max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim2 & df$p==p])),
                               min(max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim2 & df$p==p]))),
                      "xmax"=c(max(max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim2 & df$p==p])),
                               max(max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim2 & df$p==p])),
                               max(max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim2 & df$p==p])),
                               max(max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim2 & df$p==p])),
                               max(max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim2 & df$p==p])),
                               max(max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim1 & df$p==p]),
                                   max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim2 & df$p==p]))),
                      "order"=c(max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim1 & df$p==p]) <
                                max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim2 & df$p==p]),
                                max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim1 & df$p==p]) <
                                max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim2 & df$p==p]),
                                max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim1 & df$p==p]) <
                                max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim2 & df$p==p]),
                                max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim1 & df$p==p]) <
                                max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim2 & df$p==p]),
                                max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim1 & df$p==p]) <
                                max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim2 & df$p==p]),
                                max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim1 & df$p==p]) <
                                max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim2 & df$p==p])),
                    "ymin"=ymin,
                    "ymax"=ymax)
}
```

```{r write df, echo=FALSE}
# First letter = pvalue
# Second letter = kvalue
# Third letter = dim value
aa_1 <- data.frame("Hubness_score" = h5_2[[1]])
aa_4 <- data.frame("Hubness_score" = h5_50[[1]])
aa_6 <- data.frame("Hubness_score" = h5_500[[1]])
ab_1 <- data.frame("Hubness_score" = h10_2[[1]])
ab_4 <- data.frame("Hubness_score" = h10_50[[1]])
ab_6 <- data.frame("Hubness_score" = h10_500[[1]])
ac_1 <- data.frame("Hubness_score" = h20_2[[1]])
ac_4 <- data.frame("Hubness_score" = h20_50[[1]])
ac_6 <- data.frame("Hubness_score" = h20_500[[1]])
ad_1 <- data.frame("Hubness_score" = h50_2[[1]])
ad_4 <- data.frame("Hubness_score" = h50_50[[1]])
ad_6 <- data.frame("Hubness_score" = h50_500[[1]])
ae_1 <- data.frame("Hubness_score" = h100_2[[1]])
ae_4 <- data.frame("Hubness_score" = h100_50[[1]])
ae_6 <- data.frame("Hubness_score" = h100_500[[1]])
af_1 <- data.frame("Hubness_score" = h200_2[[1]])
af_4 <- data.frame("Hubness_score" = h200_50[[1]])
af_6 <- data.frame("Hubness_score" = h200_500[[1]])
aa_1$k <- 5
aa_4$k <- 5
aa_6$k <- 5
ab_1$k <- 10
ab_4$k <- 10
ab_6$k <- 10
ac_1$k <- 20
ac_4$k <- 20
ac_6$k <- 20
ad_1$k <- 50
ad_4$k <- 50
ad_6$k <- 50
ae_1$k <- 100
ae_4$k <- 100
ae_6$k <- 100
af_1$k <- 200
af_4$k <- 200
af_6$k <- 200
aa_1$Dimension <- "2"
aa_4$Dimension <- "50"
aa_6$Dimension <- "500"
ab_1$Dimension <- "2"
ab_4$Dimension <- "50"
ab_6$Dimension <- "500"
ac_1$Dimension <- "2"
ac_4$Dimension <- "50"
ac_6$Dimension <- "500"
ad_1$Dimension <- "2"
ad_4$Dimension <- "50"
ad_6$Dimension <- "500"
ae_1$Dimension <- "2"
ae_4$Dimension <- "50"
ae_6$Dimension <- "500"
af_1$Dimension <- "2"
af_4$Dimension <- "50"
af_6$Dimension <- "500"
hubness1 <- rbind(aa_1,aa_4,aa_6,
                  ab_1,ab_4,ab_6,
                  ac_1,ac_4,ac_6,
                  ad_1,ad_4,ad_6,
                  ae_1,ae_4,ae_6,
                  af_1,af_4,af_6)
rm(aa_1,aa_4,aa_6,
   ab_1,ab_4,ab_6,
   ac_1,ac_4,ac_6,
   ad_1,ad_4,ad_6,
   ae_1,ae_4,ae_6,
   af_1,af_4,af_6)

ba_1 <- data.frame("Hubness_score" = h5_2[[2]])
ba_4 <- data.frame("Hubness_score" = h5_50[[2]])
ba_6 <- data.frame("Hubness_score" = h5_500[[2]])
bb_1 <- data.frame("Hubness_score" = h10_2[[2]])
bb_4 <- data.frame("Hubness_score" = h10_50[[2]])
bb_6 <- data.frame("Hubness_score" = h10_500[[2]])
bc_1 <- data.frame("Hubness_score" = h20_2[[2]])
bc_4 <- data.frame("Hubness_score" = h20_50[[2]])
bc_6 <- data.frame("Hubness_score" = h20_500[[2]])
bd_1 <- data.frame("Hubness_score" = h50_2[[2]])
bd_4 <- data.frame("Hubness_score" = h50_50[[2]])
bd_6 <- data.frame("Hubness_score" = h50_500[[2]])
be_1 <- data.frame("Hubness_score" = h100_2[[2]])
be_4 <- data.frame("Hubness_score" = h100_50[[2]])
be_6 <- data.frame("Hubness_score" = h100_500[[2]])
bf_1 <- data.frame("Hubness_score" = h200_2[[2]])
bf_4 <- data.frame("Hubness_score" = h200_50[[2]])
bf_6 <- data.frame("Hubness_score" = h200_500[[2]])
ba_1$k <- 5
ba_4$k <- 5
ba_6$k <- 5
bb_1$k <- 10
bb_4$k <- 10
bb_6$k <- 10
bc_1$k <- 20
bc_4$k <- 20
bc_6$k <- 20
bd_1$k <- 50
bd_4$k <- 50
bd_6$k <- 50
be_1$k <- 100
be_4$k <- 100
be_6$k <- 100
bf_1$k <- 200
bf_4$k <- 200
bf_6$k <- 200
ba_1$Dimension <- "2"
ba_4$Dimension <- "50"
ba_6$Dimension <- "500"
bb_1$Dimension <- "2"
bb_4$Dimension <- "50"
bb_6$Dimension <- "500"
bc_1$Dimension <- "2"
bc_4$Dimension <- "50"
bc_6$Dimension <- "500"
bd_1$Dimension <- "2"
bd_4$Dimension <- "50"
bd_6$Dimension <- "500"
be_1$Dimension <- "2"
be_4$Dimension <- "50"
be_6$Dimension <- "500"
bf_1$Dimension <- "2"
bf_4$Dimension <- "50"
bf_6$Dimension <- "500"
hubness2 <- rbind(ba_1,ba_4,ba_6,
                  bb_1,bb_4,bb_6,
                  bc_1,bc_4,bc_6,
                  bd_1,bd_4,bd_6,
                  be_1,be_4,be_6,
                  bf_1,bf_4,bf_6)
rm(ba_1,ba_4,ba_6,
   bb_1,bb_4,bb_6,
   bc_1,bc_4,bc_6,
   bd_1,bd_4,bd_6,
   be_1,be_4,be_6,
   bf_1,bf_4,bf_6)

ca_1 <- data.frame("Hubness_score" = h5_2[[3]])
ca_4 <- data.frame("Hubness_score" = h5_50[[3]])
ca_6 <- data.frame("Hubness_score" = h5_500[[3]])
cb_1 <- data.frame("Hubness_score" = h10_2[[3]])
cb_4 <- data.frame("Hubness_score" = h10_50[[3]])
cb_6 <- data.frame("Hubness_score" = h10_500[[3]])
cc_1 <- data.frame("Hubness_score" = h20_2[[3]])
cc_4 <- data.frame("Hubness_score" = h20_50[[3]])
cc_6 <- data.frame("Hubness_score" = h20_500[[3]])
cd_1 <- data.frame("Hubness_score" = h50_2[[3]])
cd_4 <- data.frame("Hubness_score" = h50_50[[3]])
cd_6 <- data.frame("Hubness_score" = h50_500[[3]])
ce_1 <- data.frame("Hubness_score" = h100_2[[3]])
ce_4 <- data.frame("Hubness_score" = h100_50[[3]])
ce_6 <- data.frame("Hubness_score" = h100_500[[3]])
cf_1 <- data.frame("Hubness_score" = h200_2[[3]])
cf_4 <- data.frame("Hubness_score" = h200_50[[3]])
cf_6 <- data.frame("Hubness_score" = h200_500[[3]])
ca_1$k <- 5
ca_4$k <- 5
ca_6$k <- 5
cb_1$k <- 10
cb_4$k <- 10
cb_6$k <- 10
cc_1$k <- 20
cc_4$k <- 20
cc_6$k <- 20
cd_1$k <- 50
cd_4$k <- 50
cd_6$k <- 50
ce_1$k <- 100
ce_4$k <- 100
ce_6$k <- 100
cf_1$k <- 200
cf_4$k <- 200
cf_6$k <- 200
ca_1$Dimension <- "2"
ca_4$Dimension <- "50"
ca_6$Dimension <- "500"
cb_1$Dimension <- "2"
cb_4$Dimension <- "50"
cb_6$Dimension <- "500"
cc_1$Dimension <- "2"
cc_4$Dimension <- "50"
cc_6$Dimension <- "500"
cd_1$Dimension <- "2"
cd_4$Dimension <- "50"
cd_6$Dimension <- "500"
ce_1$Dimension <- "2"
ce_4$Dimension <- "50"
ce_6$Dimension <- "500"
cf_1$Dimension <- "2"
cf_4$Dimension <- "50"
cf_6$Dimension <- "500"
hubness3 <- rbind(ca_1,ca_4,ca_6,
                 cb_1,cb_4,cb_6,
                 cc_1,cc_4,cc_6,
                 cd_1,cd_4,cd_6,
                 ce_1,ce_4,ce_6,
                 cf_1,cf_4,cf_6)
rm(ca_1,ca_4,ca_6,
                 cb_1,cb_4,cb_6,
                 cc_1,cc_4,cc_6,
                 cd_1,cd_4,cd_6,
                 ce_1,ce_4,ce_6,
                 cf_1,cf_4,cf_6)

da_1 <- data.frame("Hubness_score" = h5_2[[4]])
da_4 <- data.frame("Hubness_score" = h5_50[[4]])
da_6 <- data.frame("Hubness_score" = h5_500[[4]])
db_1 <- data.frame("Hubness_score" = h10_2[[4]])
db_4 <- data.frame("Hubness_score" = h10_50[[4]])
db_6 <- data.frame("Hubness_score" = h10_500[[4]])
dc_1 <- data.frame("Hubness_score" = h20_2[[4]])
dc_4 <- data.frame("Hubness_score" = h20_50[[4]])
dc_6 <- data.frame("Hubness_score" = h20_500[[4]])
dd_1 <- data.frame("Hubness_score" = h50_2[[4]])
dd_4 <- data.frame("Hubness_score" = h50_50[[4]])
dd_6 <- data.frame("Hubness_score" = h50_500[[4]])
de_1 <- data.frame("Hubness_score" = h100_2[[4]])
de_4 <- data.frame("Hubness_score" = h100_50[[4]])
de_6 <- data.frame("Hubness_score" = h100_500[[4]])
df_1 <- data.frame("Hubness_score" = h200_2[[4]])
df_4 <- data.frame("Hubness_score" = h200_50[[4]])
df_6 <- data.frame("Hubness_score" = h200_500[[4]])
da_1$k <- 5
da_4$k <- 5
da_6$k <- 5
db_1$k <- 10
db_4$k <- 10
db_6$k <- 10
dc_1$k <- 20
dc_4$k <- 20
dc_6$k <- 20
dd_1$k <- 50
dd_4$k <- 50
dd_6$k <- 50
de_1$k <- 100
de_4$k <- 100
de_6$k <- 100
df_1$k <- 200
df_4$k <- 200
df_6$k <- 200
da_1$Dimension <- "2"
da_4$Dimension <- "50"
da_6$Dimension <- "500"
db_1$Dimension <- "2"
db_4$Dimension <- "50"
db_6$Dimension <- "500"
dc_1$Dimension <- "2"
dc_4$Dimension <- "50"
dc_6$Dimension <- "500"
dd_1$Dimension <- "2"
dd_4$Dimension <- "50"
dd_6$Dimension <- "500"
de_1$Dimension <- "2"
de_4$Dimension <- "50"
de_6$Dimension <- "500"
df_1$Dimension <- "2"
df_4$Dimension <- "50"
df_6$Dimension <- "500"
hubness4 <- rbind(da_1,da_4,da_6,
                 db_1,db_4,db_6,
                 dc_1,dc_4,dc_6,
                 dd_1,dd_4,dd_6,
                 de_1,de_4,de_6,
                 df_1,df_4,df_6)
rm(da_1,da_4,da_6,
                 db_1,db_4,db_6,
                 dc_1,dc_4,dc_6,
                 dd_1,dd_4,dd_6,
                 de_1,de_4,de_6,
                 df_1,df_4,df_6)

ea_1 <- data.frame("Hubness_score" = h5_2[[4]])
ea_2 <- data.frame("Hubness_score" = h5_5[[4]])
ea_3 <- data.frame("Hubness_score" = h5_10[[4]])
ea_4 <- data.frame("Hubness_score" = h5_50[[4]])
ea_5 <- data.frame("Hubness_score" = h5_100[[4]])
ea_6 <- data.frame("Hubness_score" = h5_500[[4]])
ea_7 <- data.frame("Hubness_score" = h5_1000[[4]])
ea_8 <- data.frame("Hubness_score" = h5_5000[[4]])
ea_9 <- data.frame("Hubness_score" = h5_9047[[4]])
eb_1 <- data.frame("Hubness_score" = h10_2[[4]])
eb_2 <- data.frame("Hubness_score" = h10_5[[4]])
eb_3 <- data.frame("Hubness_score" = h10_10[[4]])
eb_4 <- data.frame("Hubness_score" = h10_50[[4]])
eb_5 <- data.frame("Hubness_score" = h10_100[[4]])
eb_6 <- data.frame("Hubness_score" = h10_500[[4]])
eb_7 <- data.frame("Hubness_score" = h10_1000[[4]])
eb_8 <- data.frame("Hubness_score" = h10_5000[[4]])
eb_9 <- data.frame("Hubness_score" = h10_9047[[4]])
ec_1 <- data.frame("Hubness_score" = h20_2[[4]])
ec_2 <- data.frame("Hubness_score" = h20_5[[4]])
ec_3 <- data.frame("Hubness_score" = h20_10[[4]])
ec_4 <- data.frame("Hubness_score" = h20_50[[4]])
ec_5 <- data.frame("Hubness_score" = h20_100[[4]])
ec_6 <- data.frame("Hubness_score" = h20_500[[4]])
ec_7 <- data.frame("Hubness_score" = h20_1000[[4]])
ec_8 <- data.frame("Hubness_score" = h20_5000[[4]])
ec_9 <- data.frame("Hubness_score" = h20_9047[[4]])
ed_1 <- data.frame("Hubness_score" = h50_2[[4]])
ed_2 <- data.frame("Hubness_score" = h50_5[[4]])
ed_3 <- data.frame("Hubness_score" = h50_10[[4]])
ed_4 <- data.frame("Hubness_score" = h50_50[[4]])
ed_5 <- data.frame("Hubness_score" = h50_100[[4]])
ed_6 <- data.frame("Hubness_score" = h50_500[[4]])
ed_7 <- data.frame("Hubness_score" = h50_1000[[4]])
ed_8 <- data.frame("Hubness_score" = h50_5000[[4]])
ed_9 <- data.frame("Hubness_score" = h50_9047[[4]])
ee_1 <- data.frame("Hubness_score" = h100_2[[4]])
ee_2 <- data.frame("Hubness_score" = h100_5[[4]])
ee_3 <- data.frame("Hubness_score" = h100_10[[4]])
ee_4 <- data.frame("Hubness_score" = h100_50[[4]])
ee_5 <- data.frame("Hubness_score" = h100_100[[4]])
ee_6 <- data.frame("Hubness_score" = h100_500[[4]])
ee_7 <- data.frame("Hubness_score" = h100_1000[[4]])
ee_8 <- data.frame("Hubness_score" = h100_5000[[4]])
ee_9 <- data.frame("Hubness_score" = h100_9047[[4]])
ef_1 <- data.frame("Hubness_score" = h200_2[[4]])
ef_2 <- data.frame("Hubness_score" = h200_5[[4]])
ef_3 <- data.frame("Hubness_score" = h200_10[[4]])
ef_4 <- data.frame("Hubness_score" = h200_50[[4]])
ef_5 <- data.frame("Hubness_score" = h200_100[[4]])
ef_6 <- data.frame("Hubness_score" = h200_500[[4]])
ef_7 <- data.frame("Hubness_score" = h200_1000[[4]])
ef_8 <- data.frame("Hubness_score" = h200_5000[[4]])
ef_9 <- data.frame("Hubness_score" = h200_9047[[4]])
ea_1$k <- 5
ea_2$k <- 5
ea_3$k <- 5
ea_4$k <- 5
ea_5$k <- 5
ea_6$k <- 5
ea_7$k <- 5
ea_8$k <- 5
ea_9$k <- 5
eb_1$k <- 10
eb_2$k <- 10
eb_3$k <- 10
eb_4$k <- 10
eb_5$k <- 10
eb_6$k <- 10
eb_7$k <- 10
eb_8$k <- 10
eb_9$k <- 10
ec_1$k <- 20
ec_2$k <- 20
ec_3$k <- 20
ec_4$k <- 20
ec_5$k <- 20
ec_6$k <- 20
ec_7$k <- 20
ec_8$k <- 20
ec_9$k <- 20
ed_1$k <- 50
ed_2$k <- 50
ed_3$k <- 50
ed_4$k <- 50
ed_5$k <- 50
ed_6$k <- 50
ed_7$k <- 50
ed_8$k <- 50
ed_9$k <- 50
ee_1$k <- 100
ee_2$k <- 100
ee_3$k <- 100
ee_4$k <- 100
ee_5$k <- 100
ee_6$k <- 100
ee_7$k <- 100
ee_8$k <- 100
ee_9$k <- 100
ef_1$k <- 200
ef_2$k <- 200
ef_3$k <- 200
ef_4$k <- 200
ef_5$k <- 200
ef_6$k <- 200
ef_7$k <- 200
ef_8$k <- 200
ef_9$k <- 200
ea_1$Dimension <- "2"
ea_2$Dimension <- "5"
ea_3$Dimension <- "10"
ea_4$Dimension <- "50"
ea_5$Dimension <- "100"
ea_6$Dimension <- "500"
ea_7$Dimension <- "1000"
ea_8$Dimension <- "5000"
ea_9$Dimension <- "9047"
eb_1$Dimension <- "2"
eb_2$Dimension <- "5"
eb_3$Dimension <- "10"
eb_4$Dimension <- "50"
eb_5$Dimension <- "100"
eb_6$Dimension <- "500"
eb_7$Dimension <- "1000"
eb_8$Dimension <- "5000"
eb_9$Dimension <- "9047"
ec_1$Dimension <- "2"
ec_2$Dimension <- "5"
ec_3$Dimension <- "10"
ec_4$Dimension <- "50"
ec_5$Dimension <- "100"
ec_6$Dimension <- "500"
ec_7$Dimension <- "1000"
ec_8$Dimension <- "5000"
ec_9$Dimension <- "9047"
ed_1$Dimension <- "2"
ed_2$Dimension <- "5"
ed_3$Dimension <- "10"
ed_4$Dimension <- "50"
ed_5$Dimension <- "100"
ed_6$Dimension <- "500"
ed_7$Dimension <- "1000"
ed_8$Dimension <- "5000"
ed_9$Dimension <- "9047"
ee_1$Dimension <- "2"
ee_2$Dimension <- "5"
ee_3$Dimension <- "10"
ee_4$Dimension <- "50"
ee_5$Dimension <- "100"
ee_6$Dimension <- "500"
ee_7$Dimension <- "1000"
ee_8$Dimension <- "5000"
ee_9$Dimension <- "9047"
ef_1$Dimension <- "2"
ef_2$Dimension <- "5"
ef_3$Dimension <- "10"
ef_4$Dimension <- "50"
ef_5$Dimension <- "100"
ef_6$Dimension <- "500"
ef_7$Dimension <- "1000"
ef_8$Dimension <- "5000"
ef_9$Dimension <- "9047"
hubness5 <- rbind(ea_1,ea_2,ea_3,ea_4,ea_5,ea_6,ea_7,ea_8,ea_9,
                 eb_1,eb_2,eb_3,eb_4,eb_5,eb_6,eb_7,eb_8,eb_9,
                 ec_1,ec_2,ec_3,ec_4,ec_5,ec_6,ec_7,ec_8,ec_9,
                 ed_1,ed_2,ed_3,ed_4,ed_5,ed_6,ed_7,ed_8,ed_9,
                 ee_1,ee_2,ee_3,ee_4,ee_5,ee_6,ee_7,ee_8,ee_9,
                 ef_1,ef_2,ef_3,ef_4,ef_5,ef_6,ef_7,ef_8,ef_9)
rm(ea_1,ea_2,ea_3,ea_4,ea_5,ea_6,ea_7,ea_8,ea_9,
   eb_1,eb_2,eb_3,eb_4,eb_5,eb_6,eb_7,eb_8,eb_9,
   ec_1,ec_2,ec_3,ec_4,ec_5,ec_6,ec_7,ec_8,ec_9,
   ed_1,ed_2,ed_3,ed_4,ed_5,ed_6,ed_7,ed_8,ed_9,
   ee_1,ee_2,ee_3,ee_4,ee_5,ee_6,ee_7,ee_8,ee_9,
   ef_1,ef_2,ef_3,ef_4,ef_5,ef_6,ef_7,ef_8,ef_9)

fa_1 <- data.frame("Hubness_score" = h5_2[[4]])
fa_2 <- data.frame("Hubness_score" = h5_5[[4]])
fa_3 <- data.frame("Hubness_score" = h5_10[[4]])
fa_4 <- data.frame("Hubness_score" = h5_50[[4]])
fa_5 <- data.frame("Hubness_score" = h5_100[[4]])
fa_6 <- data.frame("Hubness_score" = h5_500[[4]])
fa_7 <- data.frame("Hubness_score" = h5_1000[[4]])
fa_8 <- data.frame("Hubness_score" = h5_5000[[4]])
fa_9 <- data.frame("Hubness_score" = h5_9047[[4]])
fb_1 <- data.frame("Hubness_score" = h10_2[[4]])
fb_2 <- data.frame("Hubness_score" = h10_5[[4]])
fb_3 <- data.frame("Hubness_score" = h10_10[[4]])
fb_4 <- data.frame("Hubness_score" = h10_50[[4]])
fb_5 <- data.frame("Hubness_score" = h10_100[[4]])
fb_6 <- data.frame("Hubness_score" = h10_500[[4]])
fb_7 <- data.frame("Hubness_score" = h10_1000[[4]])
fb_8 <- data.frame("Hubness_score" = h10_5000[[4]])
fb_9 <- data.frame("Hubness_score" = h10_9047[[4]])
fc_1 <- data.frame("Hubness_score" = h20_2[[4]])
fc_2 <- data.frame("Hubness_score" = h20_5[[4]])
fc_3 <- data.frame("Hubness_score" = h20_10[[4]])
fc_4 <- data.frame("Hubness_score" = h20_50[[4]])
fc_5 <- data.frame("Hubness_score" = h20_100[[4]])
fc_6 <- data.frame("Hubness_score" = h20_500[[4]])
fc_7 <- data.frame("Hubness_score" = h20_1000[[4]])
fc_8 <- data.frame("Hubness_score" = h20_5000[[4]])
fc_9 <- data.frame("Hubness_score" = h20_9047[[4]])
fd_1 <- data.frame("Hubness_score" = h50_2[[4]])
fd_2 <- data.frame("Hubness_score" = h50_5[[4]])
fd_3 <- data.frame("Hubness_score" = h50_10[[4]])
fd_4 <- data.frame("Hubness_score" = h50_50[[4]])
fd_5 <- data.frame("Hubness_score" = h50_100[[4]])
fd_6 <- data.frame("Hubness_score" = h50_500[[4]])
fd_7 <- data.frame("Hubness_score" = h50_1000[[4]])
fd_8 <- data.frame("Hubness_score" = h50_5000[[4]])
fd_9 <- data.frame("Hubness_score" = h50_9047[[4]])
fe_1 <- data.frame("Hubness_score" = h100_2[[4]])
fe_2 <- data.frame("Hubness_score" = h100_5[[4]])
fe_3 <- data.frame("Hubness_score" = h100_10[[4]])
fe_4 <- data.frame("Hubness_score" = h100_50[[4]])
fe_5 <- data.frame("Hubness_score" = h100_100[[4]])
fe_6 <- data.frame("Hubness_score" = h100_500[[4]])
fe_7 <- data.frame("Hubness_score" = h100_1000[[4]])
fe_8 <- data.frame("Hubness_score" = h100_5000[[4]])
fe_9 <- data.frame("Hubness_score" = h100_9047[[4]])
ff_1 <- data.frame("Hubness_score" = h200_2[[4]])
ff_2 <- data.frame("Hubness_score" = h200_5[[4]])
ff_3 <- data.frame("Hubness_score" = h200_10[[4]])
ff_4 <- data.frame("Hubness_score" = h200_50[[4]])
ff_5 <- data.frame("Hubness_score" = h200_100[[4]])
ff_6 <- data.frame("Hubness_score" = h200_500[[4]])
ff_7 <- data.frame("Hubness_score" = h200_1000[[4]])
ff_8 <- data.frame("Hubness_score" = h200_5000[[4]])
ff_9 <- data.frame("Hubness_score" = h200_9047[[4]])
fa_1$k <- 5
fa_2$k <- 5
fa_3$k <- 5
fa_4$k <- 5
fa_5$k <- 5
fa_6$k <- 5
fa_7$k <- 5
fa_8$k <- 5
fa_9$k <- 5
fb_1$k <- 10
fb_2$k <- 10
fb_3$k <- 10
fb_4$k <- 10
fb_5$k <- 10
fb_6$k <- 10
fb_7$k <- 10
fb_8$k <- 10
fb_9$k <- 10
fc_1$k <- 20
fc_2$k <- 20
fc_3$k <- 20
fc_4$k <- 20
fc_5$k <- 20
fc_6$k <- 20
fc_7$k <- 20
fc_8$k <- 20
fc_9$k <- 20
fd_1$k <- 50
fd_2$k <- 50
fd_3$k <- 50
fd_4$k <- 50
fd_5$k <- 50
fd_6$k <- 50
fd_7$k <- 50
fd_8$k <- 50
fd_9$k <- 50
fe_1$k <- 100
fe_2$k <- 100
fe_3$k <- 100
fe_4$k <- 100
fe_5$k <- 100
fe_6$k <- 100
fe_7$k <- 100
fe_8$k <- 100
fe_9$k <- 100
ff_1$k <- 200
ff_2$k <- 200
ff_3$k <- 200
ff_4$k <- 200
ff_5$k <- 200
ff_6$k <- 200
ff_7$k <- 200
ff_8$k <- 200
ff_9$k <- 200
fa_1$Dimension <- "2"
fa_2$Dimension <- "5"
fa_3$Dimension <- "10"
fa_4$Dimension <- "50"
fa_5$Dimension <- "100"
fa_6$Dimension <- "500"
fa_7$Dimension <- "1000"
fa_8$Dimension <- "5000"
fa_9$Dimension <- "9047"
fb_1$Dimension <- "2"
fb_2$Dimension <- "5"
fb_3$Dimension <- "10"
fb_4$Dimension <- "50"
fb_5$Dimension <- "100"
fb_6$Dimension <- "500"
fb_7$Dimension <- "1000"
fb_8$Dimension <- "5000"
fb_9$Dimension <- "9047"
fc_1$Dimension <- "2"
fc_2$Dimension <- "5"
fc_3$Dimension <- "10"
fc_4$Dimension <- "50"
fc_5$Dimension <- "100"
fc_6$Dimension <- "500"
fc_7$Dimension <- "1000"
fc_8$Dimension <- "5000"
fc_9$Dimension <- "9047"
fd_1$Dimension <- "2"
fd_2$Dimension <- "5"
fd_3$Dimension <- "10"
fd_4$Dimension <- "50"
fd_5$Dimension <- "100"
fd_6$Dimension <- "500"
fd_7$Dimension <- "1000"
fd_8$Dimension <- "5000"
fd_9$Dimension <- "9047"
fe_1$Dimension <- "2"
fe_2$Dimension <- "5"
fe_3$Dimension <- "10"
fe_4$Dimension <- "50"
fe_5$Dimension <- "100"
fe_6$Dimension <- "500"
fe_7$Dimension <- "1000"
fe_8$Dimension <- "5000"
fe_9$Dimension <- "9047"
ff_1$Dimension <- "2"
ff_2$Dimension <- "5"
ff_3$Dimension <- "10"
ff_4$Dimension <- "50"
ff_5$Dimension <- "100"
ff_6$Dimension <- "500"
ff_7$Dimension <- "1000"
ff_8$Dimension <- "5000"
ff_9$Dimension <- "9047"
hubness6 <- rbind(fa_1,fa_2,fa_3,fa_4,fa_5,fa_6,fa_7,fa_8,fa_9,
                 fb_1,fb_2,fb_3,fb_4,fb_5,fb_6,fb_7,fb_8,fb_9,
                 fc_1,fc_2,fc_3,fc_4,fc_5,fc_6,fc_7,fc_8,fc_9,
                 fd_1,fd_2,fd_3,fd_4,fd_5,fd_6,fd_7,fd_8,fd_9,
                 fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,
                 ff_1,ff_2,ff_3,ff_4,ff_5,ff_6,ff_7,ff_8,ff_9)
rm(fa_1,fa_2,fa_3,fa_4,fa_5,fa_6,fa_7,fa_8,fa_9,
   fb_1,fb_2,fb_3,fb_4,fb_5,fb_6,fb_7,fb_8,fb_9,
   fc_1,fc_2,fc_3,fc_4,fc_5,fc_6,fc_7,fc_8,fc_9,
   fd_1,fd_2,fd_3,fd_4,fd_5,fd_6,fd_7,fd_8,fd_9,
   fe_1,fe_2,fe_3,fe_4,fe_5,fe_6,fe_7,fe_8,fe_9,
   ff_1,ff_2,ff_3,ff_4,ff_5,ff_6,ff_7,ff_8,ff_9)

# Reorder factor
hubness1$Dimension <- factor(hubness1$Dimension, levels = c("2","50","500"))
hubness2$Dimension <- factor(hubness2$Dimension, levels = c("2","50","500"))
hubness3$Dimension <- factor(hubness3$Dimension, levels = c("2","50","500"))
hubness4$Dimension <- factor(hubness4$Dimension, levels = c("2","50","500"))
hubness5$Dimension <- factor(hubness5$Dimension, levels = c("2","50","500"))
hubness6$Dimension <- factor(hubness6$Dimension, levels = c("2","50","500"))
# Removing cells with hubness score = 0
hubness1 <- hubness1[hubness1$Hubness_score != 0,]
hubness2 <- hubness2[hubness2$Hubness_score != 0,]
hubness3 <- hubness3[hubness3$Hubness_score != 0,]
hubness4 <- hubness4[hubness4$Hubness_score != 0,]
hubness5 <- hubness5[hubness5$Hubness_score != 0,]
hubness6 <- hubness6[hubness6$Hubness_score != 0,]
# Add p val
hubness1$p <- "0.1"
hubness2$p <- "0.5"
hubness3$p <- "1"
hubness4$p <- "1.5"
hubness5$p <- "2"
hubness6$p <- "4"
# Log to zoom on differences
hubness1_log <- hubness1
hubness2_log <- hubness2
hubness3_log <- hubness3
hubness4_log <- hubness4
hubness5_log <- hubness5
hubness6_log <- hubness6
hubness1_log$Hubness_score <- log(hubness1_log$Hubness_score)
hubness2_log$Hubness_score <- log(hubness2_log$Hubness_score)
hubness3_log$Hubness_score <- log(hubness3_log$Hubness_score)
hubness4_log$Hubness_score <- log(hubness4_log$Hubness_score)
hubness5_log$Hubness_score <- log(hubness5_log$Hubness_score)
hubness6_log$Hubness_score <- log(hubness6_log$Hubness_score)
```

```{r comp p=0.1 log, echo=FALSE}
# Merge the dfs
dif_1 <- get_rectange(hubness1_log, kval=c(5,10,20,50,100,200),dim1="2",dim2="50",p="0.1",ymin=1,ymax=2.5)
dif_2 <- get_rectange(hubness1_log, kval=c(5,10,20,50,100,200),dim1="50",dim2="500",p="0.1",ymin=2,ymax=3.5)

# Viz
ggplot(hubness1_log, aes(x = Hubness_score, y = Dimension, fill = p)) +
  scale_fill_manual(values = "royalblue2") +
  geom_density_ridges() +
  theme_ridges() +
  xlab("Hubness score (log)") +
  ylab("Dimension of the input space") +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_1, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_1$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_2, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_2$order, levels=c(F,T))]) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores comparison of Lp norm between dimensionalities,\np=0.1')
```
