---
title: "Hubness comparison for Lp norms"
output:
  pdf_document: default
  html_document: default
---

```{r libs, results="hide"}
library(philentropy, quietly = T)
library(ggplot2, quietly = T)
library(viridis, quietly = T)
library(ggridges, quietly = T)
library(scales, quietly = T)
```

```{r functions}
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/Analysis/hubness_load_write_data.R")
get_hub01 <- function(df,kval,dim,p,ymin,ymax) { # Maximum hubness score
   max = c()
   for (k in kval) {
      val = df$Hubness_score[df$Dimension==dim & df$p==p & df$k==k]
      max = c(max, max(val))
   }
   hub_val <- data.frame("k"=kval,
                         "Maximum"=max,
                         "ymin"=ymin,
                         "ymax"=ymax,
                         "xpos"=(max(x_thd)+max(df$Hubness_score[df$p==p]))/2,
                         "ypos"=ymin+0.5)
   return(hub_val)
}
get_hub02 <- function(df,kval,dimval,pval) { # hub 01 summary plot
   max = c()
   for (d in dimval) {
      for (k in kval) {
         for (p in pval) {
            val = df$Hubness_score[df$Dimension==d & df$p==p & df$k==k]
            max = c(max, max(val))
         }
      }
   }
   hub_val <- data.frame("p"=rep(pval,times=length(dimval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(dimval)),
                         "Dimension"=rep(dimval,each=length(kval)*length(pval)),
                         "Maximum"=max)
   return(hub_val)
}
get_hub_comp <- function(df,kval,dimval,p1,p2) { # Summary plot for the max comparison between two Lp norms
   max1 = c()
   max2 = c()
   for (d in dimval) {
      for (k in kval) {
         max1 = c(max1, max(df$Hubness_score[df$Dimension==d & df$p==p1 & df$k==k]))
         max2 = c(max2, max(df$Hubness_score[df$Dimension==d & df$p==p2 & df$k==k]))
      }
   }
   hub_comp_val <- data.frame("p1"=p1,
                              "p2"=p2,
                              "k"=kval,
                              "Dimension"=rep(dimval,each=length(kval)),
                              "Maximum value 1"=max1,
                              "Maximum value 1"=max2,
                              "Difference_amplitude"=max2-max1)
   return(hub_comp_val)
}
get_hub1 <- function(df,kval,dim,p,ymin,ymax) { # Using the mean + 3* sd from the original paper
   x_thd = c()
   hub_nb = c()
   for (k in kval) {
      val = df$Hubness_score[df$Dimension==dim & df$p==p & df$k==k]
      x_thd = c(x_thd, mean(val)+3*sd(val))
      hub_nb = c(hub_nb, sum(val>=(mean(val)+sd(val))))
   }
   hub_val <- data.frame("k"=kval,
                         "x_thd"=x_thd,
                         "hub_nb"=hub_nb,
                         "ymin"=ymin,
                         "ymax"=ymax,
                         "xpos"=(max(x_thd)+max(df$Hubness_score[df$p==p]))/2,
                         "ypos"=ymin+0.5)
   return(hub_val)
}
get_hub2 <- function(df,kval,dim,p,ymin,ymax,xpos,log=F) { # Using the method from [1] >= 2k
   if (log==T) {
      hub_nb = c()
      for (k in kval) {
         val = df$Hubness_score[df$Dimension==dim & df$p==p & df$k==k]
         hub_nb = c(hub_nb, sum(val>=2*log(k)))
      }
      x_thd = 2*log(kval)
   }
   else {
      hub_nb = c()
      for (k in kval) {
         val = df$Hubness_score[df$Dimension==dim & df$p==p & df$k==k]
         hub_nb = c(hub_nb, sum(val>=2*k))
      }
      x_thd = 2*kval
   }
   hub_val <- data.frame("k"=kval,
                         "x_thd"=x_thd,
                         "hub_nb"=hub_nb,
                         "ymin"=ymin,
                         "ymax"=ymax,
                         "xpos"=xpos,
                         "ypos"=ymin+0.5)
   return(hub_val)
}
get_hub3 <- function(df,kval,dimval,p) { # skewness summary plot
   s = c()
   for (d in dimval) {
      for (k in kval) {
         val = df$Hubness_score[df$Dimension==d & df$p==p & df$k==k]
         s = c(s, mean((val-mean(val))^3)/sd(val)^3)
      }
   }
   skewness_val <- data.frame("k"=rep(kval,times=length(dimval)),
                              "skewness"=s,
                              "Dimension"=rep(dimval,each=length(kval)))
   return(skewness_val)
}
get_hub4 <- function(df,kval,dimval,pval) { # hub 1 summary plot
   x_thd = c()
   hub_nb = c()
   for (d in dimval) {
      for (k in kval) {
         for (p in pval) {
            val = df$Hubness_score[df$Dimension==d & df$p==p & df$k==k]
            x_thd = c(x_thd, mean(val)+3*sd(val))
            hub_nb = c(hub_nb, sum(val>=(mean(val)+sd(val))))
         }
      }
   }
   hub_val <- data.frame("p"=rep(pval,times=length(dimval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(dimval)),
                         "Dimension"=rep(dimval,each=length(kval)*length(pval)),
                         "Hub_nb"=hub_nb,
                         "Threshold"=x_thd)
   return(hub_val)
}
get_hub5 <- function(df,kval,dimval,pval,log=F) { # hub 2 summary plot
   if (log==T) {
      hub_nb = c()
      for (d in dimval) {
         for (k in kval) {
            for (p in pval) {
               val = df$Hubness_score[df$Dimension==d & df$p==p & df$k==k]
               hub_nb = c(hub_nb, sum(val>=2*log(k)))
            }
         }
      }
   }
   else {
      hub_nb = c()
      for (d in dimval) {
         for (k in kval) {
            for (p in pval) {
               val = df$Hubness_score[df$Dimension==d & df$p==p & df$k==k]
               hub_nb = c(hub_nb, sum(val>=2*k))
            }
         }
      }
   }
   hub_val <- data.frame("p"=rep(pval,times=length(dimval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(dimval)),
                         "Dimension"=rep(dimval,each=length(kval)*length(pval)),
                         "Hub_nb"=hub_nb)
   return(hub_val)
}
get_hub6 <- function(df,kval,dimval,pval) { # hub 3 summary plot
   s = c()
   for (d in dimval) {
      for (k in kval) {
         for (p in pval) {
            val = df$Hubness_score[df$Dimension==d & df$p==p & df$k==k]
            s = c(s, mean((val-mean(val))^3)/sd(val)^3)
         }
      }
   }
   skewness_val <- data.frame("p"=rep(pval,times=length(dimval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(dimval)),
                         "Dimension"=rep(dimval,each=length(kval)*length(pval)),
                         "Skewness"=s)
   return(skewness_val)
}
```

```{r comp p=0.1, get_hub1, echo=FALSE}
# Merge the dfs
hub9047 <- get_hub1(hubness1, kval=c(5,10,20,50,100,200),dim="9047",p="0.1",ymin=9,ymax=10)
hub5000 <- get_hub1(hubness1, kval=c(5,10,20,50,100,200),dim="5000",p="0.1",ymin=8,ymax=9)
hub1000 <- get_hub1(hubness1, kval=c(5,10,20,50,100,200),dim="1000",p="0.1",ymin=7,ymax=8)
hub500 <- get_hub1(hubness1, kval=c(5,10,20,50,100,200),dim="500",p="0.1",ymin=6,ymax=7)
hub100 <- get_hub1(hubness1, kval=c(5,10,20,50,100,200),dim="100",p="0.1",ymin=5,ymax=6)
hub50 <- get_hub1(hubness1, kval=c(5,10,20,50,100,200),dim="50",p="0.1",ymin=4,ymax=5)
hub10 <- get_hub1(hubness1, kval=c(5,10,20,50,100,200),dim="10",p="0.1",ymin=3,ymax=4)
hub5 <- get_hub1(hubness1, kval=c(5,10,20,50,100,200),dim="5",p="0.1",ymin=2,ymax=3)
hub2 <- get_hub1(hubness1, kval=c(5,10,20,50,100,200),dim="2",p="0.1",ymin=1,ymax=2)
hub9047_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="9047",p="0.1",ymin=9,ymax=10)
hub5000_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="5000",p="0.1",ymin=8,ymax=9)
hub1000_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="1000",p="0.1",ymin=7,ymax=8)
hub500_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="500",p="0.1",ymin=6,ymax=7)
hub100_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="100",p="0.1",ymin=5,ymax=6)
hub50_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="50",p="0.1",ymin=4,ymax=5)
hub10_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="10",p="0.1",ymin=3,ymax=4)
hub5_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="5",p="0.1",ymin=2,ymax=3)
hub2_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="2",p="0.1",ymin=1,ymax=2)

# Viz
ggplot(hubness1, aes(x = Hubness_score, y = Dimension, fill = p)) +
  scale_fill_manual(values = "royalblue2") +
  geom_density_ridges() +
  theme_ridges() +
  xlab("Hubness score") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub9047, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5000, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub1000, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub500, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub100, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub50, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub10, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub2, colour="violetred", inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub9047, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5000, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub1000, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub500, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub100, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub50, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub10, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub2, inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores comparison of Lp norm between dimensionalities,\np=0.1')
ggplot(hubness1_log, aes(x = Hubness_score, y = Dimension, fill = p)) +
  scale_fill_manual(values = "royalblue2") +
  geom_density_ridges() +
  theme_ridges() +
  xlab("Hubness score (log)") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub9047_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5000_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub1000_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub500_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub100_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub50_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub10_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub2_log, colour="violetred", inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub9047_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5000_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub1000_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub500_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub100_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub50_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub10_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub2_log, inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores comparison of Lp norm between dimensionalities,\np=0.1')
```

```{r comp p=0.1, get_hub2, echo=FALSE}
# Merge the dfs
hub9047 <- get_hub2(hubness1, kval=c(5,10,20,50,100,200),dim="9047",p="0.1",ymin=9,ymax=10,xpos=7500)
hub5000 <- get_hub2(hubness1, kval=c(5,10,20,50,100,200),dim="5000",p="0.1",ymin=8,ymax=9,xpos=7500)
hub1000 <- get_hub2(hubness1, kval=c(5,10,20,50,100,200),dim="1000",p="0.1",ymin=7,ymax=8,xpos=7500)
hub500 <- get_hub2(hubness1, kval=c(5,10,20,50,100,200),dim="500",p="0.1",ymin=6,ymax=7,xpos=7500)
hub100 <- get_hub2(hubness1, kval=c(5,10,20,50,100,200),dim="100",p="0.1",ymin=5,ymax=6,xpos=7500)
hub50 <- get_hub2(hubness1, kval=c(5,10,20,50,100,200),dim="50",p="0.1",ymin=4,ymax=5,xpos=7500)
hub10 <- get_hub2(hubness1, kval=c(5,10,20,50,100,200),dim="10",p="0.1",ymin=3,ymax=4,xpos=7500)
hub5 <- get_hub2(hubness1, kval=c(5,10,20,50,100,200),dim="5",p="0.1",ymin=2,ymax=3,xpos=7500)
hub2 <- get_hub2(hubness1, kval=c(5,10,20,50,100,200),dim="2",p="0.1",ymin=1,ymax=2,xpos=7500)
hub9047_log <- get_hub2(hubness1_log, kval=c(5,10,20,50,100,200),dim="9047",p="0.1",ymin=9,ymax=10,log=T,xpos=10)
hub5000_log <- get_hub2(hubness1_log, kval=c(5,10,20,50,100,200),dim="5000",p="0.1",ymin=8,ymax=9,log=T,xpos=10)
hub1000_log <- get_hub2(hubness1_log, kval=c(5,10,20,50,100,200),dim="1000",p="0.1",ymin=7,ymax=8,log=T,xpos=10)
hub500_log <- get_hub2(hubness1_log, kval=c(5,10,20,50,100,200),dim="500",p="0.1",ymin=6,ymax=7,log=T,xpos=10)
hub100_log <- get_hub2(hubness1_log, kval=c(5,10,20,50,100,200),dim="100",p="0.1",ymin=5,ymax=6,log=T,xpos=10)
hub50_log <- get_hub2(hubness1_log, kval=c(5,10,20,50,100,200),dim="50",p="0.1",ymin=4,ymax=5,log=T,xpos=10)
hub10_log <- get_hub2(hubness1_log, kval=c(5,10,20,50,100,200),dim="10",p="0.1",ymin=3,ymax=4,log=T,xpos=10)
hub5_log <- get_hub2(hubness1_log, kval=c(5,10,20,50,100,200),dim="5",p="0.1",ymin=2,ymax=3,log=T,xpos=10)
hub2_log <- get_hub2(hubness1_log, kval=c(5,10,20,50,100,200),dim="2",p="0.1",ymin=1,ymax=2,log=T,xpos=10)

# Viz
ggplot(hubness1, aes(x = Hubness_score, y = Dimension, fill = p)) +
  scale_fill_manual(values = "royalblue2") +
  geom_density_ridges() +
  theme_ridges() +
  xlab("Hubness score") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub9047, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5000, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub1000, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub500, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub100, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub50, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub10, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub2, colour="violetred", inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub9047, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5000, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub1000, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub500, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub100, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub50, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub10, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub2, inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores comparison of Lp norm between dimensionalities,\np=0.1')
ggplot(hubness1_log, aes(x = Hubness_score, y = Dimension, fill = p)) +
  scale_fill_manual(values = "royalblue2") +
  geom_density_ridges() +
  theme_ridges() +
  xlab("Hubness score (log)") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub9047_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5000_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub1000_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub500_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub100_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub50_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub10_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub2_log, colour="violetred", inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub9047_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5000_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub1000_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub500_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub100_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub50_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub10_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub2_log, inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores comparison of Lp norm between dimensionalities,\np=0.1')
```

```{r comp p=0.1, get_hub3, echo=FALSE}
# Merge the dfs
dimval <- factor(unique(hubness1$Dimension), levels = c("2","5","10","50","100","500","1000","5000","9047"))
kval <- c(5,10,20,50,100,200)
skewness <- get_hub3(hubness1, kval=kval,dimval=dimval,p="0.1")
skewness_log <- get_hub3(hubness1_log, kval=kval,dimval=dimval,p="0.1")

# Viz
ggplot(skewness, aes(x=Dimension, y=skewness, color=factor(k))) +
   geom_point() +
   geom_line(aes(group=k),linetype='dotted') +
   facet_wrap(~k)
# Viz
ggplot(skewness_log, aes(x=Dimension, y=skewness, color=factor(k))) +
   geom_point() +
   geom_line(aes(group=k),linetype='dotted') +
   facet_wrap(~k)
```

```{r comp all, get_hub4, echo=FALSE}
# Merge the dfs
dimval <- c(2,5,10,50,100,500,1000,5000,9047)
kval <- c(5,10,20,50,100,200)
pval <- c(0.1,0.5,1,1.5,2,4)
hub_nb <- get_hub4(hubness, kval=kval,dimval=dimval,pval=pval)
hub_nb_log <- get_hub4(hubness_log, kval=kval,dimval=dimval,pval=pval)

# Viz
ggplot(hub_nb, aes(x=p, y=Hub_nb, color=factor(Dimension))) +
   geom_point() +
   geom_line(aes(group=Dimension),linetype='dotted') +
   facet_wrap(~k)
ggplot(hub_nb_log, aes(x=p, y=Hub_nb, color=factor(Dimension))) +
   geom_point() +
   geom_line(aes(group=Dimension),linetype='dotted') +
   facet_wrap(~k)
```

```{r comp all, get_hub5, echo=FALSE}
# Merge the dfs
dimval <- c(2,5,10,50,100,500,1000,5000,9047)
kval <- c(5,10,20,50,100,200)
pval <- c(0.1,0.5,1,1.5,2,4)
hub_nb <- get_hub5(hubness, kval=kval,dimval=dimval,pval=pval, log=F)
hub_nb_log <- get_hub5(hubness_log, kval=kval,dimval=dimval,pval=pval, log=T)

# Viz
ggplot(hub_nb, aes(x=p, y=Hub_nb, color=factor(Dimension))) +
   geom_point() +
   geom_line(aes(group=Dimension),linetype='dotted') +
   facet_wrap(~k)
ggplot(hub_nb_log, aes(x=p, y=Hub_nb, color=factor(Dimension))) +
   geom_point() +
   geom_line(aes(group=Dimension),linetype='dotted') +
   facet_wrap(~k)
```

```{r comp all, get_hub6, echo=FALSE}
# Merge the dfs
dimval <- c(2,5,10,50,100,500,1000,5000,9047)
kval <- c(5,10,20,50,100,200)
pval <- c(0.1,0.5,1,1.5,2,4)
skewness <- get_hub6(hubness, kval=kval,dimval=dimval,pval=pval)
skewness_log <- get_hub6(hubness_log, kval=kval,dimval=dimval,pval=pval)

# Viz
ggplot(skewness, aes(x=p, y=Skewness, color=factor(Dimension))) +
   geom_point() +
   geom_line(aes(group=Dimension),linetype='dotted') +
   facet_wrap(~k)
ggplot(skewness_log, aes(x=p, y=Skewness, color=factor(Dimension))) +
   geom_point() +
   geom_line(aes(group=Dimension),linetype='dotted') +
   facet_wrap(~k)
```

```{r comp all, get_hub02, echo=FALSE}
# Merge the dfs
dimval <- c(2,5,10,50,100,500,1000,5000,9047)
kval <- c(5,10,20,50,100,200)
pval <- c(0.1,0.5,1,1.5,2,4)
maximum <- get_hub02(hubness, kval=kval,dimval=dimval,pval=pval)
maximum_log <- get_hub02(hubness_log, kval=kval,dimval=dimval,pval=pval)

# Viz
ggplot(maximum, aes(x=p, y=Maximum, color=factor(Dimension))) +
   geom_point() +
   geom_line(aes(group=Dimension),linetype='dotted') +
   facet_wrap(~k)
ggplot(maximum_log, aes(x=p, y=Maximum, color=factor(Dimension))) +
   geom_point() +
   geom_line(aes(group=Dimension),linetype='dotted') +
   facet_wrap(~k)
```

```{r comp all, get_hub_comp, echo=FALSE}
# Merge the dfs
dimval <- c(2,5,10,50,100,500,1000,5000,9047)
kval <- c(5,10,20,50,100,200)
p1 <- 1
p2 <- 2
difference <- get_hub_comp(hubness, kval=kval,dimval=dimval,p1=p1,p2=p2)
difference_log <- get_hub_comp(hubness_log, kval=kval,dimval=dimval,p1=p1,p2=p2)

# Viz
ggplot(difference, aes(x=factor(Dimension), y=Difference_amplitude, color=factor(Dimension))) +
   geom_bar(stat="identity", width = 1) +
   facet_wrap(~k)
ggplot(difference_log, aes(x=factor(Dimension), y=Difference_amplitude, color=factor(Dimension))) +
   geom_bar(stat="identity", width = 1) +
   facet_wrap(~k)
```

```{r comp p=0.1, get_hub1, echo=FALSE}
# Merge the dfs
hub9047 <- get_hub1(hubness5, kval=c(5,10,20,50,100,200),dim="9047",p="0.1",ymin=9,ymax=10)
hub5000 <- get_hub1(hubness5, kval=c(5,10,20,50,100,200),dim="5000",p="0.1",ymin=8,ymax=9)
hub1000 <- get_hub1(hubness5, kval=c(5,10,20,50,100,200),dim="1000",p="0.1",ymin=7,ymax=8)
hub500 <- get_hub1(hubness5, kval=c(5,10,20,50,100,200),dim="500",p="0.1",ymin=6,ymax=7)
hub100 <- get_hub1(hubness5, kval=c(5,10,20,50,100,200),dim="100",p="0.1",ymin=5,ymax=6)
hub50 <- get_hub1(hubness5, kval=c(5,10,20,50,100,200),dim="50",p="0.1",ymin=4,ymax=5)
hub10 <- get_hub1(hubness5, kval=c(5,10,20,50,100,200),dim="10",p="0.1",ymin=3,ymax=4)
hub5 <- get_hub1(hubness5, kval=c(5,10,20,50,100,200),dim="5",p="0.1",ymin=2,ymax=3)
hub2 <- get_hub1(hubness5, kval=c(5,10,20,50,100,200),dim="2",p="0.1",ymin=1,ymax=2)
hub9047_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="9047",p="0.1",ymin=9,ymax=10)
hub5000_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="5000",p="0.1",ymin=8,ymax=9)
hub1000_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="1000",p="0.1",ymin=7,ymax=8)
hub500_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="500",p="0.1",ymin=6,ymax=7)
hub100_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="100",p="0.1",ymin=5,ymax=6)
hub50_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="50",p="0.1",ymin=4,ymax=5)
hub10_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="10",p="0.1",ymin=3,ymax=4)
hub5_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="5",p="0.1",ymin=2,ymax=3)
hub2_log <- get_hub1(hubness1_log, kval=c(5,10,20,50,100,200),dim="2",p="0.1",ymin=1,ymax=2)

# Viz
ggplot(hubness1, aes(x = Hubness_score, y = Dimension, fill = p)) +
  scale_fill_manual(values = "royalblue2") +
  geom_density_ridges() +
  theme_ridges() +
  xlab("Hubness score") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub9047, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5000, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub1000, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub500, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub100, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub50, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub10, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub2, colour="violetred", inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub9047, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5000, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub1000, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub500, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub100, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub50, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub10, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub2, inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores comparison of Lp norm between dimensionalities,\np=2')
ggplot(hubness1_log, aes(x = Hubness_score, y = Dimension, fill = p)) +
  scale_fill_manual(values = "royalblue2") +
  geom_density_ridges() +
  theme_ridges() +
  xlab("Hubness score (log)") +
  ylab("Dimension of the input space") +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub9047_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5000_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub1000_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub500_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub100_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub50_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub10_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub5_log, colour="violetred", inherit.aes = F) +
  geom_segment(aes(x = x_thd, xend = x_thd, y = ymin, yend = ymax), hub2_log, colour="violetred", inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub9047_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5000_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub1000_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub500_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub100_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub50_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub10_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub5_log, inherit.aes = F) +
  geom_text(aes(x = xpos, label = hub_nb, y = ypos), hub2_log, inherit.aes = F) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores comparison of Lp norm between dimensionalities,\np=0.1')
```