---
title: "Hubness comparison for Lp norms"
output:
  pdf_document: default
  html_document: default
---

```{r libs, results="hide"}
library(philentropy)
library(ggplot2)
library(viridis)
library(ggridges)
library(scales)
```

```{r functions}
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/hubness_load_write_data_guo.R")
get_rectange <- function(df,kval,dim,p1,p2,ymin,ymax) {
   rect <- data.frame("k"=kval,
                      "xmin"=c(min(max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim & df$p==p2])),
                               min(max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim & df$p==p2])),
                               min(max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim & df$p==p2])),
                               min(max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim & df$p==p2])),
                               min(max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim & df$p==p2])),
                               min(max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim & df$p==p2]))),
                      "xmax"=c(max(max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim & df$p==p2])),
                               max(max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim & df$p==p2])),
                               max(max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim & df$p==p2])),
                               max(max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim & df$p==p2])),
                               max(max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim & df$p==p2])),
                               max(max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim & df$p==p1]),
                                   max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim & df$p==p2]))),
                      "order"=c(max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim & df$p==p1]) <
                                max(df$Hubness_score[df$k==kval[1] & df$Dimension==dim & df$p==p2]),
                                max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim & df$p==p1]) <
                                max(df$Hubness_score[df$k==kval[2] & df$Dimension==dim & df$p==p2]),
                                max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim & df$p==p1]) <
                                max(df$Hubness_score[df$k==kval[3] & df$Dimension==dim & df$p==p2]),
                                max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim & df$p==p1]) <
                                max(df$Hubness_score[df$k==kval[4] & df$Dimension==dim & df$p==p2]),
                                max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim & df$p==p1]) <
                                max(df$Hubness_score[df$k==kval[5] & df$Dimension==dim & df$p==p2]),
                                max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim & df$p==p1]) <
                                max(df$Hubness_score[df$k==kval[6] & df$Dimension==dim & df$p==p2])),
                    "ymin"=ymin,
                    "ymax"=ymax)
}
```

```{r comp12, echo=FALSE}
# Merge the dfs
hubness <- rbind(hubness1,hubness2)
p1="0.1"
p2="0.5"
dif_9047 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="9047",p1=p1,p2=p2,ymin=9,ymax=10)
dif_5000 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="5000",p1=p1,p2=p2,ymin=8,ymax=9)
dif_1000 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="1000",p1=p1,p2=p2,ymin=7,ymax=8)
dif_500 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="500",p1=p1,p2=p2,ymin=6,ymax=7)
dif_100 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="100",p1=p1,p2=p2,ymin=5,ymax=6)
dif_50 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="50",p1=p1,p2=p2,ymin=4,ymax=5)
dif_10 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="10",p1=p1,p2=p2,ymin=3,ymax=4)
dif_5 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="5",p1=p1,p2=p2,ymin=2,ymax=3)
dif_2 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="2",p1=p1,p2=p2,ymin=1,ymax=2)

# Viz
ggplot(hubness, aes(x = Hubness_score, y = Dimension, fill = p)) +
  scale_fill_manual(values = c("mediumvioletred","royalblue2")) +
  geom_density_ridges(alpha=0.8) +
  theme_ridges() +
  xlab("Hubness score") +
  ylab("Dimension of the input space") +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_9047, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_9047$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_5000, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_5000$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_1000, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_1000$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_500, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_500$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_100, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_100$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_50, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_50$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_10, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_10$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_5, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_5$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_2, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_2$order, levels=c(F,T))]) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores comparison of Lp norm,\np=0.1 or p=0.5')
```

```{r comp35, echo=FALSE}
# Merge the dfs
hubness <- rbind(hubness3,hubness5)
p1="1"
p2="2"
dif_9047 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="9047",p1=p1,p2=p2,ymin=9,ymax=10)
dif_5000 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="5000",p1=p1,p2=p2,ymin=8,ymax=9)
dif_1000 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="1000",p1=p1,p2=p2,ymin=7,ymax=8)
dif_500 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="500",p1=p1,p2=p2,ymin=6,ymax=7)
dif_100 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="100",p1=p1,p2=p2,ymin=5,ymax=6)
dif_50 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="50",p1=p1,p2=p2,ymin=4,ymax=5)
dif_10 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="10",p1=p1,p2=p2,ymin=3,ymax=4)
dif_5 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="5",p1=p1,p2=p2,ymin=2,ymax=3)
dif_2 <- get_rectange(hubness, kval=c(5,10,20,50,100,200),dim="2",p1=p1,p2=p2,ymin=1,ymax=2)

# Viz
ggplot(hubness, aes(x = Hubness_score, y = Dimension, fill = p)) +
  scale_fill_manual(values = c("mediumvioletred","royalblue2")) +
  geom_density_ridges(alpha=0.8) +
  theme_ridges() +
  xlab("Hubness score") +
  ylab("Dimension of the input space") +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_9047, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_9047$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_5000, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_5000$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_1000, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_1000$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_500, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_500$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_100, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_100$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_50, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_50$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_10, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_10$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_5, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_5$order, levels=c(F,T))]) +
  geom_rect(aes(x=NULL, y=NULL, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), dif_2, alpha=0.6, fill=c("violetred1","seagreen3")[factor(dif_2$order, levels=c(F,T))]) +
  facet_wrap( ~ k) +
  ggtitle('Hubness scores comparison of Lp norm,\np=1 or p=2')
```
