---
title: "Clustering"
output:
  html_document: default
  pdf_document: default
---

```{r libs, results="hide", include = FALSE}
library(ggplot2, quietly = T)
library(viridis, quietly = T)
library(ggpubr, quietly = T)
library(Seurat, quietly = T)
library(cluster, quietly = T)
```

Method 2 : mu + 3sigma (k=200)
Method 6 : anti hubs
Method 7 : MAD (k=200)

```{r functions, include = FALSE}
get_hub2 <- function(df,kval,pcval,pval) { # Using the mean + 3*sd from Tomasev
   x_thd = c()
   hub_nb = c()
   ymin = c()
   ymax = c()
   y_increment = 1
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
            val = df$score[df$Dimension==d & df$p==p & df$k==k]
            x_thd = c(x_thd, mean(val)+3*sd(val))
            hub_nb = c(hub_nb, sum(val>=(mean(val)+3*sd(val))))
            ymin = c(ymin,y_increment)
            ymax = c(ymax,y_increment+1)
         }
      }
     y_increment <- y_increment+1
   }
   hub_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=hub_nb,
                         "Threshold"=x_thd,
                         "ymin"=ymin,
                         "ymax"=ymax)
   return(hub_val)
}
get_hub6 <- function(df,kval,pcval,pval) { # anti hubs
   anti_hub = c()
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
           anti_hub = c(anti_hub,unique(df$Antihubs[df$Dimension==d & df$p==p & df$k==k]))
         }
      }
   }
   hub_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=anti_hub)
   hub_val$Dimension <- factor(hub_val$Dimension, levels = pcval)
   return(hub_val)
}
get_hub7 <- function(df,kval,pcval,pval) { # median + 3MAD
   x_thd = c()
   hub_nb = c()
   ymin = c()
   ymax = c()
   y_increment = 1
   for (d in pcval) {
      for (k in kval) {
         for (p in pval) {
           val = df$score[df$Dimension==d & df$p==p & df$k==k]
           x_thd = c(x_thd, median(val)+3*mad(val,
                                              #center=ifelse(median(val)!=0,median(val),1)
                                              ))
           hub_nb = c(hub_nb, sum(val>=(median(val)+3*mad(val,
                                                          #center=ifelse(median(val)!=0,median(val),1)
                                                          ))))
           ymin = c(ymin,y_increment)
           ymax = c(ymax,y_increment+1)
         }
      }
     y_increment <- y_increment+1
   }
   hub_val <- data.frame("p"=rep(pval,times=length(pcval)*length(kval)),
                         "k"=rep(rep(kval,each=length(pval)),times=length(pcval)),
                         "Dimension"=rep(pcval,each=length(kval)*length(pval)),
                         "GHubness"=hub_nb,
                         "Threshold"=x_thd,
                         "ymin"=ymin,
                         "ymax"=ymax)
   return(hub_val)
}
```

```{r load data, include = FALSE}
#source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_Guo.R")
source(file="/Users/elise/Desktop/GitHub/Hubness_sc/R_scripts/load_data/hubness_load_write_data_Satija.R")
#guo_data <- read.table("/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Guo_lung_2018/GSE99254_NSCLC.TCell.S9055.count.labeled.txt")
#guo_labels <- read.table("/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/Guo_lung_2018/Dataset-2019-01-22.csv",sep=";",header = T)
satija_data <- read.csv("/Users/elise/Desktop/Thèse/scRNAseq/Data_sc/10x/GSE100866_CBMC_8K_13AB_10X-RNA_umi.csv", row.names = 1)

# Remove cells that look abnormal
#nFeature <- apply(guo_data,2,function(x) sum(x!=0))
#nCount <- apply(guo_data,2,sum)
#guo_data <- guo_data[,nFeature<7500 & nCount<35e+05] # 9047 cells for Guo
#rm(nCount,nFeature)
satija_data <- satija_data[grep("HUMAN_",rownames(satija_data)),] # 20400 genes
rownames(satija_data) <- gsub("HUMAN_","",rownames(satija_data))
nFeature <- apply(satija_data,2,function(x) sum(x!=0))
nCount <- apply(satija_data,2,sum)
satija_data <- satija_data[,nFeature<4000 & nCount<15e+03] # 8604 cells for Satija
rm(nCount,nFeature)

#data <- guo_data
data <- satija_data
rm(guo_data,satija_data)
```

```{r get the hubs with the different methods, include = FALSE}
parameter <- data.frame(200,100,2)
names(parameter) <- c("k","pc","p")
val <- hubness$score[hubness$k==parameter$k & hubness$Dimension==parameter$pc & hubness$p==parameter$p]
thd2 <- get_hub2(hubness,kval=parameter$k,pcval=parameter$pc,pval=parameter$p)$Threshold
hub2 <- colnames(data)[val>=thd2]
hub6 <- colnames(data)[val==0]
thd7 <- get_hub7(hubness,kval=parameter$k,pcval=parameter$pc,pval=parameter$p)$Threshold
hub7 <- colnames(data)[val>=thd7]
```

```{r prep Seurat, include=FALSE}
#data <- data[,satija_labels$Cell.ID]
seurat <- CreateSeuratObject(data)
#seurat$FACS <- satija_labels$cellType
seurat$hub2 <- c("normal","hub")[factor(colnames(seurat) %in% hub2, levels = c("FALSE","TRUE"))]
seurat$hub6 <- c("normal","antihub")[factor(colnames(seurat) %in% hub6, levels = c("FALSE","TRUE"))]
seurat$hub7 <- c("normal","hub")[factor(colnames(seurat) %in% hub7, levels = c("FALSE","TRUE"))]
seurat[["percent.mt"]] <- PercentageFeatureSet(seurat, pattern = "^MT-")
VlnPlot(seurat, features = c("nFeature_RNA","nCount_RNA","percent.mt"))
FeatureScatter(seurat, feature1 = "nFeature_RNA", feature2 = "nCount_RNA")
# Remove cells with more than 7500 genes or 3e+06 total counts for Guo
#seurat <- subset(seurat, subset = nFeature_RNA<7500 & nCount_RNA<3e+06) # 9047 cells
#VlnPlot(seurat, features = c("nFeature_RNA","nCount_RNA","percent.mt"))
# Normalize + log transfo + scale
library(ggpubr)
seurat <- NormalizeData(seurat)
seurat <- ScaleData(seurat)
seurat <- FindVariableFeatures(seurat)
seurat <- RunPCA(seurat, verbose = F)
seurat <- RunUMAP(seurat, dims = 1:50)
seurat <- RunTSNE(seurat, dims = 1:50)
```

```{r clustering w/ or w/o hubs}
prop.table(table(seurat$FACS))*100
prop.table(table(seurat$FACS[unname(seurat$hub2=="normal")]))*100
prop.table(table(seurat$FACS[unname(seurat$hub2=="hub")]))*100
prop.table(table(seurat$FACS[unname(seurat$hub6=="normal")]))*100
prop.table(table(seurat$FACS[unname(seurat$hub6=="antihub")]))*100
prop.table(table(seurat$FACS[unname(seurat$hub7=="normal")]))*100
prop.table(table(seurat$FACS[unname(seurat$hub7=="hub")]))*100

satija_hub2 <- subset(seurat, cells = colnames(seurat)[unname(seurat$hub2=="hub")])
satija_antihub <- subset(seurat, cells = colnames(seurat)[unname(seurat$hub6=="antihub")])
satija_hub7 <- subset(seurat, cells = colnames(seurat)[unname(seurat$hub7=="hub")])
satija_normal2 <- subset(seurat, cells = colnames(seurat)[unname(seurat$hub2=="normal")])
satija_normal6 <- subset(seurat, cells = colnames(seurat)[unname(seurat$hub6=="normal")])
satija_normal7 <- subset(seurat, cells = colnames(seurat)[unname(seurat$hub7=="normal")])
satija_normal2 <- FindNeighbors(satija_normal2, dims = 1:20)
satija_normal6 <- FindNeighbors(satija_normal6, dims = 1:20)
satija_normal7 <- FindNeighbors(satija_normal7, dims = 1:20)
seurat <- FindNeighbors(seurat, dims = 1:20)
satija_normal2 <- FindClusters(satija_normal2, resolution = 0.5)
satija_normal6 <- FindClusters(satija_normal6, resolution = 0.5)
satija_normal7 <- FindClusters(satija_normal7, resolution = 0.5)
seurat <- FindClusters(seurat, resolution = 0.5)
marker_normal2 <- FindAllMarkers(satija_normal2, return.thresh = 0.01, min.diff.pct = 0.15)
marker_normal6 <- FindAllMarkers(satija_normal6, return.thresh = 0.01, min.diff.pct = 0.15)
marker_normal7 <- FindAllMarkers(satija_normal7, return.thresh = 0.01, min.diff.pct = 0.15)
marker_satija <- FindAllMarkers(seurat, return.thresh = 0.01, min.diff.pct = 0.15)
marker_normal2 <- marker_normal2[marker_normal2$p_val_adj<0.01,]
marker_normal6 <- marker_normal6[marker_normal6$p_val_adj<0.01,]
marker_normal7 <- marker_normal7[marker_normal7$p_val_adj<0.01,]
marker_satija <- marker_satija[marker_satija$p_val_adj<0.01,]
sil_normal2 <- silhouette(as.numeric(unname(Idents(satija_normal2))),
                         dist(satija_normal2@reductions$pca@cell.embeddings[,1:20]))
sil_normal6 <- silhouette(as.numeric(unname(Idents(satija_normal6))),
                         dist(satija_normal6@reductions$pca@cell.embeddings[,1:20]))
sil_normal7 <- silhouette(as.numeric(unname(Idents(satija_normal7))),
                         dist(satija_normal7@reductions$pca@cell.embeddings[,1:20]))
sil_satija <- silhouette(as.numeric(unname(Idents(seurat))),
                         dist(seurat@reductions$pca@cell.embeddings[,1:20]))
mean(sil_normal2[,3])
mean(sil_normal6[,3])
mean(sil_normal7[,3])
mean(sil_satija[,3]) # Very similar
DimPlot(satija_normal, reduction = "umap", pt.size = 3)
DimPlot(seurat, reduction = "umap", pt.size = 3)
```
